Makefile
pom.xml
src/main/assembly/assembly.xml
src/main/scala/fi/oph/koski/jettylauncher/JettyLauncher.scala

Create uberjar and serve static resources from it.

fix resourcebase to inside jar

---

src/main/resources/mockdata/koodisto/koodit/opintojenrahoitus.json

Muutoksia opintojenRahoitus-koodistoon (TOR-336)

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/IndexServlet.scala
web/app/Lander.jsx
web/app/style/lander.less
web/app/style/main.less
web/webpack.config.js

Lisää kansalaiskälin länder-sivun.

Kansalaiskali lander

---

src/main/scala/fi/oph/koski/sso/ShibbolethLoginServlet.scala
web/app/IdLogin.jsx
web/app/Lander.jsx
web/app/http.js

- Add simple for to login with national identification number
- Use async GET with `nationalidentificationnumber` header to try to log in
- If success, do redirect to hard-coded redirect URL in client

Add login form to login with national id number

---

src/main/scala/fi/oph/koski/documentation/ExamplesPerusopetuksenLisaopetus.scala
src/main/scala/fi/oph/koski/schema/PerusopetuksenLisaopetus.scala
src/test/resources/backwardcompatibility/perusopetuksenlisaopetus_2018-01-22.json
tiedonsiirtoprotokollan_muutoshistoria.md

Taaksepäinyhteensopiva skeemamuutos

Lisää valinnainen luokkakenttä Perusopetuksen lisäopetuksen suoritukseen

---

src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloFacade.scala
src/main/scala/fi/oph/koski/henkilo/oppijanumerorekisteriservice/OppijanumeroRekisteriClient.scala
src/main/scala/fi/oph/koski/schedule/UpdateHenkilotTask.scala

Korjaa ajastetun henkilötietojen päivityksen

Hae kaikki muuttuneet oppijat ei vain 1000 ensimmäistä

---

README.md

Teidän dokumentaatio kehitystyökaluista on hyvä. Minun piti kuitenkin tehdä nämä pari pientä lisäystä, jotta sain järjestelmän pyörimään lokaalisti.

Tarkennuksia PostgreSQL:n asennuksesta

---

src/main/resources/mockdata/koodisto/koodit/koskikoulutustendiaarinumerot.json
src/main/scala/fi/oph/koski/oppilaitos/OppilaitosServlet.scala
web/app/lukio/lukio.js
web/app/suoritus/Suoritus.js
web/app/uusioppija/Oppiaine.jsx
web/app/uusioppija/UusiAikuistenPerusopetuksenSuoritus.jsx
web/app/uusioppija/UusiLukionSuoritus.jsx
web/app/uusioppija/UusiOpiskeluoikeus.jsx
web/app/uusioppija/lukionSuoritus.js
web/test/page/addOppijaPage.js
web/test/spec/lukioSpec.js
web/test/spec/perusopetusSpec.js

Kuuluu tikettiin: **TOR-355**
Lisätään mahdollisuus lisätä uusi
- lukion oppimäärän
- lukion oppiaineen oppimäärän
opiskeluoikeus.
Haaran ulkopuolella:
- LuVa-oppijoiden lisäys
- paikalliset oppiaineet (https://github.com/Opetushallitus/koski/tree/paikallinen-lukion-oppiaine)

Uusi lukiosuoritus

---

src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala

AikuistenPerusopetuksenOpiskeluoikeusjakso was not handled correctly when invalidating

Handle all OpiskeluoikeudenTila types when invalidating

---

.gitignore
Makefile
pom.xml

Run npm install from Maven

---

src/main/scala/fi/oph/koski/henkilo/HenkiloRepository.scala
src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloFacade.scala
src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloRepository.scala
src/main/scala/fi/oph/koski/schema/Henkilo.scala
src/main/scala/fi/oph/koski/virta/HetuBasedOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/virta/VirtaHenkiloRepository.scala
src/main/scala/fi/oph/koski/ytr/YtrHenkiloRepository.scala
src/test/scala/fi/oph/koski/api/OppijaValidationSpec.scala
src/test/scala/fi/oph/koski/perftest/FixtureDataInserter.scala

Kopio kutsumanimi etunimestä, jos kutsumanimi puuttuu tai ei löydy etunimistä

Kopio kutsumanimi etunimestä

---

src/main/scala/fi/oph/koski/koskiuser/KoskiSession.scala
src/main/scala/fi/oph/koski/tiedonsiirto/IPService.scala
src/test/scala/fi/oph/koski/koskiuser/KoskiSessionSpec.scala

Nyt tulee poikkeus tuotannossa tyyliin: java.net.UnknownHostException: 127.0.0.1, 127.0.0.1: Name or service not known

Korjaa ip tracking jos x-forwarded-for palauttaa monta osoitetta

---

web/app/lukio/lukio.js
web/app/uusioppija/UusiOpiskeluoikeus.jsx
web/test/page/addOppijaPage.js
web/test/spec/ammatillinenSpec.js
web/test/spec/lukioSpec.js

Liittyy: **TOR-355**
Lisätään mahdollisuus lisätä uuteen lukion opiskeluoikeuteen tieto opintojen rahoituksesta.

Lukio-opintojen rahoitustiedon lisääminen

---

web/app/lukio/UusiLukionOppiaineDropdown.jsx
web/app/oppiaine/UusiOppiaineDropdown.jsx
web/app/perusopetus/UusiPerusopetuksenOppiaineDropdown.jsx
web/app/uusioppija/Oppiaine.jsx

Liittyy: **TOR-355**
Mahdollistetaan kälissä _Muiden lukio-opintojen suoritusten_ lisääminen lukio-opiskeluoikeuteen.

Lukion muut opinnot

---

src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotStatistics.scala
src/main/scala/fi/oph/koski/pulssi/KoskiPulssi.scala
src/main/scala/fi/oph/koski/pulssi/PulssiHtmlServlet.scala
web/app/Pulssi.jsx

Yhteenlaskun sijaan haetaan elasticista

Korjaa pulssin kattavuustilasto

---

src/main/scala/fi/oph/koski/oppilaitos/OppilaitosServlet.scala
web/app/uusioppija/UusiIBSuoritus.jsx
web/app/uusioppija/UusiOpiskeluoikeus.jsx
web/app/uusioppija/ibSuoritus.js
web/test/page/addOppijaPage.js
web/test/spec/ibSpec.js

Lisätään mahdollisuus lisätä uusi IB-tutkinnon suorituksen oppija.

Uuden IB-tutkinnon suorituksen lisäys

---

src/main/scala/fi/oph/koski/henkilo/KoskiHenkiloCache.scala
src/main/scala/fi/oph/koski/schedule/UpdateHenkilotTask.scala
src/test/scala/fi/oph/koski/schedule/UpdateHenkilotTaskSpec.scala

Failaa tuotannossa:
```
org.postgresql.util.PSQLException: ERROR: insert or update on table "henkilo" violates foreign key constraint "henkilo_master_oid_fkey"
Detail: Key (master_oid)=(xyz) is not present in table "henkilo".
```

Korjaa scheduled update

---

web/app/components/Dropdown.jsx
web/app/kurssi/UusiKurssiDropdown.jsx
web/app/kurssi/kurssi.js
web/app/lukio/LukionOppiaineEditor.jsx
web/app/lukio/LukionOppiaineetEditor.jsx
web/app/lukio/LuvaEditor.jsx
web/app/lukio/UusiLukionOppiaineDropdown.jsx
web/app/lukio/fragments/LukionOppiaine.jsx
web/app/oppiaine/UusiOppiaineDropdown.jsx
web/app/organisaatio/OrganisaatioHenkiloEditor.jsx
web/app/suoritus/suoritusEditorMapping.jsx
web/test/spec/ibSpec.js

Mahdollistetaan pre-IB-suorituksen muokkaus kälissä.

Pre-IB-suorituksen muokkaus

---

web/app/uusioppija/ibSuoritus.js
web/test/page/addOppijaPage.js
web/test/spec/ibSpec.js

Mahdollistetaan uuden pre-IB-suorituksen lisäys kälin kautta.

Mahdollista uuden pre-IB-oppijan lisäys

---

web/app/ib/IB.jsx
web/app/suoritus/suoritusEditorMapping.jsx
web/test/spec/ibSpec.js

Mahdollistetaan IB-oppiaineille spesifin _taso_-tiedon muokkaus.

Mahdollista IB-oppiaineen tason muokkaaminen

---

src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala

Käytä tiedonsiirron yhteenveto -listassa tallentaja-organisaatiota

---

web/app/kurssi/UusiKurssiPopup.jsx
web/app/suoritus/Koulutusmoduuli.js
web/test/page/opinnotPage.js
web/test/spec/ibSpec.js

Lisätään paikallinen kurssi (lukion / IB:n) sen mukaan, onko kyseessä lukion vai IB:n oppiaine. Muutos koskee vain käliä.

Erotellaan erityyppiset paikalliset kurssit pre-IB-kälissä

---

web/app/ib/IBYhteinenSuoritus.jsx
web/app/style/ib.less
web/app/style/lukio.less
web/app/style/main.less
web/app/suoritus/suoritusEditorMapping.jsx
web/test/page/opinnotPage.js
web/test/spec/ibSpec.js

Extended Essay -suorituksella on mm. pakollinen aine ja aihe. Mahdollistetaan näiden muokkaus kälissä.

Mahdollistetaan IB:n Extended Essay -suorituksen muokkaus

---

.eslintrc
src/main/resources/localization/default-texts.json
web/app/components/withFeatureFlag.jsx
web/app/omattiedot/Header.jsx
web/app/omattiedot/Virheraportointi.jsx
web/app/style/omattiedot.less
web/app/style/popup.less
web/featureFlags.json
web/webpack.config.js

Liittyy: **TOR-80**
- Lisätään placeholder-kälirakenne kansalaisen virheraportointi-toiminnallisuutta varten
- Piilotetaan käli tuotannosta feature flagilla (`FEATURE.OMAT_TIEDOT.VIRHERAPORTOINTI`)

Placeholder-komponentti virheraportointikälille

---

web/app/ib/IBYhteinenSuoritus.jsx
web/app/style/ib.less
web/test/page/opinnotPage.js
web/test/spec/ibSpec.js

Näytetään ja mahdollistetaan muokkaus IB:n Theory of Knowledge suoritukseen sisältyville kursseille.

IB Theory of Knowledge -suorituksen kurssien näyttö

---

src/main/resources/localization/default-texts.json
web/app/omattiedot/virheraportointi/RaportoiVirheestaForm.jsx
web/app/omattiedot/virheraportointi/Yhteystiedot.jsx
web/app/style/raportoi-virheesta-form.less

Näytetään ajax-indikaattori virheraportointilomakkeessa, kun valitun oppilaitoksen sähköpostiosoitetta haetaan.

Lisää ajax-indikaattori sähköpostiosoitteen hakuun

---

src/main/resources/localization/default-texts.json
web/app/ammatillinen/ammatillinenEditors.jsx
web/app/kurssi/KurssiPopup.jsx
web/app/oppija/editors.jsx
web/app/suoritus/OsaaminenTunnustettuEditor.jsx
web/test/page/opinnotPage.js
web/test/spec/ammatillinenSpec.js
web/test/spec/lukioSpec.js

Mahdollistetaan lukion kurssin tunnustettu-tiedon muokkaus

---

src/main/resources/mockdata/eperusteet/rakenne-valma.json
src/main/scala/fi/oph/koski/eperusteet/EPerusteetRepository.scala
src/main/scala/fi/oph/koski/eperusteet/MockEPerusteetRepository.scala
src/main/scala/fi/oph/koski/eperusteet/RemoteEPerusteetRepository.scala
src/main/scala/fi/oph/koski/tutkinto/TutkinnonPerusteetServlet.scala
web/app/uusioppija/UusiAmmatillisenKoulutuksenSuoritus.jsx
web/test/page/addOppijaPage.js
web/test/runner.html
web/test/spec/ammatillinenSpec.js
web/test/spec/valmaSpec.js

Haetaan koulutustyypille validit diaarinumerot myös e-perusteista ja täydennetään sillä koskikoulutustendiaarinumerot-koodistosta kaivettua listaa.

Uutta valma-opiskelijaa luodessa voi valita perusteen

---

web/app/ib/IB.jsx
web/app/ib/IBYhteinenSuoritus.jsx
web/test/page/opinnotPage.js
web/test/spec/ibSpec.js

Näytetään yhteisille IB-suorituksille alaviite kun ennakkoarvosana

---

web/app/perusopetus/PerusopetuksenOppiaineRowEditor.jsx
web/test/spec/perusopetusSpec.js

TOR-424 Piilotetaan kuvaus pakollisilta valtakunnallisilta oppiaineilta

---

web/app/ib/IBKurssinArviointiEditor.js
web/app/kurssi/KurssiPopup.jsx
web/app/kurssi/kurssi.js
web/app/suoritus/Suoritus.js
web/test/spec/ibSpec.js

TOR-440
Arvioinnin effort-tieto voidaan lisätä ja sitä voidaan muokata
- IB-oppiaineen kursseille
- Theory of Knowledge -suorituksen kursseille

Mahdollistetaan IB-kurssin arvioinnin effort-tiedon muokkaus

---

pom.xml
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusQueryService.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusValidationServlet.scala

Välttää pitkäkestoisiin replikasta lukemisiin liittyvät virheet

Hae validoitavat opiskeluoikeudet batcheissa

---

web/app/perusopetus/PerusopetuksenOppiaineetEditor.jsx
web/app/style/perusopetus.less

Tähtimerkinnät mahtuvat korjauksen jälkeen myös sellaisissa tapauksissa, kun on annettu pitkä sanallinen arviointi

Korjaa perusopetuksen oppiaine-taulukon

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotRepository.scala
web/app/date/DateRangeSelection.jsx
web/app/style/oppijataulukko.less
web/app/virkailija/Oppijataulukko.jsx
web/test/page/koskiPage.js
web/test/spec/oppijataulukkoSpec.js
web/test/spec/perusopetusSpec.js

TOR-490
Virkailijan listanäkymä: lisätään kriteeriksi myös päättymispäivä.

Lisätään päättymispäivä oppijalistanäkymään

---

src/main/scala/fi/oph/koski/documentation/KoskiSchemaDocumentHtml.scala

Linkit osoitteessa http://localhost:7021/koski/dokumentaatio/koski-oppija-schema.html?entity=aikuistenperusopetuksenopiskeluoikeus#korkeakoulunopintojaksonsuoritus toimii

Korjaa html-dokumentaation osaamisen tunnustamisen linkit

---

web/app/omattiedot/suoritusjako/DateInputFeedback.jsx
web/app/omattiedot/suoritusjako/SuoritusjakoLink.jsx
web/app/style/global.less
web/test/page/omatTiedotPage.js
web/test/spec/omatTiedotSpec.js

Lisäksi pieni CSS-fiksi kylkeen

Paremmat testit suoritusjakolinkin voimassaolon muokkaamiselle

---

web/app/opiskeluoikeus/OpiskeluoikeudenTilaEditor.jsx
web/app/suoritus/TilaJaVahvistusEditor.jsx

Tallentaa ei toki voi, mutta nyt pystyy korjaamaan virheellisen tilan/rahoitusmuodon/ym

TOR-511 Salli ainoan tilajakson poistaminen ui:ssa

---

src/main/resources/localization/default-texts.json
web/app/date/DateInput.jsx
web/app/omattiedot/suoritusjako/DateInputFeedback.jsx
web/app/omattiedot/suoritusjako/SuoritusjakoLink.jsx
web/app/style/suoritusjako-form.less

Suoritusjakolinkin voimassaoloajan muuttamisen DOM-rakennetta muutettu siten, että ruudunlukija ymmärtää sen paremmin. Lisätty elementti, jossa aria-live -tägi, jolloin ruudunlukija tajuaa sen sisällön päivittyvän.

Lisäparannuksia suoritusjakolinkin voimassaoloajan muuttamiseen ruudunlukijalle

---

web/app/omattiedot/suoritusjako/SuoritusjakoForm.jsx
web/app/style/suoritusjako-form.less
web/app/util/util.js

Lisätty eri kohtiin suoritusjakolomaketta fokussiirtymiä ruudunlukijan käyttäjän avustamiseksi. Lisätty myös ilmoitus suoritusjakolinkin poiston onnistumisesta.

Suoritusjako fokusparannukset part 2

---

web/app/components/ToggleButton.jsx
web/app/editor/ModalDialog.jsx
web/app/omattiedot/header/HeaderButtons.jsx
web/app/omattiedot/suoritusjako/SuoritusjakoForm.jsx
web/app/style/colors.less
web/app/style/global.less
web/app/style/mixins.less
web/app/style/omattiedot.less
web/app/style/suoritusjako-form.less
web/app/style/suoritustaulukko.less

Improve text legibility by making texts larger (e.g. in buttons) and by tweaking colors and font weights. This raises the contrast ratios of problem areas to satisfy level AA.
**N.B. Raamit remains to be fixed.**

Improve contrast (to improve accessibility)

---

src/main/scala/fi/oph/koski/sso/ShibbolethLoginServlet.scala

Näytetään ei suorituksia -sivu geneerisen virhesivun sijaan.
**TOR-523**

Näytä ei suorituksia -sivu eidas-tunnistautuneelle

---

web/app/OmatTiedot.jsx
web/app/components/FloatingActionButton.jsx
web/app/components/ToggleButton.jsx
web/app/omattiedot/header/HeaderButtons.jsx
web/app/polyfills/omattiedot-polyfills.js
web/app/style/floating-action-button.less
web/app/style/main.less
web/app/style/mixins.less
web/app/style/omattiedot.less
web/package-lock.json
web/package.json

Lisätään kansalaisen palveluun kelluva painike suoritusten jakamista varten; on huomattu, että nykyinen sivun yläosassa oleva suoritusjakopainike jää helposti huomaamatta. 
Uusi kelluva painike scrollaa näkymän takaisin ylös ja avaa tarvittaessa suoritusjakonäkymän. Vanha suoritusjakopainike toimii kuten ennenkin.

Kelluva suoritusjakopainike

---

src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/mydata/ApiProxyServlet.scala
src/test/scala/fi/oph/koski/mydata/MyDataAPIProxyServletTest.scala

Palauta 403 jos käyttäjä ei ole antanut OmaData-kumppanille lupaa hakea käyttäjästä tietoja

Forbidden status code

---

src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala

Pääsy `r_henkilo` -tauluun estetään `r_koski_katselija` käyttäjältä
Pääsy `r_henkilo` -tauluun sallitaan `r_koski_henkilo_katselija` käyttäjälle

 raportointikannan lukuoikeudet

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/schema/OsaamisenTunnustaminen.scala

Juhon kuvaus- ja tooltip-muutoksia

---

src/main/resources/reference.conf
src/main/scala/fi/oph/koski/jettylauncher/JettyLauncher.scala
src/main/scala/fi/oph/koski/koskiuser/UserServlet.scala
src/main/scala/fi/oph/koski/raportit/RaportitServlet.scala
src/test/scala/fi/oph/koski/raportit/RaportitSpec.scala

TOR-524 Poista oppijavuosiraportin rajaus testikäyttäjiin

---

src/main/scala/fi/oph/koski/schema/LukioonValmistavaKoulutus.scala

Lisätään pidennettyPäättymispäivä-tiedolle LuVassa lukiota vastaava

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/schema/Lukio.scala

[WIP] Add lukio ulkomaanjaksot description

---

src/main/scala/fi/oph/koski/db/KoskiDatabase.scala

select count(*) from opiskeluoikeus aiheuttaa timeoutin tuotannossa

Nopeuta migraatiotarkistusta

---

src/main/resources/documentation/rajapinnat_luovutuspalvelu.md

- Poistaa wanhaa informaatiota

Luovutuspalvelu dokumentaation siivousta

---

src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/log/AuditLog.scala

Ensure audit logger starts

---

src/main/resources/mockdata/koodisto/koodit/oppiaineetdia.json
src/main/scala/fi/oph/koski/documentation/ExamplesDIA.scala
src/main/scala/fi/oph/koski/schema/DIA.scala

Lisätään DIA-tietomalliin valinnaiset oppiaineet.

Dia-tietomallin valinnaiset oppiaineet

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/mydata/MyDataJakoItem.scala
src/main/scala/fi/oph/koski/mydata/MyDataService.scala
web/app/omadata/luvanhallinta/KayttoLuvat.jsx
web/app/style/kayttoluvat.less

- Yhtenäistää bullet pointit eri näkymien kesken palveluntarjoajan näkemistä tiedoista
- Lisää käyttötarkoitus selosteen mikäli sellainen on palveluntarjoajalle määritelty

yhtenäistä käyttöoikeus tekstit

---

Makefile
pom.xml
src/test/scala/fi/oph/koski/integrationtest/TrustingHttpsClient.scala
web/.snyk
web/package-lock.json
web/package.json

Selenium-päivitystä ei ole kyllä testattu, mutta sen ei pitäisi rikkoa muuta kuin koski-browserstack Jenkins job.

Update deps dec2018

---

src/main/scala/fi/oph/koski/db/KoskiDatabaseMethods.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala

Jostain syystä devillä ei tunnu riittävän to 60s

Kasva raportointikanta db-timeouttia

---

src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala
src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala

Korjaa toimipiste-käsittely raportointikannan latauksessa

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
web/test/spec/ammatillinenSpec.js

[TOR-363](https://jira.csc.fi/browse/TOR-363): Ammatilliseen tutkintoon lisätään keskiarvo-kenttä. Vain ammatilliselle tutkinnolle, ei ammatti- ja erikoisammattitutkinnoille.

TOR-363: Ammatillisen tutkinnon keskiarvo

---

src/main/scala/fi/oph/koski/luovutuspalvelu/SuomiFiService.scala
src/test/scala/fi/oph/koski/luovutuspalvelu/PalveluvaylaSpec.scala
web/app/opiskeluoikeus/OpiskeluoikeusEditor.jsx
web/app/oppija/OpiskeluoikeudetNavBar.jsx
web/test/page/opinnotPage.js
web/test/spec/ammatillinenSpec.js
web/test/spec/korkeakouluSpec.js
web/test/spec/perusopetusSpec.js

Näytti virheellisesti kaikki päätason suoritukset

Korjaa virkailijan opiskeluoikeus välilehti

---

web/app/virkailija/VirkailijaOppijaView.jsx
web/test/spec/oikeudetSpec.js

https://jira.oph.ware.fi/jira/browse/OK-227
https://confluence.oph.ware.fi/confluence/pages/viewpage.action?pageId=39324214

OK-227 Sure-linkki koskeen

---

src/main/resources/mockdata/ytr/080845-471D.json
web/app/suoritus/TilaJaVahvistusEditor.jsx
web/app/ytr/ytr.js
web/test/page/opinnotPage.js
web/test/spec/ylioppilastutkintoSpec.js

Yo-tutkinnoista jotka on suoritettu ennen vuotta 1990 puuttuu vahvistuspäivämäärä, joten niistä ei voi päätellä onko suoritus valmis vai kesken.

Piilota tila ennen vuotta 1990 suoritetuista yo-tutkinnoista

---

src/main/scala/fi/oph/koski/html/PiwikNodes.scala

Koski elää osana opintopolku-kokonaisuutta ja on loogista, että sen analytiikka elää saman kokonaisuuden alla piwikissä kuin opintopolun analytiikka.

Ota käyttöön opintopolkupuolen piwik site-id:t

---

src/main/scala/fi/oph/koski/raportit/Opiskelijavuositiedot.scala

…keet, vaihda rahoitus-sarakkeen sisältö hyödyllisemmäksi

TOR-626 Opiskelijavuositiedot-raportille rahoitus-muutoksia

---

src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala

Ei saa mergetä/viedä tuotantoon ennen kuin puuttuvat koodistorelaatiot on lisätty koodistopalveluun (OPH:laiset hoitaa).

[WIP] TOR-581 Koulutustyyppi pakolliseksi

---

src/main/scala/fi/oph/koski/koskiuser/KoskiSession.scala
src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/KayttooikeusryhmatSpec.scala

Tämä tarvitaan jotta voidaan siirtää opiskeluoikeuksia
koulutustoimijalta toiselle

Monta juuriorganisaatiota sallittu

---

src/main/scala/fi/oph/koski/editor/EditorModelBuilder.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusChangeMigrator.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/test/scala/fi/oph/koski/api/OppijaUpdateSpec.scala
web/test/spec/ammatillinenSpec.js

+ Valmiista ammatillisesta päätason suoritusta ei jäädytetä
+ Ammatillisen päätason suorituksen voi poistaa kälistä

tor-639: Ammatillisen päätason suorituksen jäädytyksen poisto

---

Makefile
src/main/scala/fi/oph/koski/virta/VirtaOppilaitosFuusioFilter.scala
src/test/scala/fi/oph/koski/api/KorkeakouluSpec.scala
src/test/scala/fi/oph/koski/virta/VirtaOppilaitosFuusioFilterSpec.scala
web/test/spec/korkeakouluSpec.js

Pelkkien suoritusten karsiminen ei riitä

Karsi duplikaattiopiskeluoikeudet

---

src/main/scala/fi/oph/koski/schema/MuuAmmatillinen.scala

Tutkinnon osaa pienemmän päätason suorituksen osasuorituksen

---

Makefile
docker-compose.yaml
elasticsearch/Dockerfile
scripts/deploy.sh

Jos on ok muille, niin voisin samalla poistaa kaiken turhan lokaalin logiikan joka liittyy possuun ja elastikkiin.
Eli:
* Possun käynnistys ja lokaalisti käyttäjien ja DBn luominen (ei tarvitse docker-composen kanssa) https://github.com/Opetushallitus/koski/blob/master/src/main/scala/fi/oph/koski/db/KoskiDatabase.scala#L55
* Koko `PostgresRunner` ja `ElasticSearchRunner` classit ja kaiken niihin liittyvän.
Applikaatio logiikkaan ei kuulu ulkoisten depsujen käynnistäminen _edes_ devi ympäristöissä.

docker-compose setup

---

src/main/scala/fi/oph/koski/raportit/AmmatillisenRaportitRepository.scala

Lisää implicit valuet plain sql kyselyille

---

src/main/scala/fi/oph/koski/raportit/LukioRaportti.scala

List:in paralellisointi on hitaampaa

Lukioraportti speedup

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/schema/Suoritus.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillisenTutkinnonOsittainenSuoritusSpec.scala
web/app/ammatillinen/AmmatillinenOsittainenTutkinto.js
web/app/ammatillinen/TutkinnonOsa.js
web/app/suoritus/Suoritus.js
web/app/suoritus/SuoritusEditor.jsx
web/app/suoritus/TilaJaVahvistusEditor.jsx
web/test/spec/ammatillinenSpec.js

- valmiiksi merkatulta osittaiselta ammatillisen tutkinnon osalta vaaditaan ammatillisen tutkinnon osan suoritus.
- sallitaan keskeneräinen yhteisen tutkinnon osa osittaisessa ammatillisessa tutkinnossa jos
keskeneräisellä yhteisellä tutkinnon osalla on vahvistettu osan osa-alueen suoritus.

tor-NumberOfTheBeast \,,/

---

src/main/scala/fi/oph/koski/log/AuditLog.scala
src/main/scala/fi/oph/koski/mydata/MyDataService.scala
src/main/scala/fi/oph/koski/mydata/MyDataServlet.scala
src/test/scala/fi/oph/koski/mydata/MyDataServiceTest.scala

Lisätään auditlogiin tieto luvan antamisesta sekä poistamisesta. Lisätään lokiin myös tieto siitä mille kumppanille lupa on annettu.

TOR-713: my data auditlog

---

web/package-lock.json

Päivitä transitiiviset npm-riippuvuudet

---

src/main/scala/fi/oph/koski/documentation/ExamplesAmmatillinen.scala
web/app/suoritus/OmatTiedotSuoritustaulukko.jsx
web/app/suoritus/Suoritustaulukko.jsx
web/app/suoritus/YhteensaSuoritettu.jsx
web/test/spec/ammatillinenSpec.js

ammatillisen tutkinnon osan laajuus lasketaan osan osa-alueista jos
kyseessä on korkeakouluopintoja tai jatko-valmiuksia tukevia opintoja

tor-625: amiksen tutkinnon osien laajuden laskenta kälissä

---

pom.xml
src/main/resources/db/migration/V66__add_alkamis_ja_paattymispaiva_to_opiskeluoikeus.sql
src/main/resources/reference.conf
src/main/scala/fi/oph/koski/db/Tables.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusQueryService.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/test/scala/fi/oph/koski/api/OppijaQuerySpec.scala

Pantataan tämän mergaamista toistaiseksi. Tuotantoonvienti vaatii käyttökatkoksen aikaavievän kantamigraation takia.

[WIP] Tilastokeskus perffi

---

src/main/resources/db/migration/V66__add_alkamis_ja_paattymispaiva_to_opiskeluoikeus.sql
src/main/scala/fi/oph/koski/db/Tables.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala

Tilastokeskus skeemamuutos vaihe 1

Lisää alkamispaiva- ja paattymispaiva-sarakkeet

---

src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationPerusopetusSpec.scala
validaation_muutoshistoria.md

…at vain jos suorituksella on vahvistus

tor-791: validoidaan nuorten perusopetuksen päättötodistuksen arvosan… 

---

src/main/resources/mockdata/virta/henkilotiedot/141199-418X.xml
src/main/resources/mockdata/virta/opintotiedot/141199-418X.xml
src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
web/test/spec/korkeakouluSpec.js

Jos kyseessä siirto opiskelija, ei käytetä alkuperäistä lähdettä oppilaitoksen päättelyssä

Siirto opiskelijan hanskaus (korkeakoulu)

---

src/main/scala/fi/oph/koski/organisaatio/OrganisaatioRepository.scala

Jotta organisaatio-service palauttaa varhaiskasvatustoimipisteet tulee kutsut tehdä rekisterinpitäjänä.

Tee organisaatiokutsut autentikoituneena

---

src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedot.scala
src/main/scala/fi/oph/koski/schema/LocalizedString.scala
src/test/scala/fi/oph/koski/api/MuuAmmatillinenSpecification.scala
src/test/scala/fi/oph/koski/api/MuuAmmatillinenTestMethods.scala
src/test/scala/fi/oph/koski/api/OpiskeluoikeudenPerustiedotSpec.scala

Ei toiminut oikein englanninkielisille tutkinnoille

Korjaa oppijataulukon tutkinnon nimellä haku

---

src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
web/test/spec/ammatillinenSpec.js

https://jira.csc.fi/secure/RapidBoard.jspa?rapidView=142&view=detail&selectedIssue=TOR-895

tor-895 sallitaan keskiarvo ammattitutkintosuorituksissa kun suoritustapa ops

---

src/main/scala/fi/oph/koski/documentation/ExamplesIB.scala
src/main/scala/fi/oph/koski/schema/IB.scala
src/test/resources/backwardcompatibility/ammatillinen-muuammatillinenkoulutus_2020-01-20.json
src/test/resources/backwardcompatibility/ammatillinen-tutkinnonosaapienempikokonaisuus_2020-01-20.json
src/test/scala/fi/oph/koski/api/OppijaValidationIBSpec.scala

https://jira.csc.fi/browse/TOR-672

Tor-672: IB-tutkinnon CAS-suorituksessa estettävä muiden arvosen kuin S:n anto

---

src/main/resources/mockdata/koodisto/koodistot/erityinenkoulutustehtava.json
src/main/resources/mockdata/koodisto/koodit/erityinenkoulutustehtava.json
src/main/scala/fi/oph/koski/documentation/ExamplesLukio.scala
src/main/scala/fi/oph/koski/schema/DIA.scala
src/main/scala/fi/oph/koski/schema/ErityisenKoulutustehtävänJakso.scala
src/main/scala/fi/oph/koski/schema/InternationalSchool.scala
src/main/scala/fi/oph/koski/schema/Lukio.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/resources/backwardcompatibility/internationalschool_2019-05-15.json
src/test/resources/backwardcompatibility/internationalschool_2019-05-23.json
src/test/resources/backwardcompatibility/internationalschool_2019-09-05.json
src/test/resources/backwardcompatibility/internationalschool_2020-01-28.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2017-10-05.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2017-10-11.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2017-10-16.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2018-02-13.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2018-02-14.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2018-02-23.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2018-05-11.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2019-04-04.json
src/test/resources/backwardcompatibility/lukio-paattotodistus_2020-01-28.json
src/test/scala/fi/oph/koski/api/OppijaValidationErityisenKoulutustehtävänJaksoSpec.scala
src/test/scala/fi/oph/koski/raportit/LukioRaporttiSpec.scala
web/test/spec/diaSpec.js
web/test/spec/lukioSpec.js

Wippiä TOR-745:stä. Tässä pitää vielä ainakin selvittää miten backward compatilibty specit saa pelaamaan.

TOR-745 erityisen koulutustehtävän vanhojen arvojen käytön esto

---

src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusQueries.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusQueryService.scala
src/main/scala/fi/oph/koski/util/Pagination.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAikuistenPerusopetusSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationIBSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationLukioSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationLukioonValmistavaSpec.scala
src/test/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusSpec.scala

- linkitetyt oidit kuntoon
- validaatiovirheviestien parannus

Katselmointikorjauksia

---

src/main/scala/fi/oph/koski/elasticsearch/ElasticSearchIndex.scala

Unohtui aiemmin. Pullari testejä varten.

Rajaa ElasticSearchin http:n näkyvyys

---

src/main/scala/fi/oph/koski/raportit/AikuistenPerusopetusRaportti.scala
src/main/scala/fi/oph/koski/raportit/AikuistenPerusopetusRaporttiRepository.scala
src/main/scala/fi/oph/koski/raportit/RaportitService.scala
src/test/scala/fi/oph/koski/raportit/AikuistenPerusopetusRaporttiSpec.scala

Ei sovelleta osasuoritusten aikarajausta ei-kurssi-tyyppisiin osasuorituksiin.

Korjaa osasuoritusten aikarajaus aikuisten perusopetuksen raportilla

---

web/app/kurssi/KurssiEditor.jsx
web/app/style/kurssi.less
web/app/style/opiskeluoikeus.less
web/app/suoritus/Koulutusmoduuli.js
web/app/suoritus/SuoritusTabs.jsx

Tiketti koskee erityisesti aikuisten perusopetusta

Tor-1013 erota paikallinen oppiaine käyttöliittymässä

---

.gitignore
README.md
src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/raportit/AmmatillinenOpiskelijavuositiedotRaportti.scala
src/main/scala/fi/oph/koski/raportit/EsiopetusRaportti.scala
src/main/scala/fi/oph/koski/raportit/PerusopetuksenVuosiluokkaRaportti.scala
src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
web/test/spec/ammatillinenSpec.js

Mietin, että pitäisikö nuo dokumentaatioparannukset laittaa suoraan masteriin, vai onko parempi, että menevät pullarin kautta, vai onko väliä?

tor-1020: lisätiedon vaikeasti vammainen title käyttöliittymässä

---

pom.xml
src/main/scala/fi/oph/koski/sso/SSOSupport.scala
src/test/scala/fi/oph/koski/raportit/AmmatillinenOpiskelijavuositiedotRaporttiSpec.scala

Scalatra 2.7.0 rikkoo liikaa asioita joten pysytään 2.6.x versiossa :(

Päivitä Scalatra ja Jetty

---

web/app/omattiedot/header/Header.jsx
web/app/omattiedot/header/HeaderButtons.jsx
web/featureFlags.json

Ominaisuudet olleet tuotannossa jo pari vuotta.

Siivoa vanhentuneita ominaisuuslippuja

---

src/main/scala/fi/oph/koski/config/Environment.scala
src/main/scala/fi/oph/koski/html/HtmlNodes.scala
src/main/scala/fi/oph/koski/kela/KelaOppijaConverter.scala
web/.eslintrc
web/app/components/withFeatureFlag.jsx
web/app/kela/KelaOppija.jsx
web/app/kela/KeyValueTable.jsx
web/app/kela/OpiskeluoikeusNav.jsx
web/app/style/kela-virkailija.less
web/app/topbar/NavList.jsx
web/featureFlags.js
web/featureFlags.json
web/webpack.config.js

- Ympäristökohtaiset featureflagit fronttiin
- Frontin featureflagit oli ennen tiedossa jo build-vaiheessa, jolloin poiskytketyt featuret voitiin jättää pois buildista. Koska meillä ei ole ympäristökohtaisia buildeja, poiskytketyt featuret tulevat nyt joka tapauksessa mukaan buildiin vaikka feature olisikin kytketty pois.
- Näytä tilat kela-kälissä

Tor-780 kela-kälin korjaukset

---

src/main/scala/fi/oph/koski/documentation/ExamplesLukio2019.scala
src/main/scala/fi/oph/koski/schema/Lukio2019.scala
src/test/resources/backwardcompatibility/lukioops2019-oppiaineidenoppimaara_2020-08-28.json
src/test/resources/backwardcompatibility/lukioops2019-oppiaineidenoppimaara_2020-08-31.json
src/test/resources/backwardcompatibility/lukioops2019-oppimaara_2020-08-28.json
src/test/resources/backwardcompatibility/lukioops2019-oppimaara_2020-08-31.json
src/test/scala/fi/oph/koski/api/OppijaValidationLukio2019Spec.scala
web/app/kurssi/KurssiEditor.jsx
web/app/suoritus/SuoritusEditor.jsx
web/test/page/opinnotPage.js
web/test/runner.html
web/test/spec/lukio2019Spec.js

https://github.com/Opetushallitus/koski/pull/922 pitää mergetä ensin.

TOR-1037 Toteuta käyttöliittymätesti Lops2021:lle

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/schema/Lukio2019.scala
web/app/lukio/LukionOppiaineEditor.jsx
web/app/lukio/LukionOppiaineetEditor.jsx
web/app/lukio/fragments/LukionOppiaine.jsx
web/app/suoritus/suoritusEditorMapping.jsx
web/test/spec/lukio2019Spec.js

TOR-1037 - lops2021 käyttöliittymäkorjauksia

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/documentation/ExamplesLukio.scala
src/main/scala/fi/oph/koski/documentation/ExamplesLukio2019.scala
src/test/resources/backwardcompatibility/lukioops2019-oppiaineidenoppimaara_2020-09-14.json
src/test/resources/backwardcompatibility/lukioops2019-oppimaara_2020-09-14.json
web/app/lukio/LukionOppiaineEditor.jsx
web/app/lukio/LukionOppiaineetEditor.jsx
web/app/lukio/OmatTiedotLukionOppiaineet.jsx
web/app/lukio/fragments/LukionOppiaineetTableHead.jsx
web/app/lukio/lukio.js
web/app/style/lukio.less
web/app/suoritus/suoritusEditorMapping.jsx
web/test/spec/lukio2019Spec.js

TOR-1037 näytä arvioitujen osasuoritusten yhteislaajuus lops2021:ssä

---

src/main/scala/fi/oph/koski/documentation/ExampleData.scala
src/main/scala/fi/oph/koski/documentation/YleissivistavakoulutusExampleData.scala
src/main/scala/fi/oph/koski/fixture/KoskiDatabaseFixtures.scala
src/main/scala/fi/oph/koski/fixture/LukioDiaIbInternationalOpiskelijaMaaratRaporttiFixtures.scala
src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
src/main/scala/fi/oph/koski/raportit/EsiopetusRaportti.scala
src/main/scala/fi/oph/koski/raportit/LukioDiaIbInternationalOpiskelijamaaratRaportti.scala
src/main/scala/fi/oph/koski/raportit/RaportitAccessResolver.scala
src/main/scala/fi/oph/koski/raportit/RaportitService.scala
src/main/scala/fi/oph/koski/raportit/RaportitServlet.scala
src/main/scala/fi/oph/koski/raportit/Raportti.scala
src/main/scala/fi/oph/koski/util/SQL.scala
src/test/scala/fi/oph/koski/raportit/LukioDiaIbInternationalOpiskelijaMaaratRaporttiSpec.scala
src/test/scala/fi/oph/koski/raportit/RaportitServletSpec.scala
web/app/raportit/Raportit.jsx
web/test/spec/oppijataulukkoSpec.js

Raportille valitaan lukiokoulutus, ib, dia ja international school opiskeluoikeudet

tor-1000: lukiokoulutuksen opiskelijamäärät

---

src/main/scala/fi/oph/koski/documentation/ExamplesLukio2019.scala
src/main/scala/fi/oph/koski/schema/Lukio2019.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/main/scala/fi/oph/koski/validation/TutkintoRakenneValidator.scala
src/test/resources/backwardcompatibility/lukioops2019-oppiaineidenoppimaara_2020-09-21.json
src/test/resources/backwardcompatibility/lukioops2019-oppimaara_2020-09-18.json
src/test/resources/backwardcompatibility/lukioops2019-oppimaara_2020-09-21.json
src/test/scala/fi/oph/koski/api/OppijaValidationLukio2019Spec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationLukioSpec.scala
validaation_muutoshistoria.md
web/test/spec/lukio2019Spec.js

TOR-1037 lops2021 lisää validointeja

---

src/main/scala/fi/oph/koski/fixture/KoskiDatabaseFixtures.scala
src/main/scala/fi/oph/koski/fixture/PerusopetusOppijaMaaratRaporttiFixtures.scala
src/main/scala/fi/oph/koski/raportit/PerusopetuksenLisäopetusOppijamäärätRaportti.scala
src/main/scala/fi/oph/koski/raportit/PerusopetuksenOppijamäärätRaportti.scala
src/main/scala/fi/oph/koski/raportit/RaportitAccessResolver.scala
src/main/scala/fi/oph/koski/raportit/RaportitService.scala
src/main/scala/fi/oph/koski/raportit/RaportitServlet.scala
src/main/scala/fi/oph/koski/raportit/Raportti.scala
src/test/scala/fi/oph/koski/raportit/PerusopetuksenLisäopetusOppijamäärätRaporttiSpec.scala
src/test/scala/fi/oph/koski/raportit/PerusopetuksenOppijamäärätRaporttiSpec.scala
src/test/scala/fi/oph/koski/raportit/RaportitServletSpec.scala
web/app/raportit/Raportit.jsx

Tässä on vielä epäselvyyttä: speksin mukaan raportille tulee vuosiluokittainen jaottelu
Muuten toteutus melkolailla sama kuin perusopetuksen oppijamääräraportilla.

Tor-999 perusopetuksen lisäopetuksen oppijamääräraportti

---

src/main/scala/fi/oph/koski/raportit/EsiopetusRaportti.scala
src/main/scala/fi/oph/koski/raportit/EsiopetusRaporttiService.scala

Sama fiksi kuin mikä tehtiin esiopetuksen rahoitusraportteihin

Esiopetuksen tarkastusraportti - haetaan myös koulutustoimijan perusteella opinto-oikeuksia rakennettaessa raporttia

---

src/main/resources/localization/default-texts.json
src/main/scala/fi/oph/koski/documentation/ExamplesLukio2019.scala
src/main/scala/fi/oph/koski/schema/Lukio2019.scala
src/main/scala/fi/oph/koski/validation/Lukio2019OsasuoritusValidation.scala
src/main/scala/fi/oph/koski/validation/Lukio2019VieraatKieletValidation.scala
src/test/resources/backwardcompatibility/lukioops2019-oppiaineidenoppimaara_2020-10-07.json
src/test/resources/backwardcompatibility/lukioops2019-oppimaara_2020-10-07.json
src/test/scala/fi/oph/koski/api/OppijaValidationLukio2019Spec.scala
web/test/spec/lukio2019Spec.js

TOR-1037 Lops2021: paranna esimerkkidataa ja tietomallin dokumentaatiota

---

src/main/scala/fi/oph/koski/koskiuser/AuthenticationSupport.scala
src/test/scala/fi/oph/koski/api/KayttooikeusryhmatSpec.scala
web/test/spec/kelaSpec.js

kela käyttää vain omaa rajapintaansa

estä kelan käyttäjätunnuksilla kaikkien virkailija-apien käyttö

---

web/app/lukio/OmatTiedotLukionOppiaineet.jsx
web/test/spec/omatTiedotLukioSpec.js

TOR-1099 lops2021: kansalaisen käyttöliittymä

---

web/app/kela/KeyValueTable.jsx

Sain ongelman toistettua ja verifioin että korjaus toimii. Ei ehkä maksa vaivaa koodata tälle testitapausta kun on niin selkeä bugi?

Korjaa tilojen järjestyksen hyppiminen kela-kälissä

---

pom.xml
src/main/scala/fi/oph/koski/config/Environment.scala
src/main/scala/fi/oph/koski/config/SecretsManager.scala
src/main/scala/fi/oph/koski/config/ShibbolethSecret.scala
src/main/scala/fi/oph/koski/db/KoskiDatabase.scala
src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala
src/main/scala/fi/oph/koski/mydata/MyDataSupport.scala
src/main/scala/fi/oph/koski/servlet/OppijaLoginPageServlet.scala
src/main/scala/fi/oph/koski/sso/ShibbolethLoginServlet.scala
src/main/scala/fi/oph/koski/virta/VirtaClient.scala
src/main/scala/fi/oph/koski/ytr/KoesuoritusService.scala
src/main/scala/fi/oph/koski/ytr/YtrClient.scala
src/main/scala/fi/oph/koski/ytr/YtrS3.scala

- Tietokantojen tunnukset
- YTR ja YTR S3
- Virta
- Shibboleth security

TOR-1155: Secrets Managerin käyttöönotto

---

src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationLukio2019Spec.scala

https://jira.csc.fi/browse/TOR-821

TOR-821 - Lukion oppimäärä, estetään kaksi lukion oppimäärän päätason suoritusta samalle opiskeluoikeudelle

---

src/main/scala/fi/oph/koski/elasticsearch/ElasticSearchIndex.scala

Ensimmäinen vaihe mapping typen poistossa. Vaikuttaa tässä vaiheessa vain uuden indeksin luomiseen ja reindeksointiin.

Mapping type pois

---

src/main/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusServlet.scala

Api palauttaa epävalidia JSON:ia statuksella 200, jos kesken striimauksen tapahtuu virhe.

Paranna virheensietokykyä striimavassa apissa

---

src/main/scala/fi/oph/koski/servlet/ObservableSupport.scala

Jos kesken striimauksen tapahtuu virhe, suljetaan koko http-yhteys, striimiin ei voi lähettää enää virhekoodia, koska status on jo mahdollisesti lähtenyt ensimmäisten pakettien joukossa.

Paranna striimauksen virheenkäsittelyä;

---

.github/workflows/run_tests.yml
.github/workflows/run_valpas_tests.yml
src/main/scala/fi/oph/koski/jettylauncher/JettyLauncher.scala
src/test/scala/fi/oph/koski/valpas/jest/ValpasFrontSpec.scala
valpas-web/.env
valpas-web/README.md
valpas-web/devserver/server.js
valpas-web/package-lock.json
valpas-web/src/api/api.ts
valpas-web/src/api/apiFetch.ts
valpas-web/src/components/navigation/LocalRaamit.tsx
valpas-web/src/index.html
valpas-web/src/utils/url.ts
valpas-web/test/integrationtests/login.test.ts

Nyt kaikki fronttiassetit polussa /valpas/virkailija
Kaikki APIt polussa /koski

TOR-1225 Valpas: Polkujen yksinkertaistaminen

---

src/main/scala/fi/oph/koski/elasticsearch/ElasticSearchIndex.scala
src/main/scala/fi/oph/koski/elasticsearch/IndexManager.scala
src/main/scala/fi/oph/koski/fixture/FixtureServlet.scala
src/main/scala/fi/oph/koski/fixture/KoskiDatabaseFixtures.scala
src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloFacade.scala
src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotIndexer.scala
src/main/scala/fi/oph/koski/schedule/PerustiedotSyncScheduler.scala
src/main/scala/fi/oph/koski/schedule/UpdateHenkilotTask.scala
src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoScheduler.scala
src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala
src/test/scala/fi/oph/koski/api/OpiskeluoikeudenPerustiedotSpec.scala
src/test/scala/fi/oph/koski/api/TiedonsiirtoSpec.scala
src/test/scala/fi/oph/koski/api/VarhaiskasvatusPerustiedotSpec.scala

Katsotaan auttaisiko tämä flaky testeihin.

Pyri tekemään indeksin refresh samalla päivityksen kanssa

---

src/main/scala/ScalatraBootstrap.scala
src/main/scala/fi/oph/koski/valpas/ValpasTestApiServlet.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
valpas-web/src/api/testApi.ts
valpas-web/src/components/navigation/LocalRaamit.less
valpas-web/src/components/navigation/LocalRaamit.tsx
valpas-web/test/integrationtests-env/browser.ts

TOR-1225 Käytä Valppaan mock-dataa vain Valpasta testatessa

---

src/main/scala/ScalatraBootstrap.scala
src/main/scala/fi/oph/koski/fixture/DatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/fixture/FixtureServlet.scala
src/main/scala/fi/oph/koski/fixture/Fixtures.scala
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/henkilo/MockOpintopolkuHenkiloFacade.scala
src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloRepository.scala
src/main/scala/fi/oph/koski/servlet/OppijaLoginPageServlet.scala
src/main/scala/fi/oph/koski/valpas/ValpasTestApiServlet.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasFixtureState.scala
src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
src/test/scala/fi/oph/koski/api/OpiskeluOikeusTestMethods.scala
src/test/scala/fi/oph/koski/schedule/UpdateHenkilotTaskSpec.scala
valpas-web/test/integrationtests-env/browser.ts

TOR-1267 Lisää Valpas mock data v2

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/organisaatio/OrganisaatioHierarkia.scala
src/main/scala/fi/oph/koski/organisaatio/OrganisaatioService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
valpas-web/src/api/api.ts
valpas-web/src/state/types.ts
valpas-web/src/views/HomeView.tsx
valpas-web/src/views/ValpasApp.tsx
valpas-web/test/integrationtests-env/browser.ts
valpas-web/test/integrationtests/homeview.test.ts

TOR-1265 Valppaan väliaikaiselle etusivulle halutut tiedot

---

src/main/scala/fi/oph/koski/oppilaitos/OppilaitosServlet.scala

Mahdollistetaan käyttöliittymästä esiopetuksen oppilaitoksesta valmistavan perusopetuksen opiskeluoikeuden lisääminen

Lisätään perusopetukseen valmistava opetus esiopetustyyppeihin

---

src/main/scala/fi/oph/koski/koskiuser/Kayttooikeus.scala
src/main/scala/fi/oph/koski/koskiuser/KoskiSpecificAuthenticationSupport.scala
src/main/scala/fi/oph/koski/koskiuser/Session.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasSession.scala

TOR-1265 Korjaa Valpas/Koski-käyttöoikeusbugi

---

src/main/scala/fi/oph/koski/valpas/valpasuser/RequiresValpasSession.scala
src/test/scala/fi/oph/koski/valpas/ValpasAuthenticationSpec.scala

WIP TOR-1265 Valpas-käyttöoikeustestit

---

src/main/scala/fi/oph/koski/koskiuser/Session.scala
src/main/scala/fi/oph/koski/organisaatio/OrganisaatioService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/RequiresValpasSession.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockKayttooikeusryhmat.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasSession.scala
valpas-web/test/integrationtests/homeview.test.ts

TOR-1265 Valppaan globaali käyttöoikeus ei toimi oikein

---

valpas-web/src/index.html
valpas-web/src/views/Raamit.tsx
valpas-web/src/views/VirkailijaApp.tsx

TOR-1267: Virkailijaraami- ja reitityskorjauksia

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
src/test/scala/fi/oph/koski/valpas/ValpasDatabaseServiceSpec.scala
valpas-web/src/state/koodistot.ts
valpas-web/src/state/oppijat.ts
valpas-web/src/views/oppija/OppijanOpiskeluhistoria.tsx
valpas-web/test/integrationtests/oppija.test.ts

Ks. commit-viestit
Seuraavassa pullarissa lisää toteutusta ja testejä lisättyjen testioppijoiden päälle.

TOR-1265 Oppijakohtaisen käyttöliittymän parannuksia v.1

---

src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/test/scala/fi/oph/koski/editor/EditorModelBuilderSpec.scala
src/test/scala/fi/oph/koski/json/SensitiveDataFilterSpec.scala
src/test/scala/fi/oph/koski/log/AuditLogSpec.scala
src/test/scala/fi/oph/koski/raportit/AikuistenPerusopetuksenAineopiskelijoidenKurssikertymätSpec.scala
src/test/scala/fi/oph/koski/raportit/AikuistenPerusopetuksenOpiskeluoikeudenUlkopuolisetKurssitSpec.scala
src/test/scala/fi/oph/koski/raportit/AikuistenPerusopetuksenOppijamäärätRaporttiSpec.scala
src/test/scala/fi/oph/koski/raportit/AikuistenPerusopetuksenOppimääränKurssikertymätSpec.scala
src/test/scala/fi/oph/koski/raportit/EsiopetuksenOppijamäärätRaporttiSpec.scala
src/test/scala/fi/oph/koski/raportit/EsiopetusRaporttiSpec.scala
src/test/scala/fi/oph/koski/raportit/PerusopetuksenLisäopetusOppijamäärätRaporttiSpec.scala
src/test/scala/fi/oph/koski/raportit/PerusopetuksenOppijamäärätRaporttiSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasDatabaseServiceSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
src/test/scala/fi/oph/koski/virta/VirtaPerfTester.scala

TOR-1265 Valpas: näytä 9-luokkalaisille aina oikea luokkatieto, paranna testejä

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/main/scala/fi/oph/koski/schema/AikuistenPerusopetuksenAlkuvaihe.scala
src/main/scala/fi/oph/koski/schema/AikuistenPerusopetus.scala
src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/main/scala/fi/oph/koski/schema/DIA.scala
src/main/scala/fi/oph/koski/schema/IB.scala
src/main/scala/fi/oph/koski/schema/IB2019.scala
src/main/scala/fi/oph/koski/schema/InternationalSchool.scala
src/main/scala/fi/oph/koski/schema/Lukio.scala
src/main/scala/fi/oph/koski/schema/Lukio2019.scala
src/main/scala/fi/oph/koski/schema/LukioonValmistavaKoulutus.scala
src/main/scala/fi/oph/koski/schema/Maksuttomuus.scala
src/main/scala/fi/oph/koski/schema/OpiskeluoikeudenLisatiedot.scala
src/main/scala/fi/oph/koski/schema/Opiskeluoikeus.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala
src/test/scala/fi/oph/koski/api/MaksuttomuusSpec.scala

tor-1995 tieto koulutuksen maksuttomuudesta

---

src/main/scala/fi/oph/koski/valpas/repository/ValpasDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/test/integrationtests/oppija.test.ts

TOR-1267: Valpas: palauta muut kuin perusopetuksen opiskeluoikeudet

---

src/main/scala/fi/oph/koski/valpas/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasSession.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala

TOR-1267: Korjaa oppilaitosoikeuksien tarkistus yhdellä oppijalla ja lisää globaalit oikeudet

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/ValpasTestApiServlet.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/repository/Rajapaivat.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasDatabaseService.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasTestBase.scala
src/test/scala/fi/oph/koski/valpas/jest/ValpasFrontSpec.scala
valpas-web/src/api/apiHooks.ts
valpas-web/src/api/testApi.ts
valpas-web/src/components/navigation/LocalRaamit.tsx
valpas-web/test/integrationtests-env/browser.ts
valpas-web/test/integrationtests/oppija.test.ts

TOR-1267 Valppaan käyttöoikeuksien päivämäärärajaukset

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
valpas-web/src/components/forms/Dropdown.tsx
valpas-web/src/components/forms/InputContainer.tsx
valpas-web/src/views/VirkailijaApp.tsx
valpas-web/src/views/hakutilanne/PerusopetusView.less
valpas-web/src/views/hakutilanne/PerusopetusView.tsx
valpas-web/src/views/hakutilanne/VirkailijaNavigation.tsx
valpas-web/test/integrationtests-env/browser.ts
valpas-web/test/integrationtests/perusopetus.test.ts

Ei tue lapsiorganisaation valitsemista

TOR-1268: Yksinkertainen organisaatiovalitsin

---

src/main/scala/fi/oph/koski/valpas/sso/ValpasSSOSupport.scala
valpas-web/devserver/index.js
valpas-web/devserver/server.js

TOR-1225: Lokaalissa logout yms. -redirectit paremmiksi

---

src/main/resources/valpas/localization/valpas-default-texts.json
valpas-web/src/components/typography/NoDataMessage.less
valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
valpas-web/test/integrationtests/perusopetus.test.ts

TOR-1267 Valpas hakutilannetaulukon datojen viimeistely

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/src/state/oppijat.ts
valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
valpas-web/src/views/hakutilanne/PerusopetusView.tsx
valpas-web/test/integrationtests/perusopetus.test.ts

Ks. commit-viestit
Huomaa ennen mergeä, ettei targettina ole vielä master!

TOR-1267 rautaisempi logiikka näytettävän opiskeluoikeuden valintaan

---

src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/fixture/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasDatabaseService.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/test/integrationtests/perusopetus.test.ts

TOR-1267 Käsittele Valppaassa eroamiset oikein tarkastelupäivän perusteella

---

src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
valpas-web/src/state/oppijat.ts
valpas-web/src/views/oppija/OppijanHaut.tsx
valpas-web/test/integrationtests/oppija.test.ts

TOR-1267 Lisää Valpas oppijanäkymään hakujen koulutuksen nimi

---

src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala

TOR-1268 Lisää debug-dataa Valppaan yhden oppijan näkymän backend-kutsuun

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/ValpasHakukoosteService.scala

Näin on sovittu, ja parempi rajoittaa ominaisuusmäärää, joka pitää saada pilottia varten tuotannossa toimimaan.

TOR-1268 Näytä vain yhteishaut Valppaassa

---

src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/Hakukooste.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
src/test/scala/fi/oph/koski/valpas/SureHakukoosteServiceSpec.scala
valpas-web/src/state/externalUrls.ts
valpas-web/src/state/oppijat.ts
valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
valpas-web/src/views/oppija/OppijanHaut.tsx

Tor-1268 kälikorjauksia

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
valpas-web/src/components/containers/IconSection.tsx
valpas-web/src/views/oppija/OppijanYhteystiedot.tsx
valpas-web/test/integrationtests/oppija.test.ts
valpas-web/test/integrationtests/perusopetus.test.ts

TOR-1267 Näytä Valppaassa speksinmukainen turvakieltovaroitus

---

valpas-web/src/i18n/i18n.tsx

Pilotissa on jo ruotsinkielisiä käyttäjiä, tämä olisi heille parempi kuin nykyiset tekniset merkkijonot

TOR-1335 Näytä Valppaassa suomenkielinen teksti, jos lokalisointi puuttuu

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/Hakukooste.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/MockHakukoosteService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/SureHakukoosteService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/ValpasHakukoosteService.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
src/test/scala/fi/oph/koski/valpas/SureHakukoosteServiceSpec.scala
valpas-web/src/state/oppijat.ts
valpas-web/test/integrationtests/oppija.test.ts

Ota käyttöön sure-API:n uusi query-parametri ja paluuarvo.

TOR-1335 Näytä vain aktiiviset haut Valppaan listanäkymässä

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/src/state/oppijat.ts
valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
valpas-web/src/views/hakutilanne/HakutilanneView.tsx

TOR-1335 Paranna Valpas yksikkötestejä ja valvottavien opiskeluoikeuksien käsittelyä

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/Hakukooste.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
src/main/scala/fi/oph/koski/valpas/repository/ValpasYhteystiedot.scala
src/test/scala/fi/oph/koski/valpas/SureHakukoosteServiceSpec.scala
valpas-web/src/state/oppijat.ts
valpas-web/src/views/oppija/OppijanYhteystiedot.tsx
valpas-web/test/integrationtests/oppija.test.ts

TOR-1335 Hakutietojen viimestelyjä

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/src/components/icons/Icon.tsx
valpas-web/src/components/tables/DataTable.tsx
valpas-web/src/state/apitypes/koodistot.ts
valpas-web/src/state/apitypes/opiskeluoikeus.ts
valpas-web/src/state/apitypes/valpasopiskeluoikeudentila.ts
valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
valpas-web/src/views/oppija/OppijanOpiskeluhistoria.tsx
valpas-web/test/integrationtests-env/browser/datatable.ts
valpas-web/test/integrationtests/hakutilanne.test.ts
valpas-web/test/integrationtests/oppija.test.ts

HUOM! Ei saa viedä masteriin ennen kuin https://github.com/Opetushallitus/koski/pull/1307 on viety kaikkiin ympäristöihin

TOR-1228: Opiskeluoikeussarake taulukkonäkymään

---

src/main/scala/ScalatraBootstrap.scala
src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/organisaatio/OrganisaatioRepository.scala
src/main/scala/fi/oph/koski/valpas/ValpasErrorCategory.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServlet.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusInputValidator.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/log/AuditLog.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/FixtureUtil.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasKuntailmoitus.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockKayttooikeusryhmat.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServletSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasRootApiServletSpec.scala
valpas-web/test/integrationtests/hakutilanne.test.ts

TOR-1229 Kuntailmoituksen luonti-API v1

---

valpas-web/src/components/tables/DataTableFilter.tsx

En ymmärrä miten tämä on koskaan edes voinut toimia (esim. demossa). Vanhemmasta toteutuksesta ylijääneet hookit aiheuttivat ikikiersiön.

TOR-1228: Korjaus taulukon hajonneisiin filttereihin

---

src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/henkilo/MockOpintopolkuHenkiloFacade.scala
src/main/scala/fi/oph/koski/valpas/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServlet.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/db/ValpasSchema.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
src/main/scala/fi/oph/koski/valpas/servlet/ValpasApiServlet.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasExampleData.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasKuntailmoitus.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasKuntailmoitusQueryService.scala
src/main/scala/fi/oph/koski/valpas/yhteystiedot/ValpasYhteystiedot.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServletSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusServiceSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasRootApiServletSpec.scala
valpas-web/test/integrationtests/oppija.test.ts

TOR-1229 kuntailmoituksen lomakkeen pohjatiedot -API

---

src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
valpas-web/src/state/accessRights.tsx
valpas-web/src/state/common.ts
valpas-web/src/state/paths.ts
valpas-web/src/views/HomeView.tsx
valpas-web/src/views/VirkailijaApp.tsx
valpas-web/src/views/hakutilanne/HakutilanneView.tsx
valpas-web/src/views/oppija/OppijaView.tsx
valpas-web/test/integrationtests/homeview.test.ts
valpas-web/test/integrationtests/oppija.test.ts

Huom! Vie tuotantoon vasta kun halutaan julkaista!

TOR-1288 Vie Valpas tuotantoon hakeutumisvelvollisuuden valvojille

---

src/main/scala/fi/oph/koski/valpas/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/src/views/hakutilanne/HakutilanneView.tsx
valpas-web/test/integrationtests-env/browser/forms.ts
valpas-web/test/integrationtests/hakutilanne.test.ts
valpas-web/test/integrationtests/homeview.test.ts

TOR-1229: Käsittele lapsiorganisaatiot hakutilanteen osalta Valpas-käyttöliittymässä oikein

---

src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusServiceSpec.scala

Tor-1229: Palauta kuntailmoituksen pohjatiedoissa oppilaitoksen koko tiedot

---

src/main/resources/mockdata/koodisto/koodistot/maatjavaltiot1.json
src/main/resources/mockdata/koodisto/koodit/maatjavaltiot1.json
src/main/scala/fi/oph/koski/koodisto/Koodistot.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/Hakukooste.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
src/main/scala/fi/oph/koski/valpas/yhteystiedot/ValpasYhteystiedot.scala
valpas-web/src/state/apitypes/yhteystiedot.ts
valpas-web/src/views/oppija/OppijanYhteystiedot.tsx
valpas-web/test/integrationtests/oppija.test.ts

TOR-1229: Käsittele hakukooste-API:sta tuleva maa Valppaassa

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
valpas-web/src/components/tables/InfoTable.less
valpas-web/src/state/apitypes/oppija.ts
valpas-web/src/views/oppija/OppijanOppivelvollisuustiedot.tsx
valpas-web/test/integrationtests/oppija.test.ts

TOR-1230: Maksuttomuusoikeuden ja oppivelvollisuuden päättymispäivät

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/src/state/apitypes/opiskeluoikeus.ts
valpas-web/test/integrationtests/oppija.test.ts

TOR-1230: Älä näytä Valppaassa oppivelvollisuuden suorittamiseen kelpaamattomia opintoja

---

src/main/scala/fi/oph/koski/valpas/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaSearchService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/OpiskeluoikeusLisätiedotRepository.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockKayttooikeusryhmat.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/test/scala/fi/oph/koski/valpas/OpiskeluoikeusLisätiedotSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServletSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusServiceSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasRootApiServletSpec.scala
valpas-web/src/state/accessRights.test.tsx
valpas-web/src/state/accessRights.tsx
valpas-web/src/state/apitypes/opiskeluoikeus.ts
valpas-web/src/state/apitypes/oppija.ts
valpas-web/src/views/oppija/OppijaView.tsx
valpas-web/test/integrationtests/maksuttomuushaku.test.ts
valpas-web/test/integrationtests/oppija.test.ts

TOR-1230 Valpas detaljinäkymä maksuttomuus- ja kuntakäyttäjille

---

src/main/scala/fi/oph/koski/http/Http.scala
src/main/scala/fi/oph/koski/valpas/ValpasErrorCategory.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/SureHakukoosteService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/ValpasHakukoosteService.scala
src/test/scala/fi/oph/koski/valpas/SureHakukoosteServiceSpec.scala

TOR-1229: Validoi Sure-API:n koodistokoodit

---

valpas-web/src/state/accessRights.tsx
valpas-web/src/state/featureFlags.tsx
valpas-web/src/views/VirkailijaApp.tsx
valpas-web/src/views/hakutilanne/VirkailijaMainNavigation.tsx
valpas-web/test/integrationtests/homeview.test.ts

- Korjaa bugin, jossa kuntailmoituslinkki näkyi riippumatta feature flagin asennosta
- Poistaa maksuttomuus -feature flagin käytöstä

TOR-1230: Maksuttomuuden viimeistely

---

src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala

TOR-1406 Lisää paremmat testit 17- ja 18-vuotiaiden näkymiselle nuorten perusopetuksessa

---

src/main/scala/fi/oph/koski/valpas/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/test/scala/fi/oph/koski/valpas/ValpasAccessResolverSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/src/state/accessRights.test.tsx
valpas-web/src/state/accessRights.tsx
valpas-web/src/state/apitypes/opiskeluoikeus.ts
valpas-web/src/state/featureFlags.tsx
valpas-web/src/views/VirkailijaApp.tsx
valpas-web/src/views/oppija/OppijaView.tsx
valpas-web/test/integrationtests/oppija.test.ts

TOR-1422 Salli detalijsivupääsy suorittamisen valvonnan oikeuksilla

---

web/app/style/error.less

Pitkät validointivirheilmoitukset näkyviin

---

src/main/resources/localization/koski-default-texts.json
src/main/resources/mockdata/koodisto/koodistot/arviointiasteikkovstvapaatavoitteinen.json
src/main/resources/mockdata/koodisto/koodit/arviointiasteikkovstvapaatavoitteinen.json
src/main/resources/mockdata/koodisto/koodit/koulutus.json
src/main/resources/mockdata/koodisto/koodit/suorituksentyyppi.json
src/main/scala/fi/oph/koski/documentation/ExamplesVapaaSivistystyö.scala
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/koodisto/Koodistot.scala
src/main/scala/fi/oph/koski/schema/VapaanSivistystyöVapaatavoitteinenKoulutus.scala
src/main/scala/fi/oph/koski/validation/VapaaSivistystyöValidation.scala
src/test/resources/backwardcompatibility/vapaasivistystyo-vapaatavoitteinenkoulutus_2021-06-21.json
src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöSpec.scala

Peruskauraa;
Lisätty suoritustyyppi koodistoon, lisätty uusi arvointirakenne, lisätty suorituksen rakenne.
Lisätty examplet.
Lisätty yksi validaatio ja testi validaatiolle; päätason suoritus voidaan vahvistaa vain jos osasuorituksilta löytyy arviointi.

TOR-1171 VST muut (vapaatavoitteiset) koulutukset tietomalli

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
valpas-web/src/views/hakutilanne/HakutilanneView.tsx
valpas-web/test/integrationtests-env/browser/forms.ts
valpas-web/test/integrationtests/hakutilanne.test.ts
valpas-web/test/integrationtests/oids.ts

TOR-1384: Mahdollista ilmoituksen teko lakkautetusta oppilaitoksesta

---

src/main/scala/fi/oph/koski/http/HttpStatus.scala
src/main/scala/fi/oph/koski/organisaatio/OrganisaatioHierarkia.scala
src/main/scala/fi/oph/koski/organisaatio/OrganisaatioRepository.scala
src/main/scala/fi/oph/koski/organisaatio/OrganisaatioService.scala
src/main/scala/fi/oph/koski/valpas/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/ValpasErrorCategory.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServlet.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusInputValidator.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaSearchService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasKuntailmoitus.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/RequiresValpasSession.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/test/scala/fi/oph/koski/valpas/ValpasAccessResolverSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServletSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusServiceSpec.scala
valpas-web/test/integrationtests/kuntailmoituslista.test.ts

- Siivoilua
- Mahdollista kuntailmoituksen teko kuntana
- Pohjatietojen refaktorointia

TOR-1236 ilmoitus kuntana backend-muutoksia

---

valpas-web/jest.config.js
valpas-web/src/components/containers/Accordion.less
valpas-web/src/components/containers/Accordion.tsx
valpas-web/src/components/containers/Modal.less
valpas-web/src/components/containers/Modal.tsx
valpas-web/src/state/animations.ts
valpas-web/src/utils/environment.ts
valpas-web/src/views/ilmoituslomake/IlmoitusForm.less
valpas-web/src/views/ilmoituslomake/IlmoitusForm.tsx
valpas-web/test/integrationtests-env/browser/core.ts
valpas-web/test/integrationtests-env/browser/utils.ts
valpas-web/test/integrationtests/kuntailmoitus.test.ts
valpas-web/test/integrationtests/oppija.test.ts
valpas-web/test/snapshots/components/containers/Accordion.test.tsx.snap

- Accordion-komponentin animointi
- Sulkeutumisanimointi ilmoituslomakkeelle
- Modaalin aukaisu- ja sulkemisanimaatio

TOR-1460: Valpas animoinnit

---

src/main/scala/fi/oph/koski/kela/KelaOppijaConverter.scala
src/main/scala/fi/oph/koski/kela/KelaSchema.scala
src/test/scala/fi/oph/koski/kela/KelaSpec.scala

Kela-scheman muutokset

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
valpas-web/src/views/suorittaminen/oppivelvolliset/SuorittaminenOppivelvollisetTable.tsx
valpas-web/test/integrationtests/suorittaminen.shared.ts

TOR-1402 Suorittamislistan käyttöliittymäkorjauksia

---

src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
web/test/spec/ammatillinenSpec.js

TOR-1484 Lisää maksuttomuustieto ammatillisen tutkinnon osien suoritukselle

---

src/main/scala/fi/oph/koski/valpas/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServletSpec.scala
valpas-web/test/integrationtests/kuntailmoitus.test.ts

TOR-1486 Korjaa ilmoituksen tekeminen nivelvaiheen valvojana

---

src/main/resources/valpas/migration/V5__ilmoitus_opiskeluoikeus_konteksti.sql
src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/db/ValpasDatabaseFixtureLoader.scala
src/main/scala/fi/oph/koski/valpas/db/ValpasSchema.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasKuntailmoitus.scala
src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasKuntailmoitusRepository.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServletSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala

TOR-1391 Kuntailmoituksiin konteksti talteen

---

src/main/scala/fi/oph/koski/fixture/DatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/main/scala/fi/oph/koski/oppivelvollisuustieto/Oppivelvollisuustiedot.scala
src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/test/scala/fi/oph/koski/api/MaksuttomuusSpec.scala
src/test/scala/fi/oph/koski/oppivelvollisuustieto/OppivelvollisuustietoSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/src/views/oppija/OppijaView.tsx
valpas-web/test/integrationtests/hakutilanne.shared.ts
valpas-web/test/integrationtests/hakutilanne.test.ts
valpas-web/test/integrationtests/oppija.test.ts
valpas-web/test/integrationtests/oppijahaku.test.ts

TOR-1488 Korjaa maksuttomuus- ja hetuttomuuspäättelyitä

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/opiskeluoikeus/CompositeOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/KoskiOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaSearchService.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRootApiServlet.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
valpas-web/src/state/apitypes/henkilohaku.ts
valpas-web/src/views/kunta/hetuhaku/KuntaHetuhaku.tsx
valpas-web/src/views/maksuttomuus/MaksuttomuusOppijaSearch.less
valpas-web/src/views/maksuttomuus/MaksuttomuusOppijaSearch.tsx
valpas-web/src/views/maksuttomuus/MaksuttomuusView.tsx
valpas-web/src/views/oppijasearch/OppijaSearch.tsx
valpas-web/src/views/suorittaminen/hetuhaku/SuorittaminenHetuhaku.tsx
valpas-web/test/integrationtests/oppijahaku.test.ts

TOR-1489 Maksuttomuushaun korjaus Kosken uusien validaatiosääntöjen yms. muun halutun mukaiseksi

---

src/main/scala/fi/oph/koski/documentation/InternationalSchoolExampleData.scala
src/main/scala/fi/oph/koski/fixture/MaksuttomuusRaporttiFixtures.scala
src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/oppivelvollisuustieto/Oppivelvollisuustiedot.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/test/scala/fi/oph/koski/api/MaksuttomuusSpec.scala
valpas-web/test/integrationtests/oppijahaku.test.ts

TOR-1489 Korjaa maksuttomuusvalidaatio käyttämään vahvistuspäiviä

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/test/integrationtests/hakutilanne.shared.ts

TOR-1501 Näytä myös vuosiluokattomat perusopetukset Valppaassa

---

src/main/scala/fi/oph/koski/valpas/hakukooste/Hakukooste.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala

TOR-1507 Muuta hakutyyppi valinnaiseksi

---

src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala
src/test/scala/fi/oph/koski/api/MaksuttomuusSpec.scala

TOR-1490 Älä salli maksuttomuutta oppijan ollessa liian vanha

---

src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/documentation/ExamplesLukio.scala
src/main/scala/fi/oph/koski/fixture/DatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/CompositeOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/KoskiOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/main/scala/fi/oph/koski/schema/Lukio.scala
src/main/scala/fi/oph/koski/schema/Lukio2015.scala
src/main/scala/fi/oph/koski/validation/KoskiGlobaaliValidator.scala
src/main/scala/fi/oph/koski/validation/Lukio2015Validation.scala
src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaSearchService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/test/scala/fi/oph/koski/api/MaksuttomuusSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationLukioAlkamispaivaSpec.scala
src/test/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md
validaation_muutoshistoria.md
valpas-web/test/integrationtests/hakutilanne.shared.ts
valpas-web/test/integrationtests/suorittaminen.shared.ts
valpas-web/test/integrationtests/suorittaminen.test.ts

TOR-1457 Maksuttomuus- ja siirtovalidoinnit lukion vanhan opsin mukaisissa opinnoissa

---

src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
src/main/scala/fi/oph/koski/validation/Lukio2015Validation.scala
src/test/scala/fi/oph/koski/api/OppijaValidationLukioAlkamispaivaSpec.scala
validaation_muutoshistoria.md
web/test/spec/oppijataulukkoSpec.js

TOR-1538 Lukion uuden diaarinumeron pakotus vasta 2005 syntyneistä alkaen

---

valpas-web/package-lock.json
valpas-web/package.json

TOR-xxxx: Uusi chrome driver

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala

TOR-1471: Varmista, että int. schoolillakin on aina jokin alkamispäivä

---

src/main/scala/fi/oph/koski/oppivelvollisuustieto/Oppivelvollisuustiedot.scala
src/test/scala/fi/oph/koski/oppivelvollisuustieto/OppivelvollisuustietoSpec.scala

TOR-1485 Päätä oppivelvollisuus myös DIA-tutkinnon tultua suoritetuksi

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala

TOR-1560 Poista deprekoidun rakenteen kotiopetusoppilaat Valppaan näkymistä

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/koodisto/Kunta.scala
src/main/scala/fi/oph/koski/raportit/AhvenanmaanKunnat.scala
src/main/scala/fi/oph/koski/valpas/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/ValpasRouhintaApiServlet.scala
src/main/scala/fi/oph/koski/valpas/log/ValpasAuditLog.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasHeturouhintaService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasHeturouhintaSheets.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasKuntarouhintaService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasKuntarouhintaSheets.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasRouhintaOppivelvollinen.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasRouhintaOppivelvollinenSheetRow.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasRouhintaService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasRouhintaTiming.scala
src/test/scala/fi/oph/koski/valpas/ValpasHeturouhintaSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntarouhintaSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasRouhintaApiServletSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasRouhintaSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasRouhintaTestBase.scala

TOR-1241 Rouhinta kunnan perusteella -backend

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasKuntarouhintaService.scala

TOR-1241 Lisää ajastuslogituksia kuntarouhintaan

---

src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasHeturouhintaService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasKuntarouhintaService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasRouhintaService.scala

TOR-1241: Rouhinnan optimointeja

---

src/main/scala/fi/oph/koski/http/Http.scala

TOR-xxxx Pidennä timeoutteja raportointikannan ongelmien vuoksi

---

src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala

TOR-1601 Uudelleenyritä raportointikannan luonnin viimeistä swap-vaihetta

---

src/main/resources/valpas/localization/valpas-default-texts.json
valpas-web/src/i18n/i18n.tsx
valpas-web/src/views/kunta/hetuhaku/KuntaHetulistahaku.less
valpas-web/src/views/kunta/hetuhaku/KuntaHetulistahaku.tsx
valpas-web/src/views/kunta/hetuhaku/Rouhintaohje.less
valpas-web/src/views/kunta/hetuhaku/Rouhintaohje.tsx
valpas-web/src/views/kunta/kuntarouhinta/KuntarouhintaView.tsx

Splitattu pullarista https://github.com/Opetushallitus/koski/pull/1634 omaksi odottamaan ohjesivun valmistumista.

TOR-1240: Rouhinnan ohjetekstit

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala

TOR-1241 Pidennä Valppaan pääkyselyn sallittua kestoa 60 s => 3 min

---

src/main/scala/fi/oph/koski/valpas/log/ValpasAuditLog.scala
src/test/scala/fi/oph/koski/log/AuditLogTester.scala
src/test/scala/fi/oph/koski/valpas/ValpasRouhintaApiServletSpec.scala

TOR-1241 Jaa liian pitkät auditlog-entryt

---

src/main/resources/mockdata/virta/henkilotiedot/100295-026D.xml
src/main/resources/mockdata/virta/opintotiedot/100295-026D.xml
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoService.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoServlet.scala
src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
web/app/omattiedot/suoritusjako/SuoritusIdentifier.js

Tässä muutetaan tiettyjen opiskeluoikeuksien rakennetta merkittävästi ja Virta-testit ei ole kovin kattavat, joten tätä pitäisi ehkä vielä testailla käytännössä ennen mergeä.

Tor-1558/1504 Korjaa suoritusjako avoimen opinnoille ja opiskelijaliikkuvuudelle

---

src/main/scala/fi/oph/koski/log/AuditLog.scala
src/main/scala/fi/oph/koski/log/LogConfiguration.scala
src/main/scala/fi/oph/koski/log/Logging.scala
src/test/scala/fi/oph/koski/log/AuditLogSpec.scala

TOR-1241 Robustimpi logitus rivipituuksien rajoitusten kanssa

---

valpas-web/src/state/featureFlags.tsx
valpas-web/src/views/VirkailijaApp.tsx
valpas-web/src/views/kunta/KuntaNavigation.tsx
valpas-web/src/views/kunta/hetuhaku/KuntaHetuhaku.tsx

TOR-1241 Poista feature-flagit rouhintatoiminnoista

---

src/main/scala/fi/oph/koski/log/LogUtils.scala
src/main/scala/fi/oph/koski/log/Logging.scala
src/main/scala/fi/oph/koski/log/MaskedSlf4jRequestLogWriter.scala
src/test/scala/fi/oph/koski/valpas/ValpasRootApiServletSpec.scala
valpas-web/test/integrationtests/meta.test.ts

TOR-1612 Logitusparannuksia

---

src/main/scala/fi/oph/koski/henkilo/OppijanumeroRekisteriClient.scala

TOR-1612 Uudelleenyritä idempotentteja ONR POST-kutsuja

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasRajapaivatService.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala

TOR-1630: Korjaa Valpas-testit toimimaan muulloin kuin v. 2021

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasRajapaivatService.scala
src/main/scala/fi/oph/koski/valpas/rouhinta/ValpasKuntarouhintaService.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala

TOR-1630: siisti rajapäiväkoodia

---

src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala

TOR-xxxx: Lisää ajastuslogitus raportointikannan generointiin

---

src/main/resources/db/migration/V77__add_suoritustyypit_to_opiskeluoikeus.sql

default-value migraatiotiedostoon

suoritustyypin lisääminen kentäksi; 

---

pom.xml
src/main/resources/documentation/rajapinnat_luovutuspalvelu.md
src/main/resources/mockdata/organisaatio/hierarkia/1.2.246.562.10.00000000001.json
src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
src/main/scala/fi/oph/koski/documentation/ExamplesAmmatillinen.scala
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
src/main/scala/fi/oph/koski/koskiuser/Session.scala
src/main/scala/fi/oph/koski/organisaatio/MockOrganisaatioRepository.scala
src/main/scala/fi/oph/koski/schema/KoskiSchema.scala
src/main/scala/fi/oph/koski/ytl/YtlSchema.scala
src/main/scala/fi/oph/koski/ytl/YtlService.scala
src/main/scala/fi/oph/koski/ytl/YtlServlet.scala
src/test/scala/fi/oph/koski/raportit/RaportitServletSpec.scala
src/test/scala/fi/oph/koski/ytl/YtlSpec.scala
web/test/spec/oppijataulukkoSpec.js

TOR-1242 YTL:n KOSKI-rajapinta vaihe 2

---

src/main/scala/fi/oph/koski/ytl/YtlService.scala

YTL Koski-rajapinta vaihe 3

---

src/main/scala/fi/oph/koski/ytl/YtlSchema.scala
src/main/scala/fi/oph/koski/ytl/YtlService.scala
src/test/scala/fi/oph/koski/ytl/YtlSpec.scala

TOR-1242: YTL-API: Palauta myös linkitetyn oppijaoidin pääoppijaoid

---

src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/test/scala/fi/oph/koski/api/OppijaValidationIBSpec.scala
src/test/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoaderPerfTester.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
validaation_muutoshistoria.md
valpas-web/test/integrationtests/hakutilanne.shared.ts
valpas-web/test/integrationtests/oppija.test.ts
valpas-web/test/integrationtests/suorittaminen.shared.ts
valpas-web/test/integrationtests/suorittaminen.test.ts

…keuden alkamispäivän suhteen, sallittu kaikki preib2015 suoritukset oppivelvollisuuden suorittamiseen kelpaavaksi

TOR-1632 pre-ib2015 maksuttomuuden validoinnin muutokset ja oppivelvollisuuden suorittamiseen kelpaavuuden muutokset

---

src/main/resources/documentation/rajapinnat_luovutuspalvelu.md
src/test/scala/fi/oph/koski/ytl/YtlSpec.scala

TOR-1242 YTL-rajapinnan parannuksia

---

src/test/scala/fi/oph/koski/migri/MigriSpec.scala

TOR-xxxx: Lisää Migri-API:lle testit linkitetyille oppijoille

---

src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
src/main/scala/fi/oph/koski/documentation/ExampleData.scala
src/main/scala/fi/oph/koski/organisaatio/MockOrganisaatioRepository.scala
src/main/scala/fi/oph/koski/ytl/YtlSchema.scala
src/test/scala/fi/oph/koski/ytl/YtlSpec.scala

TOR-1647 Korjaa YTL-API:ssa vahvistusten deserialisointi

---

src/main/scala/fi/oph/koski/koskiuser/KoskiSpecificAuthenticationSupport.scala
src/main/scala/fi/oph/koski/koskiuser/MockKayttooikeusryhmat.scala
src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
src/main/scala/fi/oph/koski/koskiuser/Session.scala
src/main/scala/fi/oph/koski/organisaatio/MockOrganisaatioRepository.scala
src/main/scala/fi/oph/koski/userdirectory/DirectoryClient.scala
src/main/scala/fi/oph/koski/userdirectory/OpintopolkuDirectoryClient.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockKayttooikeusryhmat.scala
src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasMockUsers.scala
src/test/scala/fi/oph/koski/api/KäyttöoikeusryhmätSpec.scala

TOR-1242 Käyttöoikeuskorjauksia

---

src/main/scala/fi/oph/koski/valpas/hakukooste/Hakukooste.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala

TOR-xxxx: Pikafiksi: hakukohdeKoulutuskoodi valinnaiseksi kentäksi

---

src/main/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusServlet.scala
src/test/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusSpec.scala

TOR-1646 Dokumentoi testillä tilastokeskus-rajapinnan toiminta nykyistä paremmin

---

src/main/scala/fi/oph/koski/ytl/YtlSchema.scala
src/test/scala/fi/oph/koski/ytl/YtlSpec.scala

TOR-1662: Lisää YTL-APIin lukion suoritusten tyypit

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceTestBase.scala
valpas-web/test/integrationtests/hakutilanne.shared.ts

TOR-1674: Korjaa Valppaassa näkyvä vuosiluokkatietoa joiltain oppijoilta

---

src/main/scala/fi/oph/koski/sure/SureServlet.scala
src/test/scala/fi/oph/koski/sure/SureSpec.scala

TOR-1671 Älä palauta VST-vapaatavoitteisia Surelle

---

src/main/resources/db/migration/V81__add_mitatoity_and_suostumus_peruttu_timestamps.sql
src/main/scala/fi/oph/koski/db/KoskiTables.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/KoskiOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusPoistoUtils.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotIndexer.scala
src/main/scala/fi/oph/koski/perustiedot/PerustiedotSyncRepository.scala
src/main/scala/fi/oph/koski/suostumus/SuostumuksenPeruutusService.scala
src/main/scala/fi/oph/koski/suostumus/SuostumuksenPeruutusServlet.scala
src/main/scala/fi/oph/koski/validation/VapaaSivistystyöValidation.scala
src/test/scala/fi/oph/koski/api/SuostumuksenPeruutusSpec.scala
src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
validaation_muutoshistoria.md
web/app/omattiedot/OmatTiedotOpiskeluoikeus.jsx

TOR-1670 Poista VST vapaatavoitteinen opiskeluoikeus mitätöitäessä

---

src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
src/test/scala/fi/oph/koski/virta/VirtaXMLConverterSpec.scala

Jos opiskeluoikeuden tila on päättynyt, hae nimi päättymisen päivällä.
Jos opiskeluoikeuden tila on kesken, hae nimi tällä päivällä.
Jos opiskeluoikeudella ei ole tiloja, hae nimi viimeisimmällä suorituksen vahvistuksen päivällä.

TOR-1287 korjaa organisaation nimen päättely historiasta Virta-datasta

---

src/main/resources/mockdata/virta/henkilotiedot/080795-884U.xml
src/main/resources/mockdata/virta/opintotiedot/080795-884U.xml
src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
src/test/scala/fi/oph/koski/virta/VirtaXMLConverterSpec.scala
web/test/spec/korkeakouluSpec.js
web/test/spec/omatTiedotSpec.js

Näytä Koskessa fuusioitunut myöntäjäorganisaatio (rooli 5) jos olemassa.

TOR-1041 & TOR-904 Virta-organisaation nimen näyttäminen

---

src/main/scala/fi/oph/koski/html/HtmlNodes.scala
src/main/scala/fi/oph/koski/html/PiwikNodes.scala
src/main/scala/fi/oph/koski/servlet/IndexServlet.scala
src/main/scala/fi/oph/koski/servlet/OppijaLoginPageServlet.scala
src/main/scala/fi/oph/koski/util/ChainingOps.scala
src/main/scala/fi/oph/koski/util/JsStringInterpolation.scala

- Interpolaatio turvallisen js-koodin generointiin
- Korjaa xss-haavoittuvuus cas-oppija-datasta
- Aseta window-objektin arvot siistemmin

TOR-1698: Korjaa XSS-haavoittuvuudet

---

.github/workflows/run_koski_tests_on_branches.yml
Makefile
scripts/checkdoc.sh

Ks. commit-viestit.
Draft PR:stä https://github.com/Opetushallitus/koski/pull/1834 voi katsoa, miltä failure näyttää.

TOR-1699: Lisää CI:lle tarkistus, että validaation_muutoshistoria.md on päivitetty

---

.github/workflows/run_koski_tests_on_branches.yml
Makefile
scripts/checkdoc_schema.sh
scripts/checkdoc_validation.sh

TOR-1699 buildiin epäonnistuva testi puuttuvasta scheman muutoshistoriasta

---

src/main/resources/db/migration/V82__add_koulutusmuoto_and_suoritustyypit.sql
src/main/scala/fi/oph/koski/db/KoskiTables.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusPoistoUtils.scala
src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
src/main/scala/fi/oph/koski/suostumus/SuostumuksenPeruutusService.scala
src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
src/test/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoaderPerfTester.scala
src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala

Mitätöinneistä ja suostumusten peruutuksista poistetut
opiskeluoikeudet lisätään raportointikantaan tulevia
raportointitarpeita varten.

TOR-1670 lisää poistetut opiskeluoikeudet raportointikantaan

---

src/main/resources/valpas/localization/valpas-default-texts.json
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
valpas-web/src/views/hakutilanne/HakutilanneTable.less
valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
valpas-web/test/integrationtests/hakutilanne.shared.ts

TOR-1700 Valpas: Perusopetukseen valmistautuvat hakeutumisvalvottaviksi

---

src/main/scala/ScalatraBootstrap.scala
src/main/scala/fi/oph/koski/config/RunMode.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala

- Raportointikannan full reload -pakotus pois
- Suojaraja opiskeluoikeusmuutoksien tunnistamiseen

TOR-1633: Raportointikannan generointinopeutuksen häntiä

---

src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusServlet.scala
src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala

Höllennetty tarkastusta useamman ammatillisen päätason suorituksen validoinnissa.
Ongelmana ollut aikaisemmin ennen validaatioita virheellisesti siirretyt päätason suoritukset, esimerkiksi yhdistelmä reformin mukainen näyttö + näytötutkintoon valmistava suoritus. Tällaista siirtoa ei voisi nykyään tehdä, ja sen takia poistokaan ei ole onnistunut oikein. Nyt tarkistetaan, että ainakin yksi päätason suoritus mätsää tutkintokoodilta ja suoritustavalta. Tämän pitäisi riittää sikäli, että on olemassa toinen validaatio, joka sallii kahden tai useamman päätason suorituksen siirron vain jos kyseessä on vanhan mallinen näyttö + näyttöön valmistava.
Eli halutaan korjata tapaus, jossa virheellisesti siirretty ennen nykyisiä validaatioita kaksi päätason suoritusta ja toinen pitää poistaa.

TOR - 1642 näyttötutkintoon valmistavan suorituksen poisto

---

src/main/scala/fi/oph/koski/raportointikanta/AikajaksoRowBuilder.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala

Lisää raportointikantaan opiskeluoikeuden aikajaksoihin
maksuttomuuden ja maksullisuuden aikajaksot.

TOR-1493 lisää maksuttomuustiedot raportointikantaan

---

src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala

10 minuuttia ei tuotannossa riittänyt, sillä etenkin r_osasuoritus näyttäisi nopeasti laskettuna kestävän jo nykyisellä datamäärällä yli puoli tuntia.

TOR-1633: Kasvata taulukloonauksen aikarajoja

---

src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
src/test/scala/fi/oph/koski/api/OpiskeluoikeudenMitatointiJaPoistoTestMethods.scala
src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala

Tässä samassa myös korjaus tuotannossa tapahtuvaan taulukloonauksen timeoutiin.
Draft toistaiseksi, ettei vahingossa mergeä vielä, ennen kuin on testattu että tuo korjaus myös toimii.

TOR-1633: Mitätöityjen opiskeluoikeuksien inkrementaalinen päivitys

---

src/main/scala/ScalatraBootstrap.scala
src/main/scala/fi/oph/koski/frontendvalvonta/ReportToService.scala
src/main/scala/fi/oph/koski/frontendvalvonta/ReportUriService.scala
src/test/scala/fi/oph/koski/frontendvalvonta/FrontendValvontaServletSpec.scala

TOR-1707: Content-security-policy -viimeistelykorjauksia

---

src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationPerusopetusSpec.scala
validaation_muutoshistoria.md

TOR-1430: Poista väärä validaatio

---

valpas-web/src/index.html

TOR-xxxx: Lisää oppijaraamien käyttämät fontit Valppaaseen

---

web/app/ammatillinen/LisaaRakenteeseenKuuluvaTutkinnonOsa.jsx
web/app/ammatillinen/TutkinnonOsaToisestaTutkinnostaPicker.jsx
web/app/i18n/Text.jsx
web/app/uusioppija/MuunAmmatillisenKoulutus.jsx
web/app/uusioppija/UusiOpiskeluoikeus.jsx
web/app/uusioppija/UusiVapaanSivistystyonSuoritus.jsx

- Hyväksy tyhjät arvot Text-komponentille;
- Yhtenäistä KoodistoDropdown titlen käyttö;

TOR-1734: Korjaa käyttöliittymässä näkyvät NOT A STRING -tekstit

---

src/main/scala/fi/oph/koski/jettylauncher/JettyLauncher.scala

Muutokse tehty commitissa 64283ab13d01e807ebe60ba444abb13c7530e6d2

Korjataan metrics toimimaan tehtyjen muutosten kanssa

---

src/main/scala/fi/oph/koski/jettylauncher/JettyLauncher.scala

TOR-1707: Lisää etags-headerit Koskeen

---

src/main/scala/fi/oph/koski/jettylauncher/JettyLauncher.scala
valpas-web/postbuild.mjs

TOR-1707: Valpas-hostaus Koskessa viimeistelyjä

---

src/main/scala/fi/oph/koski/validation/KoskiValidator.scala

TOR-1750: Optimoi: Älä tutki linkityksiä tietokannoista turhaan validaatioissa

---

src/main/scala/fi/oph/koski/frontendvalvonta/FrontendValvontaHeaders.scala
src/main/scala/fi/oph/koski/frontendvalvonta/FrontendValvottuServlet.scala
src/main/scala/fi/oph/koski/servlet/IndexServlet.scala

TOR-1707: Korjaa raporttien lataaminen CSP:n kanssa

---

src/main/scala/fi/oph/koski/documentation/ExamplesVapaaSivistystyö.scala
src/main/scala/fi/oph/koski/fixture/DatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusValidationServlet.scala
src/main/scala/fi/oph/koski/oppija/OppijaServlet.scala
src/main/scala/fi/oph/koski/oppija/OppijaServletV2.scala
src/main/scala/fi/oph/koski/organisaatio/MockOrganisaatioRepository.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/main/scala/fi/oph/koski/virta/VirtaOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/ytr/YtrOpiskeluoikeusRepository.scala
src/test/scala/fi/oph/koski/api/OpiskeluoikeusValidationSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationMitatointiSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöVapaatavoitteinenSpec.scala
src/test/scala/fi/oph/koski/tools/AddIgnoreKoskiValidatorFlag.scala
src/test/scala/fi/oph/koski/versioning/BackwardCompatibilitySpec.scala
validaation_muutoshistoria.md

TOR-1752: Lisätään mitätöitävään opiskeluoikeuteen puuttuvat kentät

---

src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/validation/VSTKotoutumiskoulutus2022Validation.scala
src/main/scala/fi/oph/koski/validation/VapaaSivistystyöValidation.scala
src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöMuutSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöVapaatavoitteinenSpec.scala
validaation_muutoshistoria.md
web/app/vapaasivistystyo/UusiVapaanSivistystyonOsasuoritus.tsx

- Korjaa ongelman, jossa juuri luodulle ohjauksen osasuoritukselle ei näkynyt laajuus-inputtia.
- Korjaa ohjauksen osasuorituksen validoinnin puutteet.

TOR-1683: Bugikorjauksia vst-koto-käliin

---

src/main/scala/fi/oph/koski/valpas/kela/ValpasKelaService.scala

TOR-1234: Poista väliaikainen lokitus Kelan ONR:stä haettavista oppijoista

---

src/main/resources/localization/koski-default-texts.json

TOR-xxxx: Lisää puuttuva lokalisaatio raportin lataamisilmoitukselle

---

web/test/spec/perusopetusSpec.js

[WIP] TOR-xxxx: Lisää testin timeout-aikaa flaky-testien korjaamiseksi

---

src/main/scala/fi/oph/koski/config/Environment.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
src/test/scala/fi/oph/koski/migration/MigrationSpec.scala

Kaveripullari: https://github.com/Opetushallitus/koski-aws-infra/pull/114

TOR-1792: Raportointikannan generoinnin parametrisointi

---

src/main/scala/fi/oph/koski/schema/TutkintokoulutukseenValmentavaKoulutus.scala
tiedonsiirtoprotokollan_muutoshistoria.md

TOR-1805: Lisää puuttuva pakotus tuva-tietomallin tyyppi-kentälle

---

src/main/scala/fi/oph/koski/documentation/ExamplesEsiopetus.scala
src/main/scala/fi/oph/koski/documentation/ExamplesPerusopetus.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/resources/backwardcompatibility/esiopetusvalmis_2022-08-15.json
src/test/resources/backwardcompatibility/esiopetusvalmis_2022-08-31.json
src/test/resources/backwardcompatibility/perusopetuksenoppimaara-toiminta-alueittainopiskelija_2022-08-31.json
src/test/scala/fi/oph/koski/api/OppijaValidationEsiopetusSpec.scala
src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala
web/test/spec/perusopetusSpec.js

TOR-1196 Korjaa vammaisuusjaksojen validaatiot

---

src/main/scala/fi/oph/koski/documentation/ApiOperation.scala
src/main/scala/fi/oph/koski/documentation/DocumentationApiServlet.scala
src/main/scala/fi/oph/koski/documentation/Example.scala
src/main/scala/fi/oph/koski/documentation/Examples.scala
src/main/scala/fi/oph/koski/documentation/KoodistoServlet.scala
src/main/scala/fi/oph/koski/documentation/KoskiApiOperations.scala
src/test/scala/fi/oph/koski/api/OppijaExamplesTest.scala
src/test/scala/fi/oph/koski/schema/KoskiOppijaExamplesValidationSpec.scala
src/test/scala/fi/oph/koski/schema/SerializationSpec.scala
src/test/scala/fi/oph/koski/versioning/BackwardCompatibilitySpec.scala

Samalla dokumentoidaan post-rajapinta

TOR-1808: Dokumentoi hetu-apin deprekointi

---

src/main/scala/fi/oph/koski/raportointikanta/AikajaksoRowBuilder.scala
src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/main/scala/fi/oph/koski/schema/OpiskeluoikeudenLisatiedot.scala
src/main/scala/fi/oph/koski/schema/TutkintokoulutukseenValmentavaKoulutuksenLisätiedot.scala
src/test/scala/fi/oph/koski/migration/MigrationSpec.scala

TOR-1817: Lisää raportointikantaan puuttuneet tuva-aikajaksot

---

src/main/scala/fi/oph/koski/documentation/ExamplesTutkintokoulutukseenValmentavaKoulutus.scala
src/main/scala/fi/oph/koski/raportointikanta/AikajaksoRowBuilder.scala
src/main/scala/fi/oph/koski/schema/TutkintokoulutukseenValmentavaKoulutuksenLisätiedot.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/resources/backwardcompatibility/tutkintokoulutukseenvalmentavakoulutus-eivalmistunut_2022-08-15.json
src/test/resources/backwardcompatibility/tutkintokoulutukseenvalmentavakoulutus-eivalmistunut_2022-09-13.json
src/test/scala/fi/oph/koski/api/OppijaValidationTutkintokoulutukseenValmentavaKoulutusSpec.scala
src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md
web/test/spec/tuvaSpec.js

TOR-1828 Poista tuva-tietomallista pidennettyOppivelvollisuus

---

src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
validaation_muutoshistoria.md

Huom! Merge- ja tuotantoonvienti vasta 15.9.

TOR-1804 Ota pidennetty oppivelvollisuus ja vammaisuusvalidaatiot käyttöön tuotannossa 15.9.

---

src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
validaation_muutoshistoria.md

TOR-1804 ota pid oppivelvollisuus ja vammaisuusvalidaatiot kayttoon yritys 2

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
src/test/scala/fi/oph/koski/valpas/ValpasRootApiServletSpec.scala
valpas-web/test/integrationtests/oppija.test.ts

TOR-1817 korjaa esiopetuksen tilat Valppaassa

---

.github/workflows/run_koski_tests_on_branches.yml
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
validaation_muutoshistoria.md
web/test/spec/ammatillinenSpec.js

Validoidaan, että ammatillisella suorituksella on keskiarvo vain jos suoritus on valmis.

TOR-1197 Lisää validaatio ammatillisen keskiarvolle

---

src/main/resources/reference.conf
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationEsiopetusSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationTutkintokoulutukseenValmentavaKoulutusSpec.scala
validaation_muutoshistoria.md

TOR-1833 Poista vammaisuusvalidaatiot käytöstä 1.10.2022 asti

---

src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
validaation_muutoshistoria.md

TOR-1833 Palauta vanhat vammaisuusvalidaatiot päälle tuotantoon

---

src/main/scala/fi/oph/koski/raportit/PaallekkaisetOpiskeluoikeudet.scala
src/test/scala/fi/oph/koski/raportit/PaallekkaisetOpiskeluoikeudetSpec.scala

TOR-1817: Korjaa bugi: esiopetus ei näy päällekäisten opiskeluoikeuksien raportilla

---

src/main/scala/fi/oph/koski/raportit/PaallekkaisetOpiskeluoikeudet.scala
src/test/scala/fi/oph/koski/raportit/PaallekkaisetOpiskeluoikeudetSpec.scala

TOR-1817: Käytä päällekkäisten opiskeluoikeuksien raportissa aina - -merkintää

---

src/main/scala/fi/oph/koski/schema/VapaaSivistystyöKotoutumiskoulutus2022.scala
src/main/scala/fi/oph/koski/validation/VSTKotoutumiskoulutus2022Validation.scala
tiedonsiirtoprotokollan_muutoshistoria.md
validaation_muutoshistoria.md
web/test/spec/vapaaSivistystyoSpec.js

- VST-Koto kieliopintojen laajuusvalidaatio pois
- Lisää puuttuvat arvosanat kieliopintoihin

TOR-1801: Validaatiokorjauksia VST-KOTO-suorituksille

---

src/main/resources/mockdata/eperusteet/rakenne-liiketalouden-perustutkinto-2000-011-2014_2015-08-01_2017-07-31_null.json
src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/test/scala/fi/oph/koski/api/OppijaUpdateSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
src/test/scala/fi/oph/koski/schema/KoskiOppijaExamplesValidationSpec.scala

Opiskeluoikeus validoituu, kun edes yksi voimassa olevista perusteista validoituu.

TOR-1790 lisää testi validaatiolle kun on monta perustetta samaan aikaan voimassa

---

src/main/scala/fi/oph/koski/opiskeluoikeus/KoskiOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillisenTutkinnonOsittainenSuoritusSpec.scala
validaation_muutoshistoria.md

Sallitaan valmis-tila ilman keskiarvoa "kuoriopiskeluoikeuden" suoritukselle.

TOR-1197 Huomioi linkitetty opiskeluoikeus ammatillisen validaatiossa

---

src/main/scala/fi/oph/koski/schema/AikuistenPerusopetus.scala
src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/main/scala/fi/oph/koski/schema/DIA.scala
src/main/scala/fi/oph/koski/schema/EuropeanSchoolOfHelsinki.scala
src/main/scala/fi/oph/koski/schema/InternationalSchool.scala
src/main/scala/fi/oph/koski/schema/Lukio.scala
src/main/scala/fi/oph/koski/schema/Opiskeluoikeus.scala
src/main/scala/fi/oph/koski/schema/TutkintokoulutukseenValmentavaKoulutus.scala
src/main/scala/fi/oph/koski/validation/TutkintokoulutukseenValmentavaKoulutusValidation.scala
src/test/scala/fi/oph/koski/api/OppijaValidationTutkintokoulutukseenValmentavaKoulutusSpec.scala
validaation_muutoshistoria.md

TOR-1852 Korjaa Tuvan sallitut tilat

---

src/main/scala/fi/oph/koski/documentation/ExampleData.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/validation/JotpaValidation.scala
src/test/scala/fi/oph/koski/api/JotpaValidationSpec.scala
src/test/scala/fi/oph/koski/ytl/YtlSpec.scala
validaation_muutoshistoria.md

Odottaa vastausta siitä miten tämän tarkalleen pitää toimia.

TOR-1726: JOTPA-rahoituksen konsistenttiuden validaatio

---

src/main/scala/fi/oph/koski/validation/TutkintokoulutukseenValmentavaKoulutusValidation.scala
src/test/scala/fi/oph/koski/api/OppijaValidationTutkintokoulutukseenValmentavaKoulutusSpec.scala

TOR-1852: Ilmaise tilat tuvan validointivirheessä selkeämmin

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/schema/Suoritus.scala
tiedonsiirtoprotokollan_muutoshistoria.md

TOR-xxxx: Deprekoi suorituksen tila -kenttä selkeämmin

---

src/main/resources/localization/koski-default-texts.json
src/main/resources/reference.conf
src/main/scala/fi/oph/koski/documentation/ExamplesEuropeanSchoolOfHelsinki.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/schema/EuropeanSchoolOfHelsinki.scala
src/main/scala/fi/oph/koski/validation/EuropeanSchoolOfHelsinkiValidation.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/resources/backwardcompatibility/EuropeanSchoolofHelsinki_2022-11-09.json
src/test/resources/backwardcompatibility/EuropeanSchoolofHelsinki_2022-11-11.json
src/test/scala/fi/oph/koski/api/OppijaValidationEuropeanSchoolOfHelsinkiSpec.scala
web/test/spec/europeanSchoolOfHelsinkiSpec.js

TOR-1685 ESH-tietomallin parannuksia

---

src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md
validaation_muutoshistoria.md

Tarkennus ammatillisen validaatioon: keskiarvo vaaditaan osatutkintotavoitteelliselta jos valmistunut 1.1.2022 jälkeen

TOR-1854 Keskiarvo osatutkintotavoitteiseen ammatilliseen perustutkintoon

---

src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasExampleData.scala
valpas-web/README.md
valpas-web/src/views/oppija/OppijanOppivelvollisuustiedot.tsx
valpas-web/test/integrationtests/kansalainen.test.ts
valpas-web/test/integrationtests/oppija2.test.ts

Näytä myös menneet oppivelvollisuuden keskeytykset

TOR-1827 Valpas: muokkaa menneitä keskeytyksiä

---

src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusChangeValidator.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/main/scala/fi/oph/koski/validation/DateValidation.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationPerusopetusSpec.scala
validaation_muutoshistoria.md

Ajetaan validaatio myös siirroissa, joissa aiempi opiskeluoikeus mergetään uuden kanssa.

TOR-1834 alkamispäivän validaatio opiskeluoikeuden migraatioon

---

src/main/scala/fi/oph/koski/migri/MigriService.scala
src/main/scala/fi/oph/koski/migri/MigriServlet.scala
src/test/scala/fi/oph/koski/migri/MigriServletSpec.scala

Lisätään Migrin rajapintaan tuki valintatietojen hakemiselle listalla hetuja

TOR-1866 hetuhaku Migrille

---

src/main/scala/fi/oph/koski/validation/EuropeanSchoolOfHelsinkiValidation.scala
src/test/scala/fi/oph/koski/api/OppijaValidationEuropeanSchoolOfHelsinkiSpec.scala
web/app/components/ButtonWithConfirmation.jsx
web/app/components/Dropdown.jsx
web/app/date/DateInput.jsx
web/app/editor/EnumEditor.jsx
web/app/editor/ModalDialog.jsx
web/app/esh/EuropeanSchoolOfHelsinkiOsasuorituksetEditor.jsx
web/app/esh/EuropeanSchoolOfHelsinkiOsasuoritusEditor.jsx
web/app/esh/EuropeanSchoolOfHelsinkiSuoritustaulukko.jsx
web/app/esh/UusiEshOsasuoritusDropdown.jsx
web/app/esh/esh.js
web/app/opiskeluoikeus/OpiskeluoikeudenTilaEditor.jsx
web/app/opiskeluoikeus/OpiskeluoikeudenUusiTilaPopup.jsx
web/app/suoritus/SuoritustaulukkoCommon.tsx
web/app/suoritus/TilaJaVahvistusEditor.jsx
web/app/uusioppija/UusiEuropeanSchoolOfHelsinkiSuoritus.jsx
web/app/uusioppija/UusiOpiskeluoikeus.jsx
web/test/e2e/europeanschoolofhelsinki.spec.ts
web/test/e2e/fragments/ESHOsasuoritus.ts
web/test/e2e/pages/oppija/KoskiEshOppijaPage.ts
web/test/e2e/pages/oppija/KoskiOppijaPage.ts
web/test/e2e/pages/oppija/KoskiUusiOppijaPage.ts
web/test/e2e/pages/oppija/components/Dropdown.ts
web/test/e2e/pages/oppija/dialogs/OpiskeluoikeudentilaDialog.ts

TOR-1686 ESH-testejä ja viimeistelyjä

---

src/main/resources/reference.conf
src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusChangeValidator.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepositoryV2.scala
validaation_muutoshistoria.md

Tiukempi päivämäärien validaatio odottaa korjausta lähdejärjestelmiin 1.2.2023 asti (pvm konffataan erikseen tuotantoon)

TOR-1882 Ajastetaan TOR-1834:ssä lisätty validaatio myöhemmäksi

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/oppivelvollisuustieto/Oppivelvollisuustiedot.scala
src/main/scala/fi/oph/koski/raportit/PaallekkaisetOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/schema/EuropeanSchoolOfHelsinki.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationEuropeanSchoolOfHelsinkiSpec.scala
src/test/scala/fi/oph/koski/oppivelvollisuustieto/OppivelvollisuustietoSpec.scala
web/app/esh/EshSuoritustaulukkoCommon.tsx
web/app/esh/EuropeanSchoolOfHelsinkiSuoritustaulukko.jsx
web/app/esh/esh.js
web/app/suoritus/SuoritusEditor.jsx

TOR-1685 ESH-viimeistelyjä osa 2

---

src/main/resources/mockdata/organisaatio/hierarkia/1.2.246.562.10.00000000001.json
src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
src/main/scala/fi/oph/koski/oppilaitos/OppilaitosServlet.scala
src/main/scala/fi/oph/koski/organisaatio/MockOrganisaatioRepository.scala
src/main/scala/fi/oph/koski/organisaatio/Oppilaitostyyppi.scala
src/test/scala/fi/oph/koski/api/OppilaitosServletSpec.scala
src/test/scala/fi/oph/koski/raportit/RaportitServletSpec.scala

TOR-1884 Lisää Pohjoiskalotin koulutussäätiölle ammatilliset opiskeluoikeudet käyttöliittymään

---

src/main/resources/localization/koski-default-texts.json
web/app/editor/PropertiesEditor.jsx
web/app/esh/EshPaatasonKoulutusmoduuliPropertyTitle.jsx
web/app/esh/esh.js
web/test/e2e/europeanschoolofhelsinki.spec.ts
web/test/e2e/pages/oppija/KoskiEshOppijaPage.ts

TOR-1685 Lisää ESH:n koulutuksesta infolinkki Eurooppakoulujen sivulle

---

src/main/scala/fi/oph/koski/eperusteetvalidation/EPerusteisiinPerustuvaValidator.scala
src/main/scala/fi/oph/koski/eperusteetvalidation/TutkintoRakenneValidator.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationPerusopetuksenLisaopetusSpec.scala
src/test/scala/fi/oph/koski/api/OppijaValidationValmaSpec.scala
validaation_muutoshistoria.md

TOR-1879: Vaihda vanhentuneiden oo-tyyppien viimeistä käyttöpäivää

---

src/main/scala/fi/oph/koski/fixture/LukioDiaIbInternationalESHOpiskelijaMaaratRaporttiFixtures.scala
src/test/scala/fi/oph/koski/raportit/IBSuoritustiedotRaporttiSpec.scala

TOR-xxxx: Korjaa testit toimimaan myös vuodenvaihteiden jälkeen

---

src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusChangeValidator.scala
validaation_muutoshistoria.md

TOR-1892 Salli väliaikaisesti oppilaitoksen vaihdos

---

valpas-web/src/state/formValidators.ts

Hyväksy hetu-inputissa uudet välimerkit

TOR-1900 Valpas hetu uudistus

---

src/main/scala/fi/oph/koski/omaopintopolkuloki/OmaOpintoPolkuLokiServlet.scala
src/test/scala/fi/oph/koski/omaopintopolkuloki/OmaOpintoPolkuLokiServletSpec.scala

Lisää huollettavat whoami kyselyyn.
Ks. https://github.com/Opetushallitus/oma-opintopolku-loki/pull/269

TOR-1842 huollettavien tiedot oma-opintopolku-lokiin

---

src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
src/main/scala/fi/oph/koski/documentation/ExamplesAmmatillinen.scala
src/test/resources/backwardcompatibility/ammatillinen-perustutkinto_2023-01-19.json
src/test/scala/fi/oph/koski/perftest/MixedOpiskeluoikeusInserter.scala

TOR-xxxx: Korjaa suorituskykytestit

---

src/main/scala/fi/oph/koski/documentation/ExamplesTaiteenPerusopetus.scala
src/main/scala/fi/oph/koski/validation/TaiteenPerusopetusValidation.scala
src/test/resources/backwardcompatibility/taiteenperusopetus-hyvaksytystisuoritettu_2023-01-23.json
src/test/resources/backwardcompatibility/taiteenperusopetus-lasna_2023-01-23.json
src/test/scala/fi/oph/koski/api/OppijaValidationTaiteenPerusopetusSpec.scala
validaation_muutoshistoria.md

Päivitä TPO suoritusten minimilaajuudet yhden desimaalin tarkkuudelle.

TOR-1691 korjaa TPO suoritusten laajuuksien validointi

---

pom.xml
src/main/scala/fi/oph/koski/http/Http.scala

Päivitystä kokeiltu QA:lla ja todettu toimivaksi yhteyksien osalta. 
https://github.com/http4s/http4s/issues/6933

Päivitä http4s

---

src/main/scala/fi/oph/koski/documentation/ExamplesTutkintokoulutukseenValmentavaKoulutus.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/main/scala/fi/oph/koski/validation/TutkintokoulutukseenValmentavaKoulutusValidation.scala
src/test/resources/backwardcompatibility/tutkintokoulutukseenvalmentavakoulutus-eivalmistunut_2022-08-15.json
src/test/resources/backwardcompatibility/tutkintokoulutukseenvalmentavakoulutus-eivalmistunut_2022-09-02.json
src/test/resources/backwardcompatibility/tutkintokoulutukseenvalmentavakoulutus-eivalmistunut_2022-09-13.json
src/test/resources/opiskeluoikeus_puuttuvilla_defaultvalue_propertyilla.json
src/test/scala/fi/oph/koski/api/OppijaValidationTutkintokoulutukseenValmentavaKoulutusSpec.scala
validaation_muutoshistoria.md
web/test/page/addOppijaPage.js
web/test/spec/tuvaSpec.js

Validoi TUVA-opiskeluoikeuden rahoitusmuodon olemassaolo

TOR-1888 TUVA rahoitusmuodon validaatio

---

.github/workflows/deploy.yml

Lisää ytr-data-loader task def yml:iin

TOR-1639 ytr data loader task definition

---

.github/workflows/test_build_deploy_master.yml

Lisää task definition -jumpat master deploy skriptiin

Päivitä ytr task definition deploy skriptiin

---

src/main/scala/ScalatraBootstrap.scala
src/main/scala/fi/oph/koski/ytr/YtrOppijaConverter.scala
src/main/scala/fi/oph/koski/ytr/download/YtrLaajaOppija.scala
src/main/scala/fi/oph/koski/ytr/download/YtrStatusServlet.scala
src/main/scala/fi/oph/koski/ytr/download/YtrTestServlet.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadTestMethods.scala

TOR-1639 YTR Datat koskeen vaihe 4

---

src/main/resources/reference.conf
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadService.scala

TOR-1639: YTR-datat Koskeen vaihe 5

---

src/main/scala/fi/oph/koski/schema/MuuKuinSäänneltyKoulutus.scala
src/main/scala/fi/oph/koski/schema/VapaaSivistystyö.scala
web/app/vapaasivistystyo/VapaanSivistystyonSuoritustaulukko.tsx

TOR-1896 VST Jotpa -käyttöliittymäkorjauksia

---

owasp-dependency-check-suppressions.xml
pom.xml

uusin versio vaimentaa automaattisesti osan vääristä positiivisista: https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml

Päivitä OWASP uusimpaan versioon,

---

src/main/resources/mockdata/ytr/laaja_080380-2432_140380-336X_220680-7850_240680-087S.json
src/main/scala/fi/oph/koski/kela/KelaYlioppilastutkintoSchema.scala
src/main/scala/fi/oph/koski/schema/Opiskeluoikeus.scala
src/main/scala/fi/oph/koski/schema/Suoritus.scala
src/main/scala/fi/oph/koski/schema/Ylioppilastutkinto.scala
src/main/scala/fi/oph/koski/ytr/YtrConversionUtils.scala
src/main/scala/fi/oph/koski/ytr/YtrOppijaConverter.scala
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadOppijaConverter.scala
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadService.scala
src/main/scala/fi/oph/koski/ytr/download/YtrLaajaOppija.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadOppijaConverterSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md
web/test/spec/ylioppilastutkintoSpec.js

Konvertoidaan raakadata Kosken ylioppilastutkinnoksi.

TOR-1639 YTL-tietomallin konversio

---

src/main/scala/fi/oph/koski/migri/ConvertMigriSchema.scala
src/main/scala/fi/oph/koski/migri/MigriSchema.scala

Lisää luokittelut migrin skeemaan

TOR-1870 luokittelutieto Migrin rajapintaan

---

valpas-web/package-lock.json
valpas-web/package.json
valpas-web/test/integrationtests-env/browser/downloads.ts
valpas-web/test/integrationtests/hetulistarouhinta.test.ts
valpas-web/test/integrationtests/kuntarouhinta.test.ts

Päivitetään Chromedriver. Toistaiseksi pitää skipata tiedostojen latausta käsittelevät testit koska driverissa on bugi: https://github.com/SeleniumHQ/selenium/issues/11637

Update valpas chromedriver

---

src/main/scala/fi/oph/koski/ytr/YtrConversionUtils.scala

- Opiskeluoikeuden tilan käsittely
- YTL-oppilaitoksen lisäys

TOR-1639 korjauksia tietomalliin

---

src/main/scala/fi/oph/koski/ytr/download/YtrSsnData.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadSpec.scala

Korjaa aiemmin syntynyt minMonth/maxMonth bugi ja lisää testi (bugi koski vain lokitusta)

TOR-1639 Korjaa lokitusbugi

---

scalastyle_config.xml
src/main/resources/mockdata/ytr/laaja_080380-2432.json
src/main/resources/mockdata/ytr/laaja_080380-2432_140380-336X.json
src/main/resources/mockdata/ytr/laaja_080380-2432_140380-336X_220680-7850_240680-087S.json
src/main/scala/fi/oph/koski/fixture/Fixtures.scala
src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OidGenerator.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresKoskiOpiskeluoikeusRepositoryActions.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepositoryActions.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresYtrOpiskeluoikeusRepositoryActions.scala
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadOppijaConverter.scala
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadService.scala
src/test/scala/fi/oph/koski/opiskeluoikeus/OidGeneratorSpec.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadKayttooikeudetSpec.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadOppijaConverterSpec.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadVirhetilanteetSpec.scala

TOR-1639 Korjauksia ja parannuksia YTR-downloadiin

---

src/main/scala/fi/oph/koski/omattiedot/OmatTiedotEditorModel.scala
src/main/scala/fi/oph/koski/omattiedot/OmatTiedotServletV2.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoServletV3.scala

TOR-xxxx: Piilota sensitiiviset yms. tiedot myös uudella käyttöliittymällä

---

src/main/scala/fi/oph/koski/ytr/YtrClient.scala

TOR-1639: Yritä toipua ongelmista YTR:n POST-API:ssa yrittämällä uudelleen

---

src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala

TOR-1639: Älä yritä käsitellä YO-tutkintoja Valppaassa

---

src/main/scala/fi/oph/koski/ytr/download/YtrDownloadService.scala

Yritetään oppijan päivitystä uudestaan esim. verkkovirheen sattuessa

TOR-1639: Yritä oppijan päivitystä useamman kerran

---

src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/editor/OppijaEditorModel.scala
src/main/scala/fi/oph/koski/henkilo/HenkiloRepository.scala
src/main/scala/fi/oph/koski/kela/KelaService.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/SuomiFiService.scala
src/main/scala/fi/oph/koski/omattiedot/HuoltajaService.scala
src/main/scala/fi/oph/koski/omattiedot/OmatTiedotEditorModel.scala
src/main/scala/fi/oph/koski/omattiedot/OmatTiedotServletV2.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusValidationServlet.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoServiceV2.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoServletV3.scala
src/test/scala/fi/oph/koski/api/SuoritusjakoSpec.scala
src/test/scala/fi/oph/koski/editor/EditorPerfTester.scala

TOR-932: Refaktoroinnit

---

src/main/resources/db/migration/V92__alter_ytr_download_status_table.sql
src/main/scala/fi/oph/koski/config/Environment.scala
src/main/scala/fi/oph/koski/db/KoskiTables.scala
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadService.scala
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadStatus.scala
src/main/scala/fi/oph/koski/ytr/download/YtrStatusServlet.scala
src/main/scala/fi/oph/koski/ytr/download/YtrTestServlet.scala
src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadSpec.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadTestMethods.scala

TOR-1639 Tallenna ajokertojen statukset

---

.github/workflows/all_tests.yml
Makefile
src/main/resources/mockdata/ytr/100800A057R.json
src/main/resources/mockdata/ytr/151031-620R.json
src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/documentation/DocumentationApiServlet.scala
src/main/scala/fi/oph/koski/documentation/ExamplesMuuAmmatillinen.scala
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
src/main/scala/fi/oph/koski/kela/KelaService.scala
src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotAmmatillinenSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotService.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotYlioppilastutkintoSchema.scala
src/main/scala/fi/oph/koski/ytr/YtrClient.scala
src/test/scala/fi/oph/koski/kela/KelaSpec.scala
src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala
web/test/spec/oppijataulukkoSpec.js

TOR-1025 Jaa suoritetut tutkinnot suoritusjakolinkkinä VAIHE 1

---

src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotAmmatillinenSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotDIASchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotEuropeanSchoolOfHelsinkiSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakouluSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotOpiskeluoikeusRepository.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotService.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotYlioppilastutkintoSchema.scala
src/main/scala/fi/oph/koski/virta/VirtaClient.scala
src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala

TOR-1025 Suoritusjako suoritetuista tutkinnoista VAIHE 2

---

src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotAmmatillinenSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotDIASchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotEuropeanSchoolOfHelsinkiSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakouluSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotService.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotYlioppilastutkintoSchema.scala
src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala

TOR-1025 suoritusjako suoritetuista tutkinnoista VAIHE 3

---

src/main/scala/fi/oph/koski/ytr/YtrClient.scala
web/app/suoritus/OmatTiedotSuoritustaulukko.jsx
web/test/e2e/yotodistus.spec.ts
web/test/spec/omatTiedotSpec.js

Feature flagin poistaminen odottaa että ytr saa rajapinnan valmiiksi ja tuotantoon.

TOR-1933: Digi-yo-todistuksen julkaisu käyttöön

---

.github/workflows/run_koski_tests_on_branches.yml
.github/workflows/test_build_deploy_master.yml
README.md

Esimerkki ajosta, jossa testit skipattiin: https://github.com/Opetushallitus/koski/actions/runs/5044924532/jobs/9048564734?pr=2533
Tässä ne taas lähtivät normaalisti ajooin: https://github.com/Opetushallitus/koski/actions/runs/5044947080

Älä aja testejä, jos commit-viestissä [skip-tests]

---

src/main/scala/fi/oph/koski/kela/KelaSchema.scala
src/main/scala/fi/oph/koski/schema/Korkeakoulu.scala
src/main/scala/fi/oph/koski/schema/Opiskeluoikeus.scala
src/main/scala/fi/oph/koski/schema/VapaaSivistystyö.scala
src/main/scala/fi/oph/koski/schema/Ylioppilastutkinto.scala

TOR-1984: Alkamis- ja päättymispäivät uudelleenkäytettäviksi

---

src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakouluSchema.scala
src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala
web/app/types/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakoulunLisatiedot.ts
web/app/types/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakoulunOpiskeluoikeus.ts

TOR-1025: Lisää Virta-opiskeluoikeuden tyyppi suoritettujen tutkintojen skeemaan

---

.github/workflows/run_security_checks.yml
Makefile

- Lisää uudelleenyrityksiä owaspille ja pitkä kakku
- dropme: aja owasp pushin yhteydessä

TOR-XXX: Paranna owaspin ajoa

---

.github/workflows/run_security_checks.yml

- Palauta exitcode 0 onnistuneelle owasp-ajolle
- dropme: ajetaan security test pushilla

TOR-XXX: Älä näytä epäonnistuneena onnistunutta owasp-ajoa

---

src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresKoskiOpiskeluoikeusRepository.scala
src/test/scala/fi/oph/koski/api/SuoritusjakoAPISpec.scala

- Testi suoritusjaon muuttamalle aikaleimalle
- Päivitä suoritusjakokenttä ilman aikaleiman päivittymistä

TOR-2000: Ei aikaleiman päivitystä suoritusjakolinkkiä luotaessa

---

src/main/resources/localization/koski-default-texts.json
web/app/AktiivisetJaPaattyneetOpinnot.tsx
web/app/SuoritetutTutkinnot.tsx

TOR-1984: Siisti linkkijakojen sisältökäyttöliittymää

---

src/main/resources/reference.conf
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadOppijaConverter.scala
src/main/scala/fi/oph/koski/ytr/download/YtrDownloadService.scala
src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala
src/test/scala/fi/oph/koski/ytr/download/YtrDownloadOppijaConverterSpec.scala

TOR-1639 YTR-download viimeistelyt

---

src/main/scala/fi/oph/koski/oppivelvollisuustieto/Oppivelvollisuustiedot.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusExampleData.scala
src/main/scala/fi/oph/koski/valpas/oppijahaku/ValpasOppijaSearchService.scala
src/test/scala/fi/oph/koski/oppivelvollisuustieto/OppivelvollisuustietoSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasHeturouhintaSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasKuntarouhintaSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasRootApiServletSpec.scala
src/test/scala/fi/oph/koski/valpas/oppija/ValpasOppijaLaajatTiedotServiceKayttooikeudetSpec.scala
src/test/scala/fi/oph/koski/valpas/oppija/ValpasOppijaTestData.scala
valpas-web/test/integrationtests/hakutilanne.shared.ts
valpas-web/test/integrationtests/suorittaminen.shared.ts
valpas-web/test/integrationtests/suorittaminen.test.ts

Poistetaan oppijan näkyminen oppilaitosten ja kunnan listoilta, kun oppija valmistuu ammatillisesta tutkinnosta

TOR-1987 Valpas: ammatillisesta tutkinnosta valmistuneet poistuvat oppilaitosten ja kunnan näkymistä

---

src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotAikuistenPerusopetusSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotAmmatillinenSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotDIASchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotESHSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotIBSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotInternationalSchoolSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotKorkeakouluSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotLukioSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotMUKSSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotService.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotTuvaSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotVSTSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotYlioppilastutkintoSchema.scala
src/main/scala/fi/oph/koski/typemodel/TsFileUpdater.scala
src/test/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotServiceSpec.scala
web/app/types/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotKoskeenTallennettavaOpiskeluoikeus.ts
web/app/types/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotYlioppilastutkinnonOpiskeluoikeus.ts
web/app/types/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotYlioppilastutkinnonPaatasonSuoritus.ts
web/app/types/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotYlioppilastutkinnonSuorituksenKoulutusmoduuli.ts

TOR-2032 YO-tutkinnot aktiiviset ja päättyneet opinnot -suoritusjakoon

---

src/main/scala/fi/oph/koski/documentation/ExamplesIB.scala
src/main/scala/fi/oph/koski/editor/OppijaEditorModel.scala
src/main/scala/fi/oph/koski/validation/IBValidation.scala
validaation_muutoshistoria.md
web/test/spec/ibSpec.js

TOR-2038: Poista IB-oppiaineen predicted-päättely arviointi-haarasta

---

web/app/omattiedot/header/HuollettavaDropdown.jsx
web/test/e2e/pages/kansalainen/KoskiKansalainenPage.ts
web/test/e2e/yotodistus.spec.ts
web/test/page/omatTiedotPage.js
web/test/spec/huoltajaSpec.js

TOR-1972: Korjaa huoltajan oppijavalitsin

---

web/app/components-v2/opiskeluoikeus/OsasuoritusTable.tsx
web/app/taiteenperusopetus/TaiteenPerusopetusEditor.tsx
web/app/vst/VSTEditor.tsx

Osasuorituksen muokkaus sulki osasuoritustaulukon automaattisesti, eikä se pysynyt kiinni.

TOR-1959: Korjaa Osasuoritustaulukon osasuoritusten avaus- ja sulkemislogiikka

---

.github/workflows/all_tests.yml
.github/workflows/deploy.yml
.github/workflows/run_performance_tests.yml
.github/workflows/run_security_checks.yml
.github/workflows/run_smoketests.yml
.github/workflows/test_build_deploy_master.yml
.github/workflows/update_localizations.yml
.github/workflows/valpas_performance_tests.yml

TOR-xxxx: Yritä korjata github actionsin build-ongelmat käyttämällä uudempaa runneria

---

src/main/scala/fi/oph/koski/documentation/ExamplesAmmatillinen.scala
src/main/scala/fi/oph/koski/documentation/ExamplesMuuAmmatillinen.scala
src/main/scala/fi/oph/koski/kela/KelaAmmatillinenSchema.scala
src/test/resources/backwardcompatibility/ammatillinen-erikoisammattitutkinto_2023-08-08.json
src/test/resources/backwardcompatibility/ammatillinen-erikoisammattitutkinto_2023-08-15.json
src/test/resources/backwardcompatibility/ammatillinen-muuammatillinenkoulutus_2023-08-08.json
src/test/scala/fi/oph/koski/kela/KelaSpec.scala
web/test/spec/ammatillinenSpec.js
web/test/spec/muuAmmatillinenSpec.js

Lisää skeemaan kentät 'täydentääTutkintoa' (Muu ammatillinen), 'tutkinto' ja 'päättymispäivä' (Näyttötutkintoon valmistava).

TOR-2050 kela rajapinnan täydennys

---

src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
src/test/scala/fi/oph/koski/api/OppijaValidationEsiopetusSpec.scala
validaation_muutoshistoria.md

Tarkistetaan jakson kattavuus vain opiskeluoikeuden päättymiseen asti

TOR-2044 Pidennetyn oppivelvollisuuden validaatio

---

.github/actions/koski_frontend_playwright_test/action.yml
.github/actions/koski_frontend_test/action.yml
scripts/cpuhogs.sh
scripts/filehogs.sh
scripts/memhogs.sh
web/test/mocha-chrome-wrapper.js
web/test/page/addOppijaPage.js
web/test/runner.html
web/test/spec/ammatillinenSpec.js
web/test/spec/linkitettyOppijaSpec.js
web/test/spec/lukioSpec.js
web/test/spec/perusopetusSpec.js
web/test/spec/tuvaSpec.js

TOR-xxxx: Vähennä RAM:in käyttöä epästabiilien frontend-testien aikana

---

.github/actions/valpas_integration_test/action.yml
Makefile

TOR-xxxx: Vähennä RAM:in käyttöä myös Valpas-frontend-testien aikana

---

.github/actions/koski_backend_test/action.yml
.github/actions/koski_frontend_playwright_test/action.yml
.github/actions/koski_frontend_test/action.yml
.github/actions/setup_backend/action.yml
.github/actions/valpas_integration_test/action.yml

TOR-xxxx: Käännä testit eri mvn-prosessissa myös backend-testeissä

---

src/test/scala/fi/oph/koski/log/StubAppender.scala

TOR-xxxx: Estä virheet lokibufferin rinnakkaisessa käytössä

---

src/main/resources/mockdata/virta/henkilotiedot/010190-4473.xml
src/main/resources/mockdata/virta/opintotiedot/010190-4473.xml
web/app/omattiedot/suoritusjako/SelectableSuoritusList.jsx
web/app/suoritus/TilaJaVahvistusEditor.jsx
web/test/spec/korkeakouluSpec.js

Mikäli Virrasta tuleva päätason suoritus on "Päättynyt" -tilassa, mutta Kosken näkökulmasta kesken, piilotetaan käyttäjää hämmentävä "Suoritus kesken" tilatieto.

TOR-2042 Päätason suorituksen tila Virta-datan perusteella

---

.github/actions/koski_frontend_playwright_test/action.yml
.github/workflows/all_tests.yml
src/test/scala/fi/oph/koski/api/oppijaupdate/OppijaUpdateSpec.scala
src/test/scala/fi/oph/koski/api/suostumus/SuostumuksenPeruutusSpec.scala
web/test/runner.html

TOR-xxxx: Splittaa hitaimpia testejä vielä vähän lisää

---

valpas-web/test/chunkingSequencer.js
valpas-web/test/integrationtests/hakutilanne.test.ts

TOR-xxxx: Korjaa Valpas-testien chunkkaus

---

src/main/resources/mockdata/eperusteet/rakenne-vst-lukutaitokoulutus.json
web/app/suoritus/KoulutusmoduuliEditor.jsx
web/app/suoritus/Suoritus.js
web/test/spec/suostumuksenPeruutusSpec.js
web/test/spec/vapaaSivistystyoSpec.js

- Lisää koulutus vst-lukutaito-ePerusteen esimerkkidataan
- Korjaa [object Object] -tekstit vst-lukutaitokälistä

TOR-1949: Korjauksia lukutaitokäliin

---

src/main/resources/mockdata/koodisto/koodit/suorituksentyyppi.json
src/main/scala/fi/oph/koski/schema/EB.scala
src/main/scala/fi/oph/koski/schema/EuropeanSchoolOfHelsinki.scala

TOR-2052: Korjaa EB-tutkinnon poistaminen ESH-opiskeluoikeudesta

---

src/main/scala/fi/oph/koski/eperusteetvalidation/EPerusteetLops2019Validator.scala

Uskonnon moduuleja ei erotella sen perusteella, minkä uskonnon oppimäärää
suoritetaan. Muiden aineiden validointi oli jäänyt aiemmasta toteutuksesta
pois.

TOR-1119: Korjauksia lops2019-ePeruste-validointiin

---

src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepositoryActions.scala

TOR-2053: Lisää lokitus sen tutkimiseksi, voiko yhden opiskeluoikeuden päivitystavan poistaa

---

owasp-dependency-check-suppressions.xml

Hiljennä cve-hälyt cve-id:n perusteella

---

pom.xml
web/package-lock.json
web/package.json

- fix: upgrade core-js from 3.32.2 to 3.33.0
- fix: pom.xml to reduce vulnerabilities
- fix: upgrade com.amazonaws:aws-java-sdk-dynamodb from 1.12.559 to 1.12.560
- fix: upgrade com.amazonaws:aws-java-sdk-sts from 1.12.559 to 1.12.560

Snyk-PRs 2740 2741 2743 2744

---

src/main/scala/fi/oph/koski/koodisto/KoodistoMuokkausPalvelu.scala
src/test/scala/fi/oph/koski/koodisto/KoodistoMuokkausPalveluSpec.scala

Paranna koodistojen luonnin yhteensopivuutta koodistojen päivitysten kanssa

---

valpas-web/src/style/typography.less

Korjaa Valppaan fontit

---

web/app/esh/europeanschoolofhelsinkiSuoritus.js
web/app/uusioppija/UusiEBTutkinnonSuoritus.jsx
web/app/uusioppija/UusiOpiskeluoikeus.jsx
web/test/spec/ebTutkintoSpec.js

TOR-2101: EB-tutkinnon luonti epäonnistuu käyttöliittymässä, jos päivämäärää vaihtaa

---

src/main/scala/fi/oph/koski/documentation/PerusopetusExampleData.scala
src/main/scala/fi/oph/koski/schema/YleissivistavaKoulutus.scala
src/test/resources/backwardcompatibility/perusopetuksenoppimaara-ysiluokkalainen_2023-11-27.json
tiedonsiirtoprotokollan_muutoshistoria.md
web/app/types/fi/oph/koski/schema/LukionOmanAidinkielenOpinnot.ts
web/app/types/fi/oph/koski/schema/OmanAidinkielenOpinnotLaajuusKursseina.ts
web/app/types/fi/oph/koski/schema/OmanAidinkielenOpinnotLaajuusOpintopisteina.ts
web/app/types/fi/oph/koski/schema/OmanAidinkielenOpinnotLaajuusVuosiviikkotunteina.ts
web/test/spec/perusopetusSpec.js

TOR-2092 Salli laajemmat oman äidinkielen arvosanat

---

src/main/scala/fi/oph/koski/documentation/ExamplesYlioppilastutkinto.scala
src/main/scala/fi/oph/koski/validation/Lukio2019EPerusteValidation.scala
src/main/scala/fi/oph/koski/ytr/YtrClient.scala
src/main/scala/fi/oph/koski/ytr/YtrMockDataUpdater.scala
src/main/scala/fi/oph/koski/ytr/YtrRepository.scala
src/test/scala/fi/oph/koski/ytr/YtrClientSpec.scala

TOR-2001: Älä välitä hetuja URL:ssa YTR:lle

---

src/main/scala/fi/oph/koski/ytr/YtrClient.scala

TOR-xxxx: Uudelleenyritä POST-kutsuja digitodistus status-pyynnöissä

---

src/main/scala/fi/oph/koski/eperusteet/EPerusteRakenne.scala
src/main/scala/fi/oph/koski/eperusteetvalidation/TutkintoRakenneValidator.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/tutkinto/EPerusteetTutkintoRakenneConverter.scala
src/main/scala/fi/oph/koski/tutkinto/TutkintoRakenne.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationAmmatillinenSpec.scala
validaation_muutoshistoria.md

TOR-1923 Ammatillisen tutkintonimikevalidaatio

---

src/main/resources/mockdata/koodisto/koodit/oppiaineetib.json
src/main/scala/fi/oph/koski/schema/InternationalSchool.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationInternationalSchoolSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md
web/app/types/fi/oph/koski/schema/MuuDiplomaOppiaine.ts
web/test/spec/internationalschoolSpec.js

Lisää uusi IB oppiaine DIS ja salli haarassa MuuDiplomaOppiaine

TOR-1920 Lisää uusi MuuDiplomaOppiaine

---

src/main/scala/fi/oph/koski/ytr/download/YtrDownloadService.scala

TOR-2001: Korjaa kaatuva YTR-lokitus

---

src/main/scala/fi/oph/koski/documentation/PerusopetusExampleData.scala
src/main/scala/fi/oph/koski/validation/PerusopetuksenOpiskeluoikeudenValidation.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationPerusopetusSpec.scala
validaation_muutoshistoria.md

TOR-2087: Lisää validaatio ET- ja KT-oppiaineduplikaateille

---

pom.xml

Päivitä scala-schema ja json4s uudempiin

---

src/main/scala/fi/oph/koski/valpas/kuntailmoitus/ValpasKuntailmoitusService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
src/main/scala/fi/oph/koski/valpas/oppija/OppijaHakutilanteillaLaajatTiedot.scala
src/main/scala/fi/oph/koski/valpas/oppija/ValpasAccessResolver.scala
src/main/scala/fi/oph/koski/valpas/oppija/ValpasOppijaLaajatTiedotService.scala
valpas-web/package-lock.json
valpas-web/src/views/kunnalleilmoitetut/KunnalleIlmoitetutTable.tsx
valpas-web/test/integrationtests/kuntailmoitus.test.ts
valpas-web/test/integrationtests/suorittaminen.test.ts

- browserlist-päivitys
- Näytä kunnalle ilmoitetut -listassa myös vanhat ilmoitukset

TOR-1947: Valpas: kunnalle ilmotetut- listaukselle jätetään tehdyt ilmoitukset

---

src/main/resources/reference.conf
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepositoryActions.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala

TOR-xxxx: Mahdollista validaatioiden skippaus väliaikaisesti

---

valpas-web/package-lock.json

TOR-xxxx: Päivitä Valppaan chromedriver

---

src/main/resources/localization/koski-default-texts.json
web/app/components-v2/opiskeluoikeus/OpiskeluoikeudenTila.tsx
web/app/components-v2/opiskeluoikeus/OsasuoritusProperty.tsx
web/app/components-v2/opiskeluoikeus/PerusteField.tsx
web/app/components-v2/opiskeluoikeus/UusiOpiskeluoikeudenTilaModal.tsx
web/app/util/koskiApi.ts

Lisää puuttuvia käännöksiä
Lisää perusteiden linkitys

TOR-2115 VST käännöksiä

---

web/app/components-v2/opiskeluoikeus/OpiskeluoikeudenTila.tsx
web/app/util/koskiApi.ts

- Poista ylimääräinen käännös
- Lisää kieli perustekutsuun

TOR-2115-vst-ruotsinnoksia

---

pom.xml

TOR-xxxx: Korjaa build-failure, jos sama commit jo GH-packagesissa

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/documentation/ExamplesIB.scala
src/main/scala/fi/oph/koski/schema/IB.scala
src/main/scala/fi/oph/koski/schema/InternationalSchool.scala
src/test/resources/backwardcompatibility/ib-finalgrades_2024-02-27.json
src/test/resources/backwardcompatibility/ib-predictedgrades_2024-02-27.json
src/test/resources/backwardcompatibility/internationalschool_2024-02-27.json
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationIBSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md
web/app/types/fi/oph/koski/schema/IBCASOppiaineenArviointi.ts
web/app/types/fi/oph/koski/schema/IBCoreRequirementsArviointi.ts
web/app/types/fi/oph/koski/schema/InternationalSchoolCoreRequirementsArviointi.ts
web/test/spec/ibSpec.js
web/test/spec/omatTiedotLukioSpec.js

TOR-2147: Deprekoi predicted-arvioinnit IB:n ja IS:n tietomallihaaroista

---

src/main/scala/fi/oph/koski/servlet/SuoritusjakoApiServlet.scala
src/main/scala/fi/oph/koski/suoritusjako/OppijaJakolinkilla.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoService.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoServlet.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoServletV3.scala
src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotSchema.scala
src/main/scala/fi/oph/koski/suoritusjako/common/Jakolinkki.scala
src/main/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotSchema.scala
src/test/scala/fi/oph/koski/api/misc/SuoritusjakoAPISpec.scala
src/test/scala/fi/oph/koski/api/misc/SuoritusjakoTestMethods.scala
web/app/types/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotOppija.ts
web/app/types/fi/oph/koski/suoritusjako/common/Jakolinkki.ts
web/app/types/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotOppija.ts

TOR-2150: Lisää jakolinkin voimassaoloaika palautettaviin tietoihin

---

web/package-lock.json
web/package.json
web/test/runner.html
web/test/spec/RaportitSpec.js
web/test/spec/ammatillinenSpec.js
web/test/spec/ebTutkintoSpec.js
web/test/spec/lukio2019Spec.js
web/test/spec/perusopetusSpec.js
web/webpack.config.js

TOR-xxxx: Ota moment käyttöön karkauspäiväongelmien korjaamiseksi

---

src/main/scala/fi/oph/koski/fixture/DatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/fixture/FixtureServlet.scala
src/main/scala/fi/oph/koski/fixture/Fixtures.scala
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusChangeMigrator.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresKoskiOpiskeluoikeusRepositoryActions.scala
src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepositoryActions.scala
src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala
src/main/scala/fi/oph/koski/schema/Opiskeluoikeus.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoRepository.scala
src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoRepositoryV2.scala
src/main/scala/fi/oph/koski/suostumus/SuostumuksenPeruutusService.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasOpiskeluoikeusDatabaseFixtureCreator.scala
src/test/scala/fi/oph/koski/api/misc/KäyttöoikeusryhmätSpec.scala
src/test/scala/fi/oph/koski/api/misc/OpiskeluoikeusTestMethods.scala
src/test/scala/fi/oph/koski/api/misc/OppijaQuerySpec.scala
src/test/scala/fi/oph/koski/api/misc/PutOpiskeluOikeusTestMethods.scala
src/test/scala/fi/oph/koski/api/misc/SearchTestMethods.scala
src/test/scala/fi/oph/koski/api/oppijaupdate/OppijaUpdateSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationTaiteenPerusopetusSpec.scala
src/test/scala/fi/oph/koski/api/suostumus/SuostumuksenPeruutusSpec.scala
src/test/scala/fi/oph/koski/http/HttpSpecification.scala
src/test/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md

TOR-2131: Mitätöintilogiikan parannuksia

---

.github/skip_tiedonsiirtoprotokollan_muutoshistoria.md
src/main/resources/documentation/kyselyt.md
src/main/scala/ScalatraBootstrap.scala
src/main/scala/fi/oph/koski/documentation/DocumentationApiServlet.scala
src/main/scala/fi/oph/koski/documentation/DocumentationServlet.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryDocumentation.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryParameters.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryRepository.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryResultWriter.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryResultsRepository.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryServlet.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryUtils.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudetCsv.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudetJson.scala
src/main/scala/fi/oph/koski/queuedqueries/paallekkaisetopiskeluoikeudet/QueryPaallekkaisetOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/schema/annotation/Annotations.scala
src/main/scala/fi/oph/koski/util/ChainingOps.scala
src/main/scala/fi/oph/koski/util/TryWithLogging.scala
src/test/scala/fi/oph/koski/queuedqueries/QuerySpec.scala
web/app/dokumentaatio/Dokumentaatio.jsx
web/app/style/documentation.less
web/app/virkailija/virkailijaRouter.jsx

itsensä dokumentoiviin luokkiin,

TOR-2141: Kysely-apin dokumentaatio ja refaktorointia

---

web/app/components-v2/containers/EditorContainer.tsx
web/app/components-v2/containers/KeyValueTable.tsx
web/app/components-v2/controls/FlatButton.tsx
web/app/components-v2/controls/RaisedButton.tsx
web/app/components-v2/controls/RemoveArrayItemField.tsx
web/app/components-v2/messages/Snackbar.tsx
web/app/components-v2/opiskeluoikeus/EditBar.tsx
web/app/components-v2/opiskeluoikeus/OpiskeluoikeudenSuostumuksenPeruminen.tsx
web/app/components-v2/opiskeluoikeus/OpiskeluoikeudenTila.tsx
web/app/components-v2/opiskeluoikeus/OpiskeluoikeusEditToolbar.tsx
web/app/components-v2/opiskeluoikeus/OrganisaatiohistoriaView.tsx
web/app/components-v2/opiskeluoikeus/PaikallinenOsasuoritusSelect.tsx
web/app/components-v2/opiskeluoikeus/SuorituksenVahvistus.tsx
web/app/components-v2/opiskeluoikeus/SuorituksenVahvistusModal.tsx
web/app/components-v2/texts/Trans.tsx
web/app/components-v2/yotutkinto/YoTodistus.tsx
web/app/i18n/i18n.ts
web/app/taiteenperusopetus/TaiteenPerusopetuksenTiedot.tsx
web/app/taiteenperusopetus/UusiTaiteenPerusopetuksenPäätasonSuoritus.tsx
web/app/vst/common/VSTLaajuudetYhteensa.tsx
web/app/vst/common/suoritusFields.tsx
web/app/vst/osaamismerkki/VSTOsaamismerkkiEditor.tsx

TOR-2158: Uuden kälin lokalisointi-refaktorointeja

---

pom.xml
scripts/local-reset-raportointikanta.sh
src/main/resources/documentation/kyselyt.md
src/main/resources/reference.conf
src/main/scala/fi/oph/koski/cache/RefreshingCache.scala
src/main/scala/fi/oph/koski/config/ECSMetadataClient.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryCleanupScheduler.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryDocumentation.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryScheduler.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryService.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryServlet.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryUtils.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudetCsv.scala
src/main/scala/fi/oph/koski/queuedqueries/paallekkaisetopiskeluoikeudet/QueryPaallekkaisetOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/raportit/RaportitService.scala
src/main/scala/fi/oph/koski/util/Retry.scala

- **Palauta mitätöidyt opiskeluoikeudet kyselylle**
- **Poista concurrency-konfiguraatio;**
- **Typokorjaus**
- **Tarkenna organisaatioOidin dokumentointia**
- **Tarkenna dokumentaatiota tiloihin liittyen.**
- **Palauta kyselyrajapinnan aikaleimoissa aikavyöhyke**

TOR-2141: Kyselyrajapinnan korjauksia

---

.github/workflows/all_tests.yml
src/main/resources/documentation/kyselyt.md
src/main/scala/fi/oph/koski/queuedqueries/QueryCleanupScheduler.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryDocumentation.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryRepository.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryResultsRepository.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryScheduler.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryService.scala
src/main/scala/fi/oph/koski/queuedqueries/QueryServlet.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/queuedqueries/paallekkaisetopiskeluoikeudet/QueryPaallekkaisetOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/schedule/Scheduler.scala
src/test/scala/fi/oph/koski/queuedqueries/QuerySpec.scala

- **Palauta päällekkäisten opiskeluoikeuksien raportille raportointikannan päivitysaika**
- **Lisää vastausten kentät dokumentaatioon**
- **Korjaa rikkinäinen sql**
- **Kytke download-testit takaisin päälle**
- **Siirrä kyselyrajapinnan testit lyhyempään suiteen**
- **Lisää virheenkäsittelyä**
- **Lisää mitätöidyt opiskeluoikeudet aina kyselyihin**
- **Poista kuollutta koodia**
- **Lisää kyselyrajapinnan testejä**

TOR-2141: Lisää testejä kyselyrajapinnalle

---

documentation/kyselyrajapinta.md
src/main/scala/fi/oph/koski/queuedqueries/QueryResultWriter.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudetCsv.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudetJson.scala

- **Käytä jsonin serialisointiin käyttäjäprofiilia**
- **Tee mitätöityjen opiskeuoikeuksien hausta eksplisiittinen**

TOR-2141: Viimeistelyt ja dokumentaatio kehittäjille

---

opensearch/Dockerfile
opensearch/opensearch-docker.yml

TOR-2110: Downgrade lokaali OpenSearch tuotannossa käytettävään versioon

---

web/app/components-v2/opiskeluoikeus/OpiskeluoikeusEditToolbar.tsx
web/app/components-v2/opiskeluoikeus/OpiskeluoikeusTitle.tsx
web/app/components-v2/opiskeluoikeus/VersiohistoriaButton.tsx
web/app/vst/osaamismerkki/OsaamismerkkiTitle.tsx

- Erota VersiohistoriaButton omaan tiedostoon
- Siisti mitätöintinappi ja lisää versiohistoriastapoistumisnappi

TOR-2049: Muokkaa- ja Poistu versiohistoriasta -napit kuntoon

---

src/main/scala/fi/oph/koski/queuedqueries/QueryService.scala
src/main/scala/fi/oph/koski/queuedqueries/organisaationopiskeluoikeudet/QueryOrganisaationOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/queuedqueries/paallekkaisetopiskeluoikeudet/QueryPaallekkaisetOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/util/Timeout.scala
src/test/scala/fi/oph/koski/queuedqueries/QuerySpec.scala

- **Älä merkitse timeoutia siivouksen yhteydessä;**
- **Lisää säikeen tuhoava timeout kyselyn ympärille**

TOR-2141: Viimeistelyjä osa 2

---

src/main/resources/documentation/kyselyt.md
src/main/scala/fi/oph/koski/queuedqueries/QueryDocumentation.scala

- **Lisää headerit esimerkkeihin mukaan**
- **Korjaa listatyypin renderöinti dokumentaatioon**

TOR-2141: Dokumentaation parannuksia

---

src/main/scala/fi/oph/koski/kela/KelaAmmatillinenSchema.scala
src/main/scala/fi/oph/koski/kela/KelaTutkintokoulutukseenValmentavanKoulutuksenSchema.scala
src/test/scala/fi/oph/koski/kela/KelaSpec.scala

TOR-xxxx: Palauta tarvittava tietokenttä myös Kelan laajoilla oikeuksilla

---

web/app/vst/common/VSTLisatiedot.tsx

Lisää myös puuttuva TestLayerin key

TOR-2153: Korjaa VSTLisätiedot komponentin päivämääräformaatti

---

src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
src/main/scala/fi/oph/koski/tiedonsiirto/ExamplesTiedonsiirto.scala
src/main/scala/fi/oph/koski/validation/DuplikaattiValidation.scala
src/main/scala/fi/oph/koski/validation/KoskiGlobaaliValidator.scala
src/main/scala/fi/oph/koski/validation/PerusopetuksenOpiskeluoikeudenValidation.scala
src/main/scala/fi/oph/koski/validation/VapaaSivistystyöValidation.scala
src/test/resources/backwardcompatibility/tiedonsiirto-onnistunut_2024-04-16.json
src/test/resources/backwardcompatibility/tiedonsiirto-vainsyntymaaika_2024-04-16.json
src/test/scala/fi/oph/koski/api/misc/DatabaseUpdateSpec.scala
src/test/scala/fi/oph/koski/api/misc/KäyttöoikeusryhmätSpec.scala
src/test/scala/fi/oph/koski/api/misc/SisaltyvaOpiskeluoikeusSpec.scala
src/test/scala/fi/oph/koski/api/misc/TiedonsiirtoSpec.scala
src/test/scala/fi/oph/koski/api/oppijaupdate/OppijaUpdateSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationAikuistenPerusopetusSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationAmmatillinenSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationAmmatillisenTutkinnonOsittainenSuoritusSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationEsiopetusSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationPerusopetukseenValmistavaSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationSpec.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationTutkintokoulutukseenValmentavaKoulutusSpec.scala
src/test/scala/fi/oph/koski/oppivelvollisuustieto/OppivelvollisuustietoSpec.scala
src/test/scala/fi/oph/koski/raportit/AmmatillinenTutkintoRaporttiSpec.scala
src/test/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotServiceSpec.scala
src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala
validaation_muutoshistoria.md
web/test/e2e/setup/users.json
web/test/spec/tiedonsiirrotSpec.js
web/test/spec/useampiSamanOppilaitoksenVoimassaOlevaOpintoOikeusSpec.js

Lisää tarkemmat duplikaattivalidaatiot eskarille, valmistavalle, aikuisten perusopetukselle ja ammatilliselle prosessoinnin alkuvaiheessa ajettavan globaalin validaattorin yhteyteen.

TOR-2128 Duplikaattivalidaatiot

---

web/app/kela/KeyValueTable.jsx

Korjaa osa-aikaisuusprosentin näyttäminen Kelan kälissä: labelin oikeinkirjoitus ja prosenttimerkin lisääminen

TOR-2179 Lisää komponentti osa-aikaisuusjaksolle

---

src/main/scala/fi/oph/koski/validation/IBValidation.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationIBSpec.scala

Huomioidaan että IB-tutkinnolla voi olla useampi päätason suoritus

TOR-2176 Korjaus IB-validaatioon

---

web/app/kela/KeyValueTable.jsx

- **Lisää arviointipäivät r_osasuoritus-tauluun**
- **Korjaus: className ei class**

Korjaus: class -> className

---

.github/workflows/all_tests.yml
Makefile
src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/vkt/VKTDIASchema.scala
src/main/scala/fi/oph/koski/vkt/VKTEBTutkintoSchema.scala
src/main/scala/fi/oph/koski/vkt/VKTKorkeakouluSchema.scala
src/main/scala/fi/oph/koski/vkt/VKTSchema.scala
src/main/scala/fi/oph/koski/vkt/VKTService.scala
src/main/scala/fi/oph/koski/vkt/VKTServlet.scala
src/main/scala/fi/oph/koski/vkt/VKTYlioppilastutkintoSchema.scala
src/test/scala/fi/oph/koski/vkt/VKTServiceSpec.scala

Lisätään uusi rajapinta jolla VKT voi hakea tiedot yo- ja korkeakoulututkinnoista

TOR-2180-vkt-rajapinta

---

pom.xml
smoketests/package-lock.json
smoketests/package.json

TOR-xxxx: Snykin triggeröimiä päivityksiä koostettuna

---

src/main/scala/fi/oph/koski/massaluovutus/MassaluovutusService.scala
src/main/scala/fi/oph/koski/massaluovutus/organisaationopiskeluoikeudet/MassaluovutusQueryOrganisaationOpiskeluoikeudet.scala
src/test/scala/fi/oph/koski/massaluovutus/MassaluovutusSpec.scala

- **Odota jokaisen testin jälkeen ettei skedulerilla ole enää jonoa ajossa tai ajettavaksi**
- **Lisää puuttuvia parametreja audit-logilta**

TOR-2126: Korjauksia massaluovutusrajapinnan testeihin ja logitukseen

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenOppimääräArvioinnit.scala
src/test/scala/fi/oph/koski/raportit/AikuistenPerusopetuksenOppimääränArvioinnitSpec.scala

Lisää mukaan tieto onko ensimmäinen arviointi
Käytä select distinct

TOR-2181 Korjaus AIPO arvioinnit raporttiin

---

src/main/scala/fi/oph/koski/hakemuspalvelu/HakemuspalveluAikuistenPerusopetuksenOppimääräSchema.scala
src/main/scala/fi/oph/koski/hakemuspalvelu/HakemuspalveluAmmatillinenTutkintoSchema.scala
src/main/scala/fi/oph/koski/hakemuspalvelu/HakemuspalveluLukionOppimääräSchema.scala
src/main/scala/fi/oph/koski/hakemuspalvelu/HakemuspalveluPerusopetuksenOppimääräSchema.scala
src/main/scala/fi/oph/koski/hakemuspalvelu/HakemuspalveluSchema.scala
src/main/scala/fi/oph/koski/hakemuspalvelu/HakemuspalveluService.scala
src/test/scala/fi/oph/koski/hakemuspalvelu/HakemuspalveluServiceSpec.scala

- **Lisää perusopetus, aipe, lukio ja ammatillinen**
- **Lisää testit**

TOR-2198 Hakemuspalvelun API:n laajennos

---

src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslOpiskeluoikeus.scala

- **Korjaa opiskeluoikeusJaksot -> opiskeluoikeusjaksot**

TOR-2203 Täydennä HSL tietomallia

---

src/test/scala/fi/oph/koski/luovutuspalvelu/HslSpec.scala

TOR-2203 Täydennä HSL tietomalli

---

src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslAikuistenPerusopetuksenOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslAmmatillinenOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslDiaOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslIBOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslInternationalSchoolOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslKorkeakoulunOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslLukionOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslLukioonValmistavanKoulutuksenOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslPerusopetukseenValmistavanOpetuksenOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslPerusopetuksenLisaopetuksenOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslPerusopetuksenOpiskeluoikeus.scala
src/main/scala/fi/oph/koski/luovutuspalvelu/opiskeluoikeus/HslYlioppilastutkinnonOpiskeluoikeus.scala

Lisää karsittu versio organisaatiohistoriasta

TOR-2203 Täydennä HSL api part X

---

src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala

TOR-2031: Korjaa tuotanto (maksuttomuuspakotuksen pitäisi olla edelleen disabloitu)

---

src/main/scala/fi/oph/koski/luovutuspalvelu/SoapServlet.scala

Muuta HSL lokitusta niin että virheiden sijaan lokitetaan info-tasolla odotetut tilanteet

TOR-2203 Tarkenna HSL lokitusta

---

src/main/scala/fi/oph/koski/oppija/KoskiOppijaFacade.scala

TOR-2135 Aikuisten perusopetus: aipe kurssit käliin

---

omadata-oauth2-sample/server/src/index.ts
src/main/scala/ScalatraBootstrap.scala

Ks. commit-viestit
Muutoksia myös koski-luovutuspalvelu ja koski-aws-infra
https://github.com/Opetushallitus/koski-luovutuspalvelu/pull/50
https://github.com/Opetushallitus/koski-aws-infra/pull/272

TOR-2210 OmaData OAuth2 vaihe 3

---

src/main/scala/ScalatraBootstrap.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2Support.scala

[WIP] TOR-2210 OmaData OAuth2 vaihe 5

---

documentation/oauth2toteutus.md
src/main/scala/fi/oph/koski/frontendvalvonta/FrontendValvontaHeaders.scala
src/main/scala/fi/oph/koski/frontendvalvonta/FrontendValvottuServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2LogoutPostResponseServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2Support.scala

TOR-2210: OmaDataOauth2: korjaa POST:in estävä form-action CSP header

---

src/main/resources/reference.conf
src/main/scala/fi/oph/koski/frontendvalvonta/FrontendValvontaHeaders.scala
src/main/scala/fi/oph/koski/frontendvalvonta/FrontendValvottuServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2Config.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2LogoutPostResponseServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2Support.scala

TOR-2210 OmaDataOAuth2 : Mahdollista form-action CSP-instruktion skippaus

---

src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationAmmatillinenSpec.scala
validaation_muutoshistoria.md

- **Tee alivalidaatioista privaatteja**
- **Älä salli arviointia "Hylätty" ammatillisen tutkinnon osasuorituksiin**

TOR-986: Älä salli arviointia "Hylätty" ammatillisen tutkinnon osasuorituksiin

---

src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2LogoutPostResponseServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2ResourceOwnerServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2Support.scala
src/test/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2FrontendSpec.scala

TOR-2210: OmaDataOAuth2: Palaa resource owner frontendiin epätavallisissa virhetilanteissa;

---

src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2AuthorizationServerServlet.scala
src/test/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2BackendSpec.scala

TOR-2210 OmaData OAuth2: client_id pakolliseksi access token requestissä

---

.github/workflows/all_tests.yml
documentation/oauth2toteutus.md
src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2AuthorizationServerServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2ResourceOwnerReactServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2Support.scala
src/test/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2BackendSpec.scala
src/test/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2FrontendSpec.scala
src/test/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2TestBase.scala
src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala
web/app/i18n/TextTemplate.jsx
web/app/omadata/OmaDataOAuth2AnnaHyvaksynta.jsx
web/app/omadata/OmaDataOAuth2HyvaksyntaLanding.jsx
web/app/omadata/OmaDataOAuth2UusiHyvaksynta.jsx

TOR-2210: OmaData OAuth2 Suostumussivun tekstien viimeistelyä

---

.github/actions/omadataoauth2_e2e_test/action.yml
.github/actions/omadataoauth2_setup_playwright/action.yml
.github/workflows/all_tests.yml
.github/workflows/omadataoauth2sample_test.yml
.github/workflows/run_koski_tests_continuously_on_master.yml
.github/workflows/run_koski_tests_on_branches.yml
.github/workflows/test_build_deploy_master.yml
Makefile
README.md
documentation/oauth2toteutus.md
omadata-oauth2-sample/client/.gitignore
omadata-oauth2-sample/client/package-lock.json
omadata-oauth2-sample/client/package.json
omadata-oauth2-sample/client/playwright.config.ts
omadata-oauth2-sample/client/public/index.html
omadata-oauth2-sample/client/src/App.tsx
omadata-oauth2-sample/client/test/e2e/front-page.spec.ts
omadata-oauth2-sample/server/src/index.ts
pom.xml
scripts/omadata-oauth2-e2e-test.sh
src/test/scala/fi/oph/koski/meta/GithubActionsSpec.scala
src/test/scala/fi/oph/koski/omadataoauth2/e2e/OmaDataOAuth2E2ESpec.scala
src/test/scala/fi/oph/koski/omadataoauth2/unit/OmaDataOAuth2BackendSpec.scala
src/test/scala/fi/oph/koski/omadataoauth2/unit/OmaDataOAuth2ClientDetailsSpec.scala
src/test/scala/fi/oph/koski/omadataoauth2/unit/OmaDataOAuth2FrontendSpec.scala
src/test/scala/fi/oph/koski/omadataoauth2/unit/OmaDataOAuth2TestBase.scala

TOR-2210 Runko playwright-testeille

---

.github/actions/omadataoauth2_e2e_test/action.yml
.github/actions/omadataoauth2_setup_playwright/action.yml
.github/workflows/omadataoauth2sample_test.yml
omadata-oauth2-sample/client/package.json
omadata-oauth2-sample/client/playwright.config.ts
omadata-oauth2-sample/client/test/e2e/luovutuspalvelu-healthcheck-page.spec.ts
omadata-oauth2-sample/server/src/index.ts
pom.xml
src/test/scala/fi/oph/koski/e2e/KoskiFrontSpec.scala
src/test/scala/fi/oph/koski/omadataoauth2/e2e/OmaDataOAuth2E2ESpec.scala

TOR-2210 OmaData OAuth2 E2E-testeihin luovutuspalvelu mukaan

---

src/main/resources/omadataoauth2/dummydata.json
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2ResourceServerServlet.scala

TOR-2210: OmaData OAuth2: Palauta oikeampaa dummy-sisältöä OAuth2 resource serveriltä

---

pom.xml
src/main/scala/fi/oph/koski/cache/ExpiringCache.scala

- **Päivitä guava**
- **Ota debug-logia ExpiringCachesta jumitusten selvittelemiseksi**

TOR-XXX: KOSKI-konttien jumittelun selvittely

---

documentation/oauth2toteutus.md
omadata-oauth2-sample/README.md
omadata-oauth2-sample/client/package.json
omadata-oauth2-sample/client/playwright.config.ts
omadata-oauth2-sample/client/src/App.tsx
omadata-oauth2-sample/client/test/e2e/front-page.spec.ts
omadata-oauth2-sample/client/test/e2e/openid-client-test.spec.ts
omadata-oauth2-sample/server/package-lock.json
omadata-oauth2-sample/server/package.json
omadata-oauth2-sample/server/src/apiroutes/front-page-dummy.ts
omadata-oauth2-sample/server/src/apiroutes/healthcheck.ts
omadata-oauth2-sample/server/src/apiroutes/openid-api-test.ts
omadata-oauth2-sample/server/src/config/client-cert-config.ts
omadata-oauth2-sample/server/src/config/koski-backend-config.ts
omadata-oauth2-sample/server/src/config/oauth-client-config.ts
omadata-oauth2-sample/server/src/index.ts
omadata-oauth2-sample/server/src/oauth2-client/oauth2-client.ts
omadata-oauth2-sample/server/src/util/memoize.ts
omadata-oauth2-sample/server/tsconfig.json
src/main/resources/reference.conf
src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2ResourceOwnerReactServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2Support.scala
web/app/omadata/OmaDataOAuth2HyvaksyntaLanding.jsx

TOR-2210 OmaData Oauth2: Käytä openid-client -kirjastoa sample-applikaatiossa

---

omadata-oauth2-sample/client/package-lock.json
omadata-oauth2-sample/client/package.json
omadata-oauth2-sample/client/src/App.css
omadata-oauth2-sample/client/src/App.tsx
omadata-oauth2-sample/client/src/setupProxy.js
omadata-oauth2-sample/client/test/e2e/front-page.spec.ts

TOR-2210: OmaData OAuth2 samplen parannuksia

---

.github/skip_tiedonsiirtoprotokollan_muutoshistoria.md
src/main/scala/fi/oph/koski/editor/EditorModelBuilder.scala
src/main/scala/fi/oph/koski/editor/EditorModelSerializer.scala
src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/main/scala/fi/oph/koski/schema/annotation/Hidden.scala
web/app/editor/PropertiesEditor.jsx
web/test/spec/ammatillinenSpec.js

- **Uusi tietomallin annotaatio: @HiddenWhen**
- **Piilota reformin mukaiselta amiksen opiskeluoikeudelta vanhanmallisten näyttötutkintojen tietoja**

TOR-2047: Vanhanmallisten näyttötutkintojen näytön tietojen piilotus reformin mukaisista koulutuksista

---

src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala

- **Testi oppijalle, jolla on vain mitätöityjä opiskeluoikeuksia**
- **Lisää r_henkilo-tauluun myös oppijat, joilla ei ole kuin mitätöityjä opiskeluoikeuksia**

TOR-1577: Lisää raportointikannan r_henkilo-tauluun oppijat, joilla on pelkkiä mitätöityjä opiskeluoikeuksia

---

src/main/scala/fi/oph/koski/koskiuser/Kayttooikeus.scala
src/main/scala/fi/oph/koski/koskiuser/Palvelurooli.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2DiscoveryServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2ResourceOwnerReactServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2ResourceOwnerServlet.scala
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2Support.scala
src/test/scala/fi/oph/koski/omadataoauth2/unit/OmaDataOAuth2FrontendSpec.scala

TOR-2210: OmaData OAuth2: Lisää scope-validointeja

---

src/main/resources/reference.conf
src/main/scala/fi/oph/koski/koskiuser/UserServlet.scala

This reverts commit 2f5dfb5ec63973ac88fb32723415894a1b234d66.
Merge aikaisintaan 27.11.2024

TOR-1438: Poista feature flag lähdejärjestelmäkytkennältä

---

src/main/resources/documentation/massaluovutus-oph.md
src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/SuoritusrekisteriMuuttuneetJalkeenQuery.scala
src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/SuoritusrekisteriOppijaOidsQuery.scala
src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/SuoritusrekisteriQuery.scala
src/test/scala/fi/oph/koski/massaluovutus/MassaluovutusSpec.scala

- **Uudelleennimeä olemassaoleva sure-massaluovutus**
- **Siirrä sure-kyselyiden jaettava koodi traittiin**
- **Lisää uusi kysely oppija-oidien perusteella**

TOR-2261: Sure-massaluovutuksen kysely oppija-oidien perusteella

---

src/main/scala/fi/oph/koski/henkilo/OppijanumeroRekisteriClient.scala
src/main/scala/fi/oph/koski/http/Http.scala

Säädetty idleTimeout-arvoa, jotta se seuraa http4s-kirjaston suosituksia

Korjaa OppijanumeroRekisteriClientRetryStrategy

---

src/main/scala/fi/oph/koski/cas/CasClient.scala
src/main/scala/fi/oph/koski/http/Http.scala
src/main/scala/fi/oph/koski/sso/CasService.scala

TOR-xxxx: Paranna oppija-cas:in service ticket -validoinnin virhekäsittelyä

---

src/main/scala/fi/oph/koski/cas/CasClient.scala
src/main/scala/fi/oph/koski/sso/CasService.scala

TOR-2210: Tue digilompakkotunnistusta testiympäristöissä

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationAmmatillinenSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md
validaation_muutoshistoria.md
web/app/types/fi/oph/koski/schema/AmmatillisenOpiskeluoikeudenLisatiedot.ts

- **Lisää amiksen lisätietoihin kenttä siirtynytTutkinnonUusiinPerusteisiin**
- **Validaatio siirtynytTutkinnonUusiinPerusteisiin -siirrolle**

TOR-2240: Siirtynyt tutkinnon uusiin perusteisiin -kenttä

---

pom.xml
src/main/scala/fi/oph/koski/config/Environment.scala
src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogDynamoDB.scala
src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogMockData.scala
src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogService.scala
src/main/scala/fi/oph/koski/ytr/YoTodistusService.scala

Päivitetään Joulukuussa 2025 vanhentuvat AWS SDK:t v2-versioon.
Päivitys vaatii muutoksia Kosken sovelluskoodiin.

AWS SDK v2

---

src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogMockData.scala
src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogService.scala

TOR-xxxx: Korjaa kuka katsoi tietojani -näkymä

---

src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogService.scala

TOR-xxxx: lisäfiksi kuka katsoi tietojani -näkymään

---

src/main/scala/fi/oph/koski/log/MaskedSlf4jRequestLogWriter.scala
src/main/scala/fi/oph/koski/servlet/SuoritusjakoApiServlet.scala
src/test/scala/fi/oph/koski/api/misc/SuoritusjakoAPISpec.scala

- **Lisää puuttuva maskaus**
- **Lisää oppijan oid auditlogin targetiin**

Fix: henkilön oid suoritusjaon auditlogiin

---

src/main/resources/localization/koski-default-texts.json
web/app/ib/state/preIBOppiaine.ts

- **Näytä kielivalikko valittaessa A-kieli**
- **Lisää puuttuvia käännöksiä**

TOR-2262: Korjaussarja

---

web/app/components-v2/containers/KeyValueTable.less
web/app/components-v2/opiskeluoikeus/ArvosanaField.tsx

- **Piilota KeyValueTablesta vain ne rivit, joiden välitön arvo on tyhjä**
- **Näytä viiva puuttuvan arvosanan kohdalla**

TOR-2262: Korjaa näkymätön theory of knowledge

---

web/app/ib/IBPaatasonSuoritusTiedot.tsx

- **Näytä theory of knowledge -kurssin lisäysnappi, jos kursseja ei entuudestaan ole**
- **Korjaa arvosanan asettaminen**

TOR-2262: Korjaa theory of knowledgen editointibugit

---

src/main/resources/localization/koski-default-texts.json
src/main/resources/mockdata/koodisto/koodistot/virtapatevyys.json
src/main/resources/mockdata/koodisto/koodit/virtapatevyys.json
src/main/resources/mockdata/virta/opintotiedot/100869-192W.xml
src/main/scala/fi/oph/koski/koodisto/Koodistot.scala
src/main/scala/fi/oph/koski/schema/Korkeakoulu.scala
src/main/scala/fi/oph/koski/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakouluSchema.scala
src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala
src/test/scala/fi/oph/koski/virta/VirtaXMLConverterSpec.scala
web/app/types/fi/oph/koski/schema/KorkeakoulunOpiskeluoikeudenLisatiedot.ts
web/app/types/fi/oph/koski/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakoulunLisatiedot.ts

- **Lisää pätevyyskoodisto**
- **Parsi Patevyys-tieto**

TOR-2252 Opettajapätevyystieto Virrasta

---

src/main/resources/mockdata/koodisto/koodit/omadataoauth2client.json
src/main/resources/reference.conf
src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
src/main/scala/fi/oph/koski/koskiuser/Session.scala
src/main/scala/fi/oph/koski/userdirectory/DirectoryClient.scala
src/test/scala/fi/oph/koski/omadataoauth2/unit/OmaDataOAuth2BackendSpec.scala

TOR-2285: Mahdollista Opetushallitukselle käyttöoikeus OAuth2-oikeuksissa

---

src/main/resources/documentation/omadata_oauth2.md
src/main/resources/reference.conf
src/main/scala/fi/oph/koski/omadataoauth2/OmaDataOAuth2ResourceOwnerReactServlet.scala
src/main/scala/fi/oph/koski/sso/SSOSupport.scala
src/test/scala/fi/oph/koski/mydata/MyDataSupportTest.scala
src/test/scala/fi/oph/koski/omadataoauth2/unit/OmaDataOAuth2FrontendSpec.scala
web/app/omadata/OmaDataOAuth2HyvaksyntaLanding.jsx

TOR-2285: Mahdollista käyttöliittymäkielen asetus OmaData OAuth2-rajapinnassa

---

src/main/scala/fi/oph/koski/koskiuser/AuthenticationSupport.scala
src/main/scala/fi/oph/koski/koskiuser/UserLanguage.scala
src/main/scala/fi/oph/koski/sso/CasServlet.scala
src/main/scala/fi/oph/koski/valpas/sso/ValpasOppijaCasServlet.scala

TOR-2285 jatko: Jos ONR:ssä ei ole tai sieltä ei saada asiointikieltä, defaulttaa cookieen eikä fi:hin

---

omadata-oauth2-sample/server/src/config/client-cert-config.ts
omadata-oauth2-sample/server/src/util/memoize.ts

TOR-2285: Älä cachea virheellisten pyyntöjen tuloksia OAuth2-samplessa

---

web/app/omadata/OmaDataOAuth2AnnaHyvaksynta.jsx
web/app/style/omadataoauth2.less

TOR-2285 OAuth2-suostumusdialogin käyttöliittymäparannuksia

---

src/main/resources/mockdata/virta/opintotiedot/100869-192W.xml
src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala

Opiskeluoikeuteen liittyvät pätevyydet luettiin epähuomiossa kaikilta suorituksilta eikä vain ko. opiskeluoikeuteen liittyviltä

FIX:Opettajapätevyydet

---

.github/actions/omadataoauth2_e2e_test/action.yml
.github/workflows/all_tests.yml
.github/workflows/omadataoauth2sample_test.yml
.github/workflows/run_koski_tests_on_branches.yml
omadata-oauth2-sample/client/package.json
omadata-oauth2-sample/client/playwright.config.ts

Katso myös https://github.com/Opetushallitus/koski-luovutuspalvelu/pull/68

TOR-2313 OmaDataOAuth2 E2E testit käyttämään valmista luovutuspalvelun imagea ECR:stä

---

src/main/scala/fi/oph/koski/schema/Henkilo.scala
src/main/scala/fi/oph/koski/schema/Organisaatio.scala
src/test/scala/fi/oph/koski/schema/KoskiOppijaExamplesValidationSpec.scala

TOR-2331: Salli uudet solmuluokat henkilöille ja organisaatioille

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotKorkeakouluSchema.scala
src/main/scala/fi/oph/koski/schema/Korkeakoulu.scala
src/main/scala/fi/oph/koski/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakouluSchema.scala
src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala
src/test/scala/fi/oph/koski/virta/VirtaXMLConverterSpec.scala
tiedonsiirtoprotokollan_muutoshistoria.md
web/app/types/fi/oph/koski/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotKorkeakoulunOpiskeluoikeudenLisatiedot.ts
web/app/types/fi/oph/koski/schema/KorkeakoulunOpiskeluoikeudenLisatiedot.ts
web/app/types/fi/oph/koski/suoritetuttutkinnot/SuoritetutTutkinnotKorkeakoulunLisatiedot.ts

TOR-2327 Täydennyksiä opettajan pätevyys -kenttien esittämiseen

---

src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloRepository.scala
src/main/scala/fi/oph/koski/oppivelvollisuustieto/Oppivelvollisuustiedot.scala
src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala
src/main/scala/fi/oph/koski/valpas/opiskeluoikeusfixture/ValpasMockOppijat.scala
src/main/scala/fi/oph/koski/valpas/oppija/ValpasOppijanumerorekisteriService.scala
src/main/scala/fi/oph/koski/valpas/oppijahaku/ValpasOppijaSearchService.scala
src/test/scala/fi/oph/koski/valpas/ValpasRootApiServletSpec.scala
src/test/scala/fi/oph/koski/valpas/ValpasYtlServletSpec.scala
src/test/scala/fi/oph/koski/valpas/oppija/ValpasOppijaLaajatTiedotServiceVainOnrSpec.scala

TOR-2297 Korjaa detaljisivu ja maksuttomuushaku huomioimaan kuntahistoria;

---

.github/workflows/run_security_checks.yml
Makefile
omadata-oauth2-sample/java/owasp-dependency-check-suppressions-oauth2-sample.xml
omadata-oauth2-sample/java/pom.xml
omadata-oauth2-sample/server/package-lock.json
omadata-oauth2-sample/server/package.json
owasp-dependency-check-suppressions.xml
pom.xml
web/package-lock.json
web/package.json

TOR-2312 Päivitä OWASP dependency checker yms.

---

Makefile
web/app/components-v2/forms/FormField.tsx
web/app/components-v2/opiskeluoikeus/ArvioitsijatField.tsx
web/app/components-v2/opiskeluoikeus/OrganisaatioHenkilotField.tsx
web/app/components-v2/opiskeluoikeus/UusiOpiskeluoikeudenTilaModal.tsx
web/app/date/date.ts
web/app/kielitutkinto/yleinenKielitutkinto.ts
web/app/omadata/OmaDataOAuth2AnnaHyvaksynta.jsx
web/app/omattiedot/suoritusjako/SuoritusjakoForm.jsx
web/app/perusopetus/PerusopetuksenOppiaineRowEditor.jsx
web/app/perusopetus/Perusopetus.js
web/app/style/documentation.less
web/app/suoritus/Suoritus.js
web/app/suoritus/SuoritustaulukkoCommon.tsx
web/app/util/hooks.js
web/app/util/laxModify.ts
web/app/util/useBooleanState.ts

TOR-xxxx: Korjaa prettierin ajo testeissä

---

web/app/SuoritetutTutkinnot.tsx

TOR-xxxx: Lisää puuttuvat lokalisoinnit suoritetut tutkinnot -näkymään

---

src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureAmmatillinenTutkinto.scala
src/main/scala/fi/oph/koski/massaluovutus/valintalaskenta/ValintalaskentaResponse.scala

- **Lisää yhteisen tutkinnon osat**
- **Lisää yhteisten tutkintojen osien osasuoritusten osasuoritukset**

TOR-2347: SURE-massaluovutusrajapinnan tietomallin korjauksia

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/documentation/ExamplesKielitutkinto.scala
src/main/scala/fi/oph/koski/typemodel/TsFileUpdater.scala
web/app/components-v2/containers/EditorContainer.tsx
web/app/components-v2/opiskeluoikeus/SuorituksenVahvistus.tsx
web/app/kielitutkinto/ValtiohallinnonKielitutkintoEditor.tsx
web/app/kielitutkinto/YleinenKielitutkintoEditor.tsx
web/app/types/fi/oph/koski/schema/ArviointiPaivamaaralla.ts
web/app/util/arvioinnit.ts

- **Piilota vahvistuspalkki kielitutkinnoilta**
- **Korjaa esimerkin tutkintopäivät**
- **Valtionhallinnon kielikokeen kälikorjauksia**

TOR-2329: Kielitutkintojen kälipäivityksiä

---

web/app/components-v2/opiskeluoikeus/OppiaineTable.tsx
web/app/ib/dialogs/UusiIBTutkintoOppiaineDialog.tsx

- **Kaiva oppiainetaulukkoon CAS-oppiaineen laajuus koulutusmoduulista**
- **Korjaa kälin kaatuminen, jos yritettiin lisätä uutta extended essay -oppiainetta**

TOR-2262: IB-kälin korjaussarja

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/schema/Esiopetus.scala
src/main/scala/fi/oph/koski/schema/NuortenPerusopetus.scala
src/main/scala/fi/oph/koski/schema/OpiskeluoikeudenLisatiedot.scala
src/main/scala/fi/oph/koski/schema/Tukijakso.scala
src/main/scala/fi/oph/koski/typemodel/TypescriptTypes.scala
tiedonsiirtoprotokollan_muutoshistoria.md
web/app/types/fi/oph/koski/schema/EsiopetuksenOpiskeluoikeudenLisatiedot.ts
web/app/types/fi/oph/koski/schema/PerusopetuksenOpiskeluoikeudenLisatiedot.ts
web/app/types/fi/oph/koski/schema/TyhjaTukijakso.ts

TOR-2311: Korjaa kentän rename-ongelma

---

src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala

TOR-xxxx: Poista cache healthcheckistä

---

web/app/uusiopiskeluoikeus/opiskeluoikeusCreator/perusopetus.ts

Aiemmin oppiaineen oppimäärän opiskeluoikeuden luonnissa oppiaine lisättiin virheellisesti valinnaisena.

TOR-2366 lisää oppiaine pakollisena, kun luodaan oppiaineen oppimäärän opiskeluoikeus

---

src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala

TOR-xxxx: Lisää suorituskykylokitus healthcheckin osavaiheille

---

src/main/scala/fi/oph/koski/cache/SeldomBlockingRefreshingCache.scala
src/main/scala/fi/oph/koski/config/KoskiApplication.scala
src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala
src/main/scala/fi/oph/koski/healthcheck/HealthMonitoring.scala
src/main/scala/fi/oph/koski/healthcheck/RadiatorService.scala
src/main/scala/fi/oph/koski/valpas/hakukooste/SureHakukoosteService.scala
src/main/scala/fi/oph/koski/virta/VirtaClient.scala
src/test/scala/fi/oph/koski/api/misc/HealthCheckSpec.scala
src/test/scala/fi/oph/koski/cache/CacheSpec.scala
src/test/scala/fi/oph/koski/cache/Counter.scala
src/test/scala/fi/oph/koski/cache/SeldomBlockingRefreshingCacheSpec.scala

TOR-xxxx: Nopea paluuarvo healthcheckeistä, jos kaikki on kunnossa

---

web/app/components-v2/containers/Modal.tsx
web/app/components-v2/controls/Checkbox.tsx
web/app/components-v2/controls/RadioButtons.less
web/app/components-v2/controls/RadioButtons.tsx
web/app/style/opiskeluoikeus.less
web/test/page/addOppijaPage.js

Jotkut checkboxit ja radio buttonit eivät olleet fokusoitavissa ja valittavissa näppäimistöllä. Tämä korjaa ainakin osan niistä.

TOR-2345 Saavetettavuuskorjauksia radio buttoneihin ja checkboxeihin

---

src/main/scala/fi/oph/koski/db/KoskiTables.scala
src/test/scala/fi/oph/koski/api/misc/KäyttöoikeusryhmätSpec.scala

TOR-xxxx: Poista väliaikaisesti tuki hienojakoisille käyttöoikeuksille

---

src/main/scala/fi/oph/koski/db/KoskiTables.scala
src/test/scala/fi/oph/koski/api/misc/KäyttöoikeusryhmätSpec.scala

TOR-xxxx: Palauta väliaikaisesti poistetut hienojakoiset käyttöoikeudet

---

src/main/resources/localization/koski-default-texts.json
src/main/scala/fi/oph/koski/schema/Korkeakoulu.scala

Lisää oma kelpoisuuden määritelmä ainepätevyyksien/opetettavan aineen kohdalle inffokenttään

TOR-2396 aineen inffokenttä

---

.trivyignore

Ei päivitetä transitiivisia depsuja suoraan

TOR-XXX Suppressoi oauth2 sample app -hälyt

---

src/main/scala/fi/oph/koski/db/KoskiTables.scala
src/main/scala/fi/oph/koski/koskiuser/Kayttooikeus.scala
src/main/scala/fi/oph/koski/koskiuser/KayttooikeusRepository.scala
src/main/scala/fi/oph/koski/koskiuser/Session.scala
src/main/scala/fi/oph/koski/massaluovutus/paallekkaisetopiskeluoikeudet/MassaluovutusQueryPaallekkaisetOpiskeluoikeudet.scala
src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotRepository.scala
src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenOppijamäärätRaportti.scala
src/main/scala/fi/oph/koski/raportit/esiopetus/EsiopetuksenOppijamaaristaRaportoiva.scala
src/main/scala/fi/oph/koski/raportit/esiopetus/EsiopetusRaportti.scala
src/main/scala/fi/oph/koski/validation/KoskiValidator.scala

TOR-2412: Optimoi varhaiskasvatuksen käyttöoikeuksien käsittely

---

src/main/resources/documentation/omadata_oauth2.md

TOR-2430: Korjaa rikkinäinen linkki dokumentaatiossa
