- web/app/editor/KurssiEditor.jsx
Issues to be resolved (may not be an exhaustive list):
- unless https://github.com/facebook/react/issues/11027
- Polyfill, or maybe in the long run move to https://github.com/GoogleChrome/puppeteer
Dependencies:
- wait for PR to be merged: see https://github.com/akiran/react-highlight/pull/43 (or fork?) 
- merge upstream (adds React 16 as peer dependency: helior/react-highlighter@1151ef1)
- causes `Warning: Accessing createClass via the main React package is deprecated`
> [WIP] Upgrade React to version 16

- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/fi/oph/koski/IndexServlet.scala
- src/main/scala/fi/oph/koski/config/Environment.scala
- src/main/scala/fi/oph/koski/config/KoskiApplication.scala
- src/main/scala/fi/oph/koski/fixture/Fixtures.scala
- web/app/lander/IdLogin.jsx
- web/app/lander/Lander.jsx
- web/app/lander/LanderInfo.jsx
- web/app/lander/LanderWithLogin.jsx
- web/webpack.config.js
**Summary**: Only show national identification number login form within lander page on development environments (local and dev).
**Implementation**: Conditionally serve a separate js bundle that includes/excludes the login form based on environment (in order to prevent leaking the client-side components to users in higher-than-dev environments).
**Note**: The js bundles are still accessible with a direct URI. Should they be?
> Kansalaiskali restrict login

- src/main/resources/localization/default-texts.json
- src/main/scala/fi/oph/koski/schema/Korkeakoulu.scala
- src/main/scala/fi/oph/koski/schema/Vahvistus.scala
- src/main/scala/fi/oph/koski/suoritusote/OpintosuoritusoteHtml.scala
- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
- src/test/scala/fi/oph/koski/api/KorkeakouluSpec.scala
- web/app/opiskeluoikeus/OpiskeluoikeusEditor.jsx
- web/app/style/opiskeluoikeus.less
- web/app/suoritus/ArvosanaEditor.jsx
- web/app/suoritus/SuoritusEditor.jsx
- web/app/virta/Korkeakoulusuoritukset.jsx
- web/test/spec/korkeakouluSpec.js
Näytetään suoritukset taulukkomuodossa.
- Mikäli opiskeluoikeuteen liittyy tutkintosuoritus, näytetään 1) sen tiedot ja 2) hierarkkisesti taulukoituna siihen liittyvät suoritukset sekä niiden osasuoritukset 
- Mikäli "opiskeluoikeus" on ainoastaan kooste irrallisista (samassa paikassa suoritetuista) suorituksista, näytetään nämä vastaavasti taulukoituna (kuitenkin ilman opiskeluoikeus- ja tutkintotietoja)
> Muotoile Virta-suoritukset käyttöliittymässä

- web/app/uusisuoritus/UusiAmmatillisenTutkinnonSuoritus.jsx
- web/test/spec/ammatillinenSpec.js
TOR-340
Rajoita kälissä suoritusten lisäämistä ammatilliseen opiskeluoikeuteen seuraavasti:
- Kun Valma, Telma tai "ammatillisen tutkinnon osa / osia", poista kälistä mahdollisuus lisätä:
- ammatillisen tutkinnon suoritus
- näyttötutkintoon valmistavan koulutuksen suoritus
> Rajoita kälissä suoritusten lisäämistä ammatilliseen opiskeluoikeuteen

- src/main/scala/fi/oph/koski/tutkinto/Koulutustyyppi.scala
- src/main/scala/fi/oph/koski/tutkinto/TutkinnonPerusteetServlet.scala
- web/app/suoritus/Suoritustaulukko.jsx
- web/test/page/opinnotPage.js
- web/test/spec/ammatillinenSpec.js
TOR-341: kälissä
1. Poista Telmalta mahdollisuus tutkinnon osan lisäämiseen toisesta tutkinnosta (edd2214)
1. Lisää Telmalle ja Valmalle mahdollisuus tutkinnon osan sanallisen arvioinnin syöttämiseen
> Muutoksia Valma- ja Telma-käleihin

- src/main/resources/mockdata/virta/opintotiedot/090888-929X.xml
- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
Tuotannon virtadatasta tullut epävalidi suorituskieliarvo on johtanut virheeseen. Ei heitetä poikkeusta vaan palautetaan tyhjä arvo.
> Defensiivinen virta kielikoodien käsittely

- src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala
- src/test/scala/fi/oph/koski/api/OppijaUpdateSpec.scala
Korjaa virheen joka ilmeni kun palvelukäyttäjänä tehdyssä
tiedonsiirrossa oli vääränmuotoinen hetu.
> Validoi hetu ja oid tiedonsiirtodatan tallennuksessa

- web/app/uusioppija/UusiAmmatillisenKoulutuksenSuoritus.jsx
- web/test/spec/ammatillinenSpec.js
"Lisää uusi opiskelija" -> Nimitiedot + Oppilaitos: Stadin ammattiopisto, Opiskeluoikeus: Ammatillinen koulutus, Suoritustyyppi: Ammatillisen tutkinnon osa/osia, Tutkinto: Autoalan perustutkinto, Suoritustapa: Näyttötutkinto -> "Lisää opiskelija"-nappi enabloituu
> Korjaa osittaisen ammatillisen suorituksen lisäys

- src/main/scala/fi/oph/koski/koodisto/RemoteKoodistoPalvelu.scala
Sille ei löydy mitään lisätietoja, vältetään koodistopalvelun >500 HTTP-pyynnön kuormapiikki
> Älä hae koodiston lisätietoja lukionkurssitops2003nuoret koodistolle

- src/main/scala/fi/oph/koski/schedule/UpdateHenkilotTask.scala
Oppijanumerorekisterin hyväksymä maksimikoko
> Kutista henkilötiedotpäivityksen batchin koko 5000:n

- src/main/scala/fi/oph/koski/schema/Lukio.scala
- web/app/ib/IB.jsx
- web/app/kurssi/UusiKurssiPopup.jsx
- web/app/lukio/LukionOppiaineEditor.jsx
- web/app/lukio/LukionOppiaineenOppimaaranSuoritusEditor.jsx
- web/app/lukio/LukionOppiaineetEditor.jsx
- web/app/lukio/LuvaEditor.jsx
- web/app/lukio/UusiLukionOppiaineDropdown.jsx
- web/app/style/dropdown.less
- web/app/style/kurssi.less
- web/app/style/lukio.less
- web/app/style/opiskeluoikeus.less
- web/app/suoritus/Koulutusmoduuli.js
- web/app/suoritus/suoritusEditorMapping.jsx
- web/test/spec/lukioSpec.js
**TOR-355**: Lukiotietojen syöttökäyttöliittymä (koulutustoimijalle)
- Mahdollistetaan lukiosuoritusten muokkaaminen käyttöliittymän kautta
Haaran ulkopuolelle jää:
- Uuden lukiosuorituksen luominen
- Paikallisten oppiaineiden lisäys
- Kurssien lisäyksessä kurssivaihtoehtojen rajoitus ePerusteiden kautta (https://github.com/Opetushallitus/koski/tree/lukio-eperusteet)
> Lukiotietojen syöttökäyttöliittymä

- src/main/scala/fi/oph/koski/editor/EditorServlet.scala
- src/main/scala/fi/oph/koski/eperusteet/EPerusteRakenne.scala
- web/app/kurssi/UusiKurssiDropdown.jsx
- web/app/kurssi/kurssi.js
- web/test/page/opinnotPage.js
- web/test/spec/lukioSpec.js
Liittyy **TOR-355**
Koska lukion oppiaine-/kurssikoodistoista puuttuu linkkaukset oppiaineeseen sisältyvistä kursseista, niin:
Käytetään 
- opetussuunnitelman diaarinumeroa
- oppiaineen oppimäärää (kieliaine / matematiikka) ja 
- ePerusteita 
rajaamaan kurssivaihtoehtoja, kun lisätään kurssia lukion oppiaineeseen.
> Lukiokurssien lisäys ePerusteiden avulla

- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/fi/oph/koski/IndexServlet.scala
- src/main/scala/fi/oph/koski/sso/ShibbolethLoginServlet.scala
- web/app/EiSuorituksia.jsx
- web/app/style/ei-suorituksia.less
- web/app/style/main.less
- web/webpack.config.js
Ohjataan kirjautumisen jälkeen omat tiedot -sivulle myös käyttäjä, jolle ei löydy oppijaa (ennen: käyttäjälle palautuu JSON:ia), mutta näytetään kirjautumattomalle käyttäjälle "ei suorituksia" -sivu.
> Ei suorituksia -sivu

- web/app/EiSuorituksia.jsx
- web/app/OmatTiedot.jsx
- web/app/style/omattiedot.less
- web/test/page/omatTiedotPage.js
- web/test/spec/omatTiedotSpec.js
Näytetään parempi selitysteksti kirjautuneelle kansalaiselle, kun opiskeluoikeuksia ei löydy.
> Ei suorituksia kirjautuneella

- src/main/resources/mockdata/koodisto/koodit/koskikoulutustendiaarinumerot.json
- src/main/scala/fi/oph/koski/tutkinto/TutkinnonPerusteetServlet.scala
- web/app/suoritus/PerusteDropdown.jsx
- web/app/suoritus/Suoritus.js
Erotetaan lukiokoulutukseen ja aikuisten lukiokoulutukseen kuuluvat diaarinumerot toisistaan.
Koskessa sekä nuorten että aikuisten lukiokoulutus on "Lukion opiskeluoikeus", jonka määrittää tarkemmin Lukion oppimäärän (tai oppiaineen oppimäärän) suorituksen tieto "oppimäärä". Muutetaan koulutustyyppi -> diaarinumerot -rajapintaa siten, että usean koulutustyypin sisältämät diaarinumerot voidaan hakea yhdellä kyselyllä: näin voidaan hakea samalla kertaa sekä lukiokoulutuksen että aikuisten lukiokoulutuksen mahdolliset perusteet (diaarinumerot).
> Lukiosuoritusten koulutustyypit

- src/main/resources/mockdata/ytr/120674-064R.json
- src/main/scala/fi/oph/koski/ytr/YtrOppija.scala
- web/test/spec/ylioppilastutkintoSpec.js
Kansalainen ei näe tietojaan, tulee virheitä lokiin tyyliin _java.lang.RuntimeException: Validation error while de-serializing as fi.oph.koski.ytr.YtrOppija: List(ValidationError(language,JNothing,MissingProperty(missingProperty)))_
> Language-kenttää ei aina välitetä ytr-datassa

- src/main/scala/fi/oph/koski/editor/EditorServlet.scala
Mahdollistetaan valtakunnallisten kurssien koodien palautus, vaikka
hakuparametreilla ei löytyisikään kursseja ePerusteista. Esimerkiksi
A1-englannin tunniste- ja kieli-koodit eivät Kosken mallissa vastaa ePerusteiden
oppiainetta ja oppimäärää, joten nämä rajautuivat pois palautetuista vaihtoehdoista.
Palautetaan nyt kaikki valtakunnalliset kurssit, mikäli haku
ePerusteista ei tuota kurssituloksia (vaikka diaarinumeron mukainen
rakenne löytyisikin).
> Paranna valtakunnallisten lukion kurssien lisäystä

- web/app/oppiaine/UusiOppiaineDropdown.jsx
- web/app/uusioppija/Oppiaine.jsx
- Ennen: uuden paikallisen oppiaineen lisäys-painike ei toimi, sillä
uuden opiskeluoikeuden lisäykseen ei ole liitetty uuden paikallisen
oppiaineen lisäyskäyttöliittymää
- Nyt: poistetaan painike
> Älä näytä lisää-painiketta uuden oppiaineen opiskeluoikeuden lisäyksessä

- web/app/ib/UusiIBOppiaineDropdown.jsx
- web/app/lukio/UusiLukionOppiaineDropdown.jsx
- web/test/spec/lukioSpec.js
- Organisaation preferencejen kautta haetulla paikallisella oppiaineella
ei ole parent-tietoa. Luodaan tässä tapauksessa uusi oppiaineen
suoritus.
> Korjaa organisaation preferenceistä haetun oppiaineen lisäys

- src/main/resources/localization/default-texts.json
- src/main/resources/mockdata/koodisto/koodit/suorituksentyyppi.json
- src/main/scala/fi/oph/koski/editor/OppijaEditorModel.scala
- web/app/uusisuoritus/UusiIBTutkinnonSuoritus.jsx
- web/test/page/addOppijaPage.js
- web/test/spec/ibSpec.js
- Päivitetään IB:n `suorituksentyyppi`-koodit
- Järjestetään päätason IB-suoritukset seuraavasti:
1. IB-tutkinnon suoritus
2. Pre-IB-suoritus
- Tällöin myös opiskeluoikeuden otsakeriviin tulee oikein IB-tutkinto (jos on) ja pre-IB vain jos IB-tutkintosuoritusta ei ole
> Päivitä IB-koodit

- src/main/scala/fi/oph/koski/henkilo/Hetu.scala
- src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloRepository.scala
- web/test/spec/omatTiedotSpec.js
Syntymäaika on oleellinen tieto, kun kansalainen raportoi suorituksissaan olevasta virheestä. Mikäli siis (optionaalinen) syntymäaika-tieto puuttuu, luodaan se hetun perusteella.
Liittyy: TOR-80
> Parsitaan syntymäaika hetusta kun ei syntymäaikatietoa

- web/app/util/http.js
- Problem: when firing multiple consecutive http requests and taking only the last result (i.e. using flatMapLatest to fire requests), the errorMapper would not get triggered for the previous results. This causes issues with the http.cachedGet.
- Fix: attach the .onEnd subscription to the actual property that has the
error mapper (instead of the property that was composed without the
error mapper), in order to keep the property alive even when switching
to a latter request via the flatMapLatest.
> Fix error mapper not being used

- src/main/scala/fi/oph/koski/documentation/ExamplesIB.scala
- src/main/scala/fi/oph/koski/schema/IB.scala
Myös IB-oppiaineella (IB-kurssin lisäksi) voi arviointiin liittyä effort-tieto. Mahdollistetaan tämä lisäämällä optionaalinen kenttä.
> Lisää IB-oppiaineelle optionaalinen effort-tieto arviointiin

- src/main/resources/reference.conf
- src/main/scala/fi/oph/koski/config/Features.scala
- src/main/scala/fi/oph/koski/config/KoskiApplication.scala
- src/main/scala/fi/oph/koski/email/EmailSender.scala
- src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloFacade.scala
- src/main/scala/fi/oph/koski/koskiuser/KayttooikeusRyhmat.scala
- src/main/scala/fi/oph/koski/koskiuser/Kayttooikeusryhma.scala
- src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
- src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoFailureMailer.scala
- src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala
- src/test/scala/fi/oph/koski/api/TiedonsiirtoSpec.scala
- src/test/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoFailureMailerSpec.scala
- web/test/spec/raporttiSpec.js
Disabloitu kaikissa ympäristöissä konffivivulla (https://github.com/Opetushallitus/koski-env/commit/8f03ecd83ebee7a30e4f7dcee8f8af67a9453d96), otetaan käyttöön vasta kun oppilashallintajärjestelmät ottavat automaattisen tiedonsiiirron käyttöön.
> Tiedonsiirtovirheestä lähtee sähköposti

- web/app/date/date.js
- web/app/opiskeluoikeus/OpiskeluoikeudenTilaEditor.jsx
Tilanne tällä hetkellä:
- `formatISODate` olettaa inputtina JavaScript Date:n, joka on ko. päivämäärän keskiyö UTC:ssä (ja toimii väärin, jos selaimen aikavyöhyke on UTC:stä länteen)
- `parseFinnishDate` palauttaa ko. päivämäärän keskiyön UTC:ssä jos selaimen aikavyöhyke on UTC:stä itään, ja on rikki jos selaimen aikavyöhyke on länteen.
- `parseISODate` (samassa tiedossa) palauttaa JavaScript Date:n, joka on ko. päivämäärän keskiyö selaimen aikavyöhykkeessä
En ole 100% varma mikä olisi paras mahdollinen ratkaisu (varmaankin erillinen tietotyyppi ala LocalDate, mutta se on isompi muutos), mutta tämä pullari korjaa tilanteen niin, että käytetään aina ko. päivämäärän keskiyötä selaimen aikavyöhykkeessä.
Nyt nämä funkkarit joihin on koskettu pitäisi toimia oikein riippumatta onko selaimen …
> Fix JavaScript Date parsing/formatting if system time zone is west of UTC

- web/app/EiSuorituksia.jsx
- web/app/OmatTiedot.jsx
- web/app/omattiedot/EiSuorituksiaInfo.jsx
Kansalaiselle näytetään lyhyen aikaa "ei suorituksia" -ilmoitus avattaessa omat tiedot -sivua. Korjataan tämä virheellinen näyttäminen.
> Korjaa kansalaiselle välähtävä 'Ei suorituksia'

- src/main/scala/fi/oph/koski/IndexServlet.scala
- src/main/scala/fi/oph/koski/koskiuser/AuthenticationSupport.scala
- src/main/scala/fi/oph/koski/koskiuser/KoskiSessionStatus.scala
- src/main/scala/fi/oph/koski/koskiuser/LogoutServlet.scala
TOR-435
Käyttäjän session vanhennuttua tulisi käyttäjä uudelleenohjata eri
paikkoihin riippuen siitä, onko kyseessä kansalais- vai
virkailijakäyttäjä. Aiemmin kuitenkaan tätä tietoa ei tässä vaiheessa
enää ollut, sillä käyttäjän sessio oli jo poistettu. Kaikki käyttäjät
ohjattiin tässä tilanteessa virkailijan osoitteeseen.
Fix:
- Tarkistetaan vanhentuneesta sessiosta ennen sessiotiedon hävittämistä,
oliko kyseessä kansalais- vai virkailijakäyttäjä. Ohjataan tämän
perusteella käyttäjä oikeaan paikkaan.
> Fix faulty redirects when user session has expired

- src/main/resources/localization/default-texts.json
- src/main/resources/mockdata/koodisto/koodistot/erityisopetuksentoteutuspaikka.json
- src/main/resources/mockdata/koodisto/koodit/erityisopetuksentoteutuspaikka.json
- src/main/scala/fi/oph/koski/koodisto/Koodistot.scala
- src/main/scala/fi/oph/koski/schema/Esiopetus.scala
- src/main/scala/fi/oph/koski/schema/NuortenPerusopetus.scala
TOR-436
- Mallinnetaan perusopetukseen ja perusopetuksen lisäopetukseen "eritysen tuen päätös" -tiedon osaksi uusi kenttä "toteutuspaikka", jolla on 4 eri mahdollista arvoa
- Lisätään arvoja varten uusi koodisto "erityisopetuksen toteutuspaikka"
- Lisätään koko erityisen tuen päätös -rakenne tässä muodossa myös esiopetukselle
> [WIP] TOR-436 erityisopetuksen toteutuspaikka

- web/app/opiskeluoikeus/OpiskeluoikeusEditor.jsx
- web/app/opiskeluoikeus/Versiohistoria.jsx
Opiskeluoikeuksilla, joita ei tallenneta Koskeen, ei ole opiskeluoikeusoid:a eikä versiohistoriaa.
Piilotetaan nämä käyttäliittymästä, jos opiskeluoikeudella ei ole oidia
> Piilotetaan opiskeluoikeusoid ja versiohistoria

- web/app/editor/PropertiesEditor.jsx
Properties editor printtaa tyhjiä tauluja joissain tilanteissa, ks esim gäppiä Järjestämismuotojen ja Ryhmätietojen välillä opiskeluoikeudessa: https://dev.koski.opintopolku.fi/koski/oppija/1.2.246.562.24.56145616714?1.2.246.562.15.75706369487.suoritus=Autoalan%20perustutkinto
> Properties editor ei printtaa tyhjiä tauluja

- src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
TOR-489
Sallitaan VALMA-suorituksen tyypillä suorituksen vahvistus myöhemmin kuin opiskeluoikeuden päättävän tilan päivämäärä.
> Sallitaan vahvistus opiskeluoikeuden päättymisen jälkeen kun VALMA

- src/main/resources/mockdata/ytr/080698-967F.json
- src/main/scala/fi/oph/koski/fixture/KoskiDatabaseFixtures.scala
- src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
- src/main/scala/fi/oph/koski/organisaatio/MockOrganisaatioRepository.scala
- web/app/omattiedot/virheraportointi/RadioOption.jsx
- web/app/omattiedot/virheraportointi/RaportoiVirheestaForm.jsx
- web/test/spec/omatTiedotSpec.js
TOR-495
Selvityksessä: 
Näytetään kansalaisen virheraportointilomakkeessa ylioppilastutkintojen osalta "oppilaitoksena" YTL eikä lukiota. Näytetään kuitenkin lisäksi lukio, mikäli myös lukion suorituksia.
> Kohdennetaan kansalaisen ylioppilastutkintovirheraportoinnit YTL:lle

- web/app/opiskeluoikeus/OpiskeluoikeudenUusiTilaPopup.jsx
- web/app/uusioppija/UusiOpiskeluoikeus.jsx
- web/test/page/addOppijaPage.js
- web/test/spec/ammatillinenSpec.js
- web/test/spec/perusopetusSpec.js
TOR-496
Poistetaan ammatillisen syöttökälistä tila "eronnut". Arvo kuitenkin näytetään mikäli se on opiskeluoikeudelle välitetty. "Eronnut" on terminä uuden laindääsännön myötä vanhentunut, ja oppilaitosten tulee käyttää tilaa "katsotaan eronneeksi".
> Eronnut-tila pois ammatillisen kälistä

- src/main/scala/fi/oph/koski/tiedonsiirto/ExamplesTiedonsiirto.scala
- src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala
- web/app/style/tiedonsiirrot.less
- web/app/style/topbar.less
- web/app/tiedonsiirrot/Tiedonsiirtotaulukko.jsx
- web/test/spec/tiedonsiirrotSpec.js
TOR-395
Lisätään tiedonsiirrot-sivulle (tiedonsiirtoloki- ja virheet-taulukoihin) "tutkinto / osaamisala / nimike" -sarake.
> Tiedonsiirrot-sivulle tutkintotiedot

- web/app/editor/ModalDialog.jsx
Virkailijan ammatillisen koulutuksen editorissa focus trap aiheutti
"Lisää tutkinnon osa toisesta tutkinnosta" -modaalin menemisen ruudun
reunan yli.
> Remove focus trapping from non-full-screen modal to fix regression

- web/app/style/oppija.less
Bug: virkailijan näkymässä suoritus-välilehdet menivät edit-palkin
päälle.
Cause: edit-palkin pinotaso oli määritelty suhteessa edit-palkin omaan
pinokontekstiin, jonka taso puolestaan oli alempi kuin välilehtien.
Fix: määritellään edit-palkin kontekstin taso korkeammaksi kuin
välilehtien.
> Korjaa näkymien virheellinen pinoamisjärjestys

- web/app/components/ModalMount.jsx
- web/app/editor/ModalDialog.jsx
- web/app/omattiedot/suoritusjako/SuoritusjakoLink.jsx
- web/app/style/global.less
This makes it practical to add aria-hidden to other content and will therefore prevent screen readers from escaping the modal contents. Similar case for traditional displays is already handled within the modal dialog with focus trapping.
This only applies to kansalainen (suoritusjako confirmation).
> Mount modal directly on body

- src/main/scala/fi/oph/koski/koskiuser/AuthenticationSupport.scala
- src/test/scala/fi/oph/koski/koskiuser/AuthenticationSpec.scala
When 3rd party apps call My Data APIs via Palveluväylä, all error messages are passed to the caller. Removed username from failed authentication error message so it won't leak to 3rd parties.
> less explicit error messages: don't leak username to 3rd parties

- src/main/scala/fi/oph/koski/koskiuser/KoskiSession.scala
- src/test/scala/fi/oph/koski/api/SuoritusjakoTestMethods.scala
- Osa suoritusjaon sisällöstä näytettiin suomeksi vaikka kieleksi olisi
valittu ruotsi
> Korjaa väärä kieli suoritusjakojen katselussa

- web/app/components/ButtonWithConfirmation.jsx
- web/app/style/opiskeluoikeus.less
Opiskeluoikeuden mitätöinnissä ja päätason suoritusten poistossa on
käytössä kaksivaiheinen painike, jossa toisena vaiheena vahvistetaan
haluttu toimenpide. Vaihdetaan toisen vaiheen peruutus- ja
hyväksymispainikkeiden paikkaa siten, että vahingossa hyväksyminen
(esim. tuplaklikkauksella) ei ole niin helposti tehtävissä.
> [WIP] Tee vahvistus-painikkeesta turvallisempi käyttää

- src/main/scala/fi/oph/koski/documentation/KoskiSchemaDocumentHtml.scala
- src/main/scala/fi/oph/koski/schema/annotation/Deprecated.scala
- web/static/css/schema-printable.css
Näytetään vanhentuneet kentät HTML-dokumentaatiossa:
- kentän nimen kohdalla "Vanhentunut kenttä"
- kentän kuvauksen kohdalla myös deprecated-metadatan viesti
Näytetään vanhentuneet kentät JSON-skeemakatselijassa:
- näytetään vanhentuneet kentät katselijan oranssilla deprecated-merkkivärillä
- näytetään kentän kuvauksessa myös deprecated-metadatan viesti
> Merkitse vanhentuneet kentät skeema-dokumentaatioon

- src/main/scala/fi/oph/koski/servlet/MyDataSupport.scala
- src/test/scala/fi/oph/koski/mydata/MyDataSupportTest.scala
- web/app/omadata/HyvaksyntaLanding.jsx
- web/test/page/myDataPage.js
URL-encode the callback parameter so it won't get messed up in login redirects
> Encode callback parameter

- pom.xml
Asetettu skipTests = true, kuten ohjeistettu täällä http://www.scalatest.org/user_guide/using_the_scalatest_maven_plugin
surefire ei toimi uusimmalla JDK:lla: build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13
https://issues.apache.org/jira/browse/SUREFIRE-1588
> Poista surefire-plugin käytöstä

- web/app/omadata/Header.jsx
- web/app/omadata/HyvaksyntaAnnettu.jsx
- web/app/omadata/HyvaksyntaLanding.jsx
- web/app/style/omadata.less
- web/test/spec/myDataSpec.js
- Poistaa logout napin yläpalkista
- Poistaa mobiilimenun (Täältä aikaisemmin löytyi logout nappi mobiililla)
- Siirtyy palveluntarjoajan sivulle hitaammin hyväksynnän jälkeen
> Poistaa logoutin tietojen käyttö sivulta

- src/main/resources/documentation/rajapinnat_palveluvayla_omadata.md
WSDL link on MyData documentation now points to Suomi.fi liityntäkatalogi instead of Koski-sovitinpalvelu URL.
> Update MyData documentation (link to WSDL)

- web/test/page/opinnotPage.js
- web/test/spec/diaSpec.js
Testattu nyt myös seuraavia:
- opiskeluoikeuden lisätiedot
- valmistavan ja tutkintovaiheen tiedot
- lasketaan kokonaispistemäärään -valinta
- päättökokeet
Lisäksi parannettu testikoodin ja -outputin luettavuutta.
> Lisää testejä saksalaisen koulun käyttöliittymälle

- src/main/scala/fi/oph/koski/oppilaitos/OppilaitosServlet.scala
- web/app/suoritus/Suoritus.js
- web/app/uusioppija/UusiDIASuoritus.jsx
- web/app/uusioppija/UusiOpiskeluoikeus.jsx
- web/app/uusioppija/diaSuoritus.js
- web/app/uusisuoritus/UusiDIATutkinnonSuoritus.jsx
- web/app/uusisuoritus/UusiSuoritusLink.jsx
- web/test/page/addOppijaPage.js
- web/test/spec/diaSpec.js
Mahdollistetaan kälissä
- uuden DIA-opiskeluoikeuden lisääminen
- valmistavalla vaiheella tai
- tutkintovaiheella
- olemassa olevaan DIA-opiskeluoikeuteen
- valmistavan vaiheen lisääminen, jos ei ole mutta on tutkintovaihe
- tutkintovaiheen lisääminen, jos ei ole mutta on valmistava vaihe
> Mahdollista uuden DIA-oppijan lisäys kälissä

- src/main/scala/fi/oph/koski/koskiuser/KoskiSession.scala
- src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
- src/main/scala/fi/oph/koski/permission/PermissionCheckServlet.scala
- src/test/scala/fi/oph/koski/api/PermissionCheckSpec.scala
HENKILONHALLINTA-oikeudet ovat deprekoituneet.
OPPIJANUMEROREKISTERI-oikeudet korvaavat nämä.
> Muuta Oppijanumerorekisteri-nappulan käyttöoikeudet

- web/app/suoritus/Suoritus.js
- web/app/uusioppija/UusiDIASuoritus.jsx
- web/app/uusisuoritus/UusiDIATutkinnonSuoritus.jsx
- web/test/spec/diaSpec.js
Uutta opiskeluoikeutta lisättäessä DIA-tutkinnon valinta opiskeluoikeuden tyypiksi muuttaa nyt automaattisesti suorituskieleksi saksan.
Lisättäessä uutta suoritusta DIA-tutkintoon, kopioidaan suorituskieli olemassaolevalta suoritukselta (eli käytännössä joko kopioidaan valmistavan vaiheen suorituskieli tutkintovaiheen suorituskieleksi, tai päinvastoin). Näin saadaan ensimmäiselle suoritukselle oletusarvoisesti valittu suorituskieli "saksa" automaattisesti myös toiselle suoritukselle.
> DIA-tutkinnon ja -suoritusten oletuskieleksi saksa

- web/app/kurssi/UusiKurssiDropdown.jsx
- web/app/suoritus/Koulutusmoduuli.js
- web/test/spec/diaSpec.js
Saksalaisen koulun käyttöliittymässä, uutta kurssia valittaessa, näytetään dropdownin sisältönä nyt ainoastaan kurssin nimi, eikä kurssin koodi sekä nimi.
> Näytä pelkkä nimi saksalaisen koulun käyttöliittymän osasuoritus-dropdownissa

- src/main/scala/fi/oph/koski/documentation/DIAExampleData.scala
- src/main/scala/fi/oph/koski/documentation/ExamplesDIA.scala
- src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
- src/main/scala/fi/oph/koski/schema/DIA.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OpiskeluoikeusTestMethodsDIA.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationDIASpec.scala
- web/test/page/opinnotPage.js
- web/test/spec/diaSpec.js
- Lisätään **DIA-lukukausille laajuus** (mutta ei muille osasuorituksille eli kirjalliselle/suulliselle kokeelle eikä näyttötutkinnolle).
- Pidetään laajuus myös oppiaineella
- Oppiaineen laajuus on summa osasuorituksien laajuuksista
On jo olemassa validaatio, joka validoi, että osasuoritusten laajuus täsmää oppiaineen laajuuteen. Lisätään lisäksi validaatio, joka validoi, että valmiilla DIA-päätason suorituksella (DIA-tutkinto tai valmistava vaihe) on oltava oppiaineilla laajuudet. Näin saadaan tämä data "pakotettua" talteen talletetuksi, mutta mahdollistetaan sen muuttamatta jättäminen joka kerta, kun kesken olevaa suoritusta muokataan.
> DIA-laajuudet

- src/main/scala/fi/oph/koski/editor/EditorModelBuilder.scala
- src/main/scala/fi/oph/koski/schema/DIA.scala
- web/test/page/opinnotPage.js
- web/test/spec/diaSpec.js
DIA-tutkinnossa lukukaudet lähtökohtaisesti lasketaan kokonaispistemäärään, mutta tietyt lukukausisuoritukset on mahdollista jättää laskematta. Muutetaan `lasketaanKokonaispistemäärään`-kentän toimintaa syöttökäyttöliittymässä vastaamaan tätä: kun arviointi lisätään, merkitään oletuksena, että suoritus lasketaan kokonaispistemäärään. Näin vältetään tarve kääntä flagi käsin joka lukukausisuorituksen kohdalla.
> DIA:n "lasketaan kokonaispisteisiin" oletusarvoksi true

- pom.xml
High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
Description: Deserialization of Untrusted Data
Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72448
Introduced through: com.fasterxml.jackson.core:jackson-databind@2.9.7
> Upgrade jackson-databind because of vulnerability in current version

- src/main/scala/fi/oph/koski/validation/DateValidation.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationSpec.scala
- web/app/opiskeluoikeus/OpiskeluoikeudenUusiTilaPopup.jsx
- web/test/spec/perusopetusSpec.js
Kun opiskeluoikeudelle asetetaan uutta tilaa, uuden tilan alku päivämäärän tulee olla uudempi päivämäärä kuin edellisen tilan alku päivämäärän
- Estää saman tai vanhemman alku päivämäärän asettamisen uudelle tilalle virkailijan käyttöliittymässä
- Tiedonsiirrossa palauttaa virheviestin jos kahdella tilalla on sama alkupäivä
(testeissä joissa lisäillään uusia tiloja oletettiin, että defaulttina tuleva alkupäivä on validi, joten testeihin on lisätty alkupäivän asettamisia, jotta peräkkäiset tilan lisäykset menevät läpi)
> TOR-566: Eri opiskeluoikeuden tilat samalla alkupvm:llä tuottaa virheen

- README.md
- src/main/scala/fi/oph/koski/raportit/Opiskelijavuositiedot.scala
- src/test/scala/fi/oph/koski/raportit/RaportitSpec.scala
- web/package-lock.json
Opiskelijavuositiedot-raportin opiskelijavuosikertymässä lasketaan valmistumispäivä aina 100% läsnäololla, vaikka valmistumista edeltäneet opinnot olisivat olleet osa-aikaisia.
> TOR-565: Opiskelijavuosikertymän laskenta opiskelijavuositiedot-raportilla

- src/main/resources/mockdata/koodisto/koodit/aikuistenperusopetuksenpaattovaiheenkurssit2017.json
- web/test/spec/perusopetusSpec.js
[TOR-538](https://jira.csc.fi/browse/TOR-538): Korjattu aikuisten perusopetuksen äidinkielen kurssien jaottelua. Tämän muutoksen jälkeen oppiaineen valinta (suomen kieli ja kirjallisuus / suomi toisena kielenä ja kirjallisuus / ruotsin kieli ja kirjallisuus) filtteröi kurssivalikoimaan vain ko. oppiaineen kurssit.
> TOR-538: Aikuisten perusopetuksen oppimäärän äidinkielen kurssit

- web/test/spec/perusopetusSpec.js
- web/test/util/testHelpers.js
Failaava testi:
```
Perusopetus
Opiskeluoikeuden lisääminen
Aikuisten perusopetuksen alkuvaihe
Päättövaiheen opintojen lisääminen
"before all" hook:
Error: Timeout of 10000ms exceeded.
```
Prefill-pyyntö kestää aikuisten perusopetuksen osalta huomattavan kauan
(responsen koko gzipattuna 611 KB, avattuna 6.6MB). Vastauksen
oppiaineiden prototypes-tietoon sisällytetään valtavasti eri koodeja ja
luokkia, ja hiljattain lisätyt uudet skeemaluokat ja koodit ovat
paisuttaneet vastausta entisestään. Nyt pyyntöjen tekeminen hidastaa
testien suoritusta jo niin paljon, että Jenkinsillä ko. testi failaa
epäsäännöllisesti.
Hotfixataan kasvattamalla ko. testien timeouttia. Varsinainen korjaus
edellyttää prototyyppien koostamisen tutkimista ja optimoimista.
> Hotfixaa timeoutista johtuva failaava testi

- src/main/scala/fi/oph/koski/schema/Korkeakoulu.scala
- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
- src/test/scala/fi/oph/koski/api/OpiskeluoikeusTestMethodsKorkeakoulu.scala
- src/test/scala/fi/oph/koski/virta/VirtaXMLConverterSpec.scala
Virta-vastauksen konvertoinnissa opiskeluoikeuden tyyppi sisälsi aiemmin ainostaan tyypin koodin. Nyt se sisältää myös tyypin nimen.
Poistettu lisäksi Korkeakoulu-skeemasta `tyyppi`-kentän oletusarvo, joka viittasi konstruktoriin jota käyttämällä tyypin nimi jäi tyhjäksi. Täten samanlaista bugia ei jatkossa pääse vahingossa syntymään uudestaan.
> Lisätty opiskeluoikeuden tyypin nimi Virta-tietoihin

- src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
- src/main/scala/fi/oph/koski/validation/DateValidation.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OpiskeluoikeusTestMethodsAmmatillinen.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationSpec.scala
- Oma virheviesti tilanteelle jossa kaksi tilaa samalla päivämäärällä
- Jos opiskeluoikeudella on oikeuden päättävä tila, tulee sen olla viimeinen ja ainut päättävä tila
* Kaksi päättävää tilaa sallitaan, jos viimeinen tila on 'mitatoity'
> TOR-599 Opiskeluoikeuden tilojen uusia validaatioita

- src/main/resources/localization/default-texts.json
- src/main/resources/mockdata/koodisto/koodistot/ammatilliseentehtavaanvalmistavakoulutus.json
- src/main/resources/mockdata/koodisto/koodit/ammatilliseentehtavaanvalmistavakoulutus.json
- src/main/resources/mockdata/koodisto/koodit/suorituksentyyppi.json
- src/main/scala/fi/oph/koski/koodisto/Koodistot.scala
- src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
Lisätään muun ammatillisen koulutuksen tietomallin ensimmäinen luonnos. Sisältää kaksi uutta päätason suoritusta:
- `muuammatillinenkoulutus`
- `tutkinnonosaapienempikokonaisuus`
> Muu ammatillinen -tietomalli

- src/main/scala/fi/oph/koski/editor/EditorModelSerializer.scala
- src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
- src/main/scala/fi/oph/koski/schema/annotation/Annotations.scala
- web/app/editor/NumberEditor.jsx
- web/app/lukio/LukionOppiaineEditor.jsx
- web/app/lukio/LukionOppiaineetEditor.jsx
- web/app/lukio/OmatTiedotLukionOppiaineet.jsx
- web/app/suoritus/YhteensaSuoritettu.jsx
- web/app/util/format.js
- web/test/spec/ammatillinenSpec.js
* Ammatillisen tutkinnon painotettu keskiarvo näytetään nyt käyttöliittymässä aina kahdella desimaalilla (myös nollat, eli esim. keskiarvo 2 näytetään muodossa 2,00). Tätä varten lisätty skeemaan `Scale` -annotaatio, jolla näytettävien desimaalien lukumäärä voidaan määrittää.
* Lisäksi tehty seuraava korjaus: keskiarvo-kenttä näytetään silloin, kun ammatillisen tutkinnon suoritustapa on "reformi" (ei "ops").
> Ammatillisen tutkinnon keskiarvon esittäminen aina 2 desimaalilla

- src/main/resources/localization/default-texts.json
- src/main/resources/mockdata/koodisto/koodit/suorituksentyyppi.json
- src/main/scala/fi/oph/koski/schema/Ammatillinen.scala
- lisätään pilotti-tieto
- poistetaan pakollinen-tiedot (turhia muussa ammatillisessa)
- selkeytetään tutkinnon osaa pienemmän kokonaisuuden nimeämistä: _osasuoritukset_ ovat tutkinnon osaa pienempiä kokonaisuuksia, ja päätason suoritus on ainoastaan "kooste" näistä, jotta kokonaisuuksia saadaan liitettyä samaan suoritukseen
> Muu ammatillinen tietomalliviilaukset

- src/main/resources/mockdata/ytr/010280-952L.json
- src/main/resources/mockdata/ytr/080640-881R.json
- src/main/resources/mockdata/ytr/080698-967F.json
- src/main/resources/mockdata/ytr/080845-471D.json
- src/main/resources/mockdata/ytr/120872-781Y.json
- src/main/resources/mockdata/ytr/140940-558L.json
- src/main/resources/mockdata/ytr/210244-374K.json
- src/main/resources/mockdata/ytr/250493-602S.json
- src/main/resources/mockdata/ytr/280171-2730.json
- src/main/scala/fi/oph/koski/ytr/YtrOppija.scala
- src/main/scala/fi/oph/koski/ytr/YtrOppijaConverter.scala
Ylioppilastutkintorekisterin API:ssa kahden kentän nimi on muuttunut:
- `graduationSchoolOphOid` -> `certificateSchoolOphOid`
- `graduationSchoolYtlNumber` -> `certificateSchoolYtlNumber`
Muutos on toteutettu ylioppilastutkintorekisterin päässä niin, että API:n vastaus sisältää sekä uuden että vanhan nimiset kentät, joten Koski-järjestelmään tämä muutos voidaan tehdä välittömästi.
> Huomioitu ylioppilastutkintorekisterin kenttien nimenmuutos

- src/main/resources/mockdata/virta/opintotiedot/090992-3237.xml
- src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
- src/test/scala/fi/oph/koski/api/KorkeakouluSpec.scala
- src/test/scala/fi/oph/koski/luovutuspalvelu/PalveluvaylaSpec.scala
- web/test/spec/korkeakouluSpec.js
Jotkut oppilaitokset siirtävät opintojaksot opiskeluoikeuden alle eikä päätason suorituksen alle. Jos tutkinto on valmis laitetaan ne tutkinnon osasuorituksiksi. Tämä on luultavasti vähemmän hämmentävää datan käyttäjien kannalta. Lisäksi käyttöliittymässä näkyy otsikossa tutkinnon nimi eikä vain "x opintojaksoa".
> Siirrä päätasolla olevat opintojaksot valmiin tutkinnon alle

- src/main/resources/localization/default-texts.json
- src/main/scala/fi/oph/koski/documentation/DIAExampleData.scala
- src/main/scala/fi/oph/koski/documentation/ExamplesDIA.scala
- src/main/scala/fi/oph/koski/schema/DIA.scala
- src/main/scala/fi/oph/koski/schema/Laajuus.scala
- web/app/suoritus/RyhmiteltyOppiaineetEditor.jsx
- web/test/spec/diaSpec.js
Luodaan tutkintovaiheen DIA-oppiaineelle uusi rakenne "vastaavuustodistuksen tiedot", jonka alle 
- siirretään nykyinen "keskiarvo"-tieto ja
- lisätään "lukio-opintojen laajuus"
- 2 mahdollista yksikköä (opintopiste, kurssi)
- tälle tooltip: "valmistavan DIA-vaiheen ja DIA-tutkintovaiheen yhteenlaskettu laajuus"
> DIA-vastaavuustodistuksen tiedot

- src/main/scala/fi/oph/koski/koskiuser/RequiresLuovutuspalvelu.scala
- src/test/scala/fi/oph/koski/mydata/MyDataAPIProxyServletTest.scala
HTTP 403 vastataan edelleen, jos opinto-oikeuksien luovutukseen ei ole
myönnetty lupaa.
> TOR-649: Vastaa HTTP 401 jos luovutuspalvelukäyttäjän tunnukset ovat väärin

- src/main/scala/fi/oph/koski/db/PostgresDriverWithJsonSupport.scala
- src/main/scala/fi/oph/koski/documentation/PerusopetusExampleData.scala
- src/main/scala/fi/oph/koski/raportit/PerusopetuksenRaportitRepository.scala
- src/test/scala/fi/oph/koski/raportit/PerusopetuksenVuosiluokkaSpec.scala
Raportille tulostui kaikki oppilaitoksessa aktiivisena olevien oppijoiden vuosiluokka suoritus haetulta vuodelta => Nyt tulostetaan vain ne vuosiluokka suoritukset joiden vahvistuspäivä on sama tai tulevaisuudessa suhteessa parametrina annettuun päivään
Raportille tulostui tyhjiä oppimäärän suorituksia => Nyt tulostetaan vain niiden oppijoiden oppimäärän suoritukset joilla on viimeisin ysiluokan suoritus sellainen jota ei ole merkitty luokalle jääväksi
> Korjaa perusopetuksen vuosiluokka raportti

- src/main/scala/fi/oph/koski/raportit/AmmatillinenOsittainenRaportti.scala
- src/main/scala/fi/oph/koski/raportit/AmmatillinenRaporttiUtils.scala
- src/main/scala/fi/oph/koski/raportit/AmmatillinenTutkintoRaportti.scala
- src/test/scala/fi/oph/koski/raportit/AmmatillinenOsittainenRaporttiSpec.scala
- src/test/scala/fi/oph/koski/raportit/AmmatillinenTutkintoRaporttiSpec.scala
Vapaasti valittavat tutkinnon osat ja tutkintoa yksilöllisesti laajentavat tutkinnon osat lasketaan mukaan tutkinnon yhteislaajuuteen.
Valmiiden vapaasti tutkinnon osien ja tutkintoa yksilöllisesti laajentavien tutkinnon osien lukumäärä omiin kolumneihin excelissä.
"ammatillisentutkinnonosaapienempikokonaisuus" tyyppisiä osasuorituksia ei lasketa mihinkään
>  Ammatillisen suoritustietoraportin korjaus

- src/main/scala/fi/oph/koski/raportit/Excel.scala
- src/main/scala/fi/oph/koski/raportit/ExcelWriter.scala
- src/test/scala/fi/oph/koski/raportit/ExcelWriterSpec.scala
Korvataan huonosti luettava "Ohjeet" välilehti raportointi-exceleistä asettamalla kommentteja otsikkorivin sarakkeisiin, joihin halutaan tarkempi ohjeistus.
> Mahdollista excel-kommenttinen lisäys Columniin

- src/main/scala/fi/oph/koski/raportit/ExcelWriter.scala
- src/main/scala/fi/oph/koski/raportit/LukioRaportti.scala
- src/test/scala/fi/oph/koski/raportit/ExcelWriterSpec.scala
- src/test/scala/fi/oph/koski/raportit/LukioRaporttiSpec.scala
- Erikoismerkkejä ei filtteröidä kokonaan pois sillä tämä voi aiheuttaa kaksi saman nimistä välilehteä
- kielletyt merkit korvataan välilyönneillä
> Korjaa erikoismerkeistä aihetuva virhe excelien luonnissa

- src/main/resources/mockdata/virta/opintotiedot/270680-459P.xml
- src/main/scala/fi/oph/koski/editor/OppijaEditorModel.scala
- src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
- web/test/spec/korkeakouluSpec.js
- web/test/spec/omatTiedotSpec.js
Jos opiskeluoikeuden alla on kaksi päätason suoritusta, valitaan otsikkoon se päätason suoritus jolla on uusin vahvistus
> tor-677: korkeakoulun opiskeluoikeuden otsikko

- docker-compose.yaml
- postgresql/docker-entrypoint-initdb.d/create-test-db.sql
Luodaan docker-composen käynnistyksen yhteydessä myös koskitest kanta.
> Create koskitest db in docker-compose init

- src/test/scala/fi/oph/koski/raportit/EsiopetusRaporttiSpec.scala
Testin _"Raportti voidaan ladata ja lataaminen tuottaa auditlogin"_ osuus feilaa jos fixtureita ei olla ajettu sisään ennen testin ajoa. Joten siirretään `loadRaportointikantaFixtures`-kutsu `beforeAll`-koukkuun, jotta se on varmasti ajettuna ennen testejä.
> Korjaa EsiopetusRaporttiSpec kun se ajetaan ennen muita testejä

- src/main/scala/fi/oph/koski/schedule/KoskiScheduledTasks.scala
- src/main/scala/fi/oph/koski/schedule/PurgeOldSessionsTask.scala
- src/main/scala/fi/oph/koski/sso/KoskiSessionRepository.scala
- src/test/scala/fi/oph/koski/sso/KoskiSessionRepositorySpec.scala
https://jira.csc.fi/browse/TOR-817
Lisätään ajastettu tehtävä poistamaan yli vuoden vanhat sessiot `casserviceticket`-taulusta kerran päivässä.
Kommentoikaa mielellään matalalla kynnyksellä kaikesta mikä näyttää vähänkin oudolta projektin tyyli tai yleinen Scala-tyyli huomioiden tai ylipäänsä. 🙂 
Toteutuksessa on mahdollinen ongelma liittyen siihen, että tehtävä ajetaan ensimmäistä kertaa vasta 24h käynnistyksen jälkeen. Tällä hetkellä ei aiheuttane ongelmia, mutta jos siirrytään AWS:ään ja kontteihin, voi olla teoriassa mahdollista, ettei kontit ole tarpeeksi pitkään hengissä?
> Vanhentuneiden sessioiden poisto

- src/test/scala/fi/oph/koski/tools/AddIgnoreKoskiValidatorFlag.scala
- src/test/scala/fi/oph/koski/versioning/BackwardCompatibilitySpec.scala
Tällöin flägättyjä opiskeluoikeuksia ei yritetä validoida KoskiValidaattorin validaatiosääntöjä vasten.
> BackwardCompatibility jsoneihin voi lisätä ignoreKoskiValidator flagin.

- src/main/scala/fi/oph/koski/raportit/AmmatillinenTutkintoRaportti.scala
"Ammatillisen koulutuksen suoritustietoraportti laskee nyt suoritetuksi sellaisenkin yhteisen tutkinnon osan, jolla ei ole arviointia. Pitää korjata niin, että laskee suoritetuksi vain sellaiset yhteiset tutkinnon osat, joilla on arviointi. "
> TOR-1012 Korjaa valmiiden yhteisten tutkinnon osien laskeminen

- pom.xml
Alkuperäisen scalastylen ylläpitäjät ovat kadonneet, joten piti vaihtaa uuteen fork:iin, jonka kehitys jatkuu, ja joka osaa parsia esim. scala-koodia, jossa käytetty trailing comma:a.
Historiaa: https://github.com/scalastyle/scalastyle/issues/327#issuecomment-570951273
Uuden forkin websivu: https://scalastyle.beautiful-scala.com/
Uutta scalastyle-maven-pluginia forkin tekijä ei ole tehnyt, siksi piti muuttaa riippuvuus käsin pom.xml:ssä.
> Käytä uusinta scalastyle-pluginia ja scalastyleä

- web/app/uusioppija/UusiOppija.jsx
Button-elementti on oletuksena submit-tyyppinen, eli lähettää formin sivuvaikutuksena. Formin lähetys katkaisee Firefoxissa fetch-pyynnöt (Firefox toimii tiukemmin speksin mukaan kuin muut selaimet). Tällöin vaihtelevasti pyyntö joko jää palvelimella kesken, ja uutta oppijaa ei luoda, tai selain ei vastaanota palvelimen vastausta, jolloin oppija on luotu, mutta käyttöliittymä joutuu virhetilaan eikä näytä luotua oppijaa.
Korjataan muuttamalla nappi button-tyyppiseksi, jolloin formia ei lähetetä ja Bacon saa rauhassa tehdä työnsä. Muutos poistaa käytöstä formin lähettämisen enter-nappia painamalla. Tämä ei tosin tähän mennessäkään ilmeisesti toiminut fokuksen ollessa dropdown-kentissä. 🤷
> Tor-1038 Uuden oppijan luonti epäonnistuu Firefoxilla

- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillisenTutkinnonOsittainenSuoritusSpec.scala
Mahdollistaa muutokset sisältävään opiskeluoikeuteen (kuoreen) vaikka sisältyvän
opiskeluoikeuden (pihvin) oppilaitos olisi muuttunut
> "Linkitys tehty"-validaatio tarkistaa vain opiskeluoikeus oidin

- src/main/resources/localization/default-texts.json
- src/main/scala/fi/oph/koski/schema/Esiopetus.scala
- src/main/scala/fi/oph/koski/schema/NuortenPerusopetus.scala
- src/main/scala/fi/oph/koski/schema/PerusopetuksenLisaopetus.scala
- web/test/spec/perusopetusSpec.js
Luultavasti laki muuttuu syksyllä, minkä jälkeen kentät voidaan ottaa käyttöön. Ennen sitä niihin datan tallentaminen on kuitenkin kiellettyä, mistä on viestitty myös koulujärjestelmien
kehittäjille.
Pitäisikö lisätä validointi, joka estää uusiin kenttiin tietojen tallentamisen kokonaan? Vastaus: ei lisätä
> tor-902 piilota uudet kentät toistaiseksi

- src/main/scala/fi/oph/koski/schema/NuortenPerusopetus.scala
- src/main/scala/fi/oph/koski/schema/PerusopetuksenLisaopetus.scala
Ilman @Hidden annotaatiota ne tulevat muuten aina näkyviin, vaikka
ovatkin merkitty @Deprecated-annotaatiolla.
> TOR-902 Piilota erityisopiskelun boolean-kentät käyttöliittymästä

- pom.xml
- src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala
- src/main/scala/fi/oph/koski/http/Http.scala
- src/main/scala/fi/oph/koski/huoltaja/HuollettavatRepository.scala
- src/main/scala/fi/oph/koski/sso/CasServlet.scala
- src/main/scala/fi/oph/koski/ytr/YtrClient.scala
- src/test/scala/fi/oph/koski/henkilo/OppijanumeroRekisteriClientSpec.scala
- src/test/scala/fi/oph/koski/localization/EPerusteetLocalizationTest.scala
scala-cas_2.12:n riippuvuus on päivitetty 0.16.6 => 0.16.6a (https://github.com/Opetushallitus/scala-utils/blob/master/scala-cas_2.12/pom.xml#L42) , tee sama päivitys myös Koskessa. 
Tämä näyttäisi alustavien testien perusteella korjaavan raportointikanta-app:n timeoutteja, mutta selviää oikeasti vasta pidempään testattuna.
> TOR-1073: Ota käyttöön uudempi patch-versio http4s:stä

- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/fi/oph/koski/documentation/DocumentationServlet.scala
- src/main/scala/fi/oph/koski/healthcheck/HealthCheckHtmlServlet.scala
- src/main/scala/fi/oph/koski/koskiuser/LogoutServlet.scala
- src/main/scala/fi/oph/koski/mydata/MyDataReactServlet.scala
- src/main/scala/fi/oph/koski/omattiedot/OmatTiedotHtmlServlet.scala
- src/main/scala/fi/oph/koski/pulssi/PulssiHtmlServlet.scala
- src/main/scala/fi/oph/koski/servlet/EiSuorituksiaServlet.scala
- src/main/scala/fi/oph/koski/servlet/HtmlServlet.scala
- src/main/scala/fi/oph/koski/servlet/IndexServlet.scala
- src/main/scala/fi/oph/koski/servlet/OmaOpintopolkuSupport.scala
- src/main/scala/fi/oph/koski/servlet/OppijaHtmlServlet.scala
- src/main/scala/fi/oph/koski/servlet/OppijaLoginPageServlet.scala
- src/main/scala/fi/oph/koski/servlet/SuoritusjakoHtmlServlet.scala
- src/main/scala/fi/oph/koski/servlet/VirhesivuServlet.scala
- src/main/scala/fi/oph/koski/servlet/VirkailijaHtmlServlet.scala
- src/main/scala/fi/oph/koski/servlet/VirkailijaLoginPageServlet.scala
- src/main/scala/fi/oph/koski/sso/CasServlet.scala
- src/main/scala/fi/oph/koski/suoritusote/SuoritusServlet.scala
- src/main/scala/fi/oph/koski/todistus/TodistusServlet.scala
- src/main/scala/fi/oph/koski/ytr/YtrKoesuoritusServlet.scala
Aiemmin virkailija-raamit päälle asettava X-Raamit header on asetettu HAProxy:ssä, mitä ei enää AWS-ympäristössä ole käytössä.
> WIP: TOR-1088: Näytä virkailija-raamit aina paitsi lokaalissa kehityksessä

- owasp-dependency-check-suppressions.xml
- pom.xml
- src/main/resources/log4j.properties
Toisin kuin koodissa oletetaan, org.apache.log4j.rolling.RollingFileAppender on meillä käytössä vielä testiympäristössä. 
Palauta riippuvuus ja suppressoi riippuvuuden tietoturvailmoitus myös apache-log4j-extras osalta samalla perusteella kuin se on suppressoitu jo log4j:n osalta.
> TOR-xxxx: Korjaa dev-ympäristön logitus

- src/main/scala/fi/oph/koski/kela/KelaOppijaConverter.scala
- src/main/scala/fi/oph/koski/kela/KelaSchema.scala
OsaamisenTunnistaminen-rakennetta oli käytetty Kosken alkuperäisestä skeemasta (virhe) ja tämä sisälsi kentän jonka tyyppi oli Suoritus. Kelan skeemassa oli myös määritelty Suoritus niminen tyyppi, tosin eri packageen. Tämä nimien yhteentörmäys aiheutti bugin jossa json-schema-vieweria ei voinut avata kelan skeemalla.
> tor-780: korjaa rikkinäinen kelan json-schema-viewer

- web/app/i18n/i18n.js
- web/app/kela/KelaOsasuorituksetTable.jsx
- web/test/spec/kelaSpec.js
- jos LocalizedString sisältää vain englanninkielisen käännöksen, näytetään englanninkielinen käännös vaikka valittu kieli olisi joku muu
- bugfix: näytä suorituksen nimessä suoritettu kieli jos kyseessä on kieliaine ja oppimäärän nimi jos suoritus sisältää oppimäärän
> tor-780: Kela UI korjauksia

- src/main/scala/fi/oph/koski/raportit/EsiopetuksenOppijamäärätRaportti.scala
- src/main/scala/fi/oph/koski/raportit/EsiopetusRaportti.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
Jotta kaikki dataa hyödyntävät järjestelmät osaavat ladata taulun.
Raportointikannan hajottava muutos. Vietäessä tuotantoon voidaan tilanne korjata ajamalla manuaalisesti 
ALTER TABLE esiopetus_opiskeluoikeus_aikajakso RENAME TO esiopetus_opiskeluoik_aikajakso;
> Lyhennetään taulun nimi alle 32 merkkiseksi

- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
Indeksejä voisi katsoa uudestaan tarkemmin kun ollaan toteutettu jatkuvasti lataava raportointikanta, jolloin indeksien statistiikka oikeasti kertookin jotain.
`VACUUM ANALYSE` voi potentiaalisesti parantaa kyselyjen suorituskykyä reilustikin. Sen ajamisessa kestää noin 20 minuuttia, mutta kantaa voi periaatteessa käyttää samalla, joskin se voi olla hidas.
> Raportointikannan huoltoa

- src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusQueryService.scala
- src/main/scala/fi/oph/koski/util/Retry.scala
Opiskeluoikeuksien lataus sivuittain saattaa välillä epäonnistua ja
epäonnistuminen johtaa koko raportointikannan latauksen keskeytymiseen
> Raportointikannan lataus ei lopu ekaan virheeseen

- src/main/scala/fi/oph/koski/log/MaskedSlf4jRequestLogWriter.scala
- src/test/scala/fi/oph/koski/kela/KelaSpec.scala
Näin on ollut tapana tehdä Koskessa. Ylimääräinen \d regexpissä, koska on myös route kela/versiohistoria/... , jota ei tarvitse maskata.
> TOR-1144: Maskaa kela-URLeista hetu access-lokeissa

- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
`\\`-selector palauttaa kaikki matchaavat xml-rakenteet, childit + grandchildit.., tästä syystä opintojakson arviointien nimet valittiin myös mukaan opintojakson nimen päättelyyn. Suuressa osassa tapauksia tämä virhe piiloutui, koska arviointien `Nimi`-rakenteilla ei ole `kieli`-propertyä, suorituksen `Nimi`-rakenteella se on. Mutta tapauksessa jossa, suorituksen `Nimi`-rakenteella ei ole suomenkielistä käännöstä, valittiin virheellisesti suomenkieliseksi käännökseksi arvioinnin `Nimi`-rakenteesta löytyvä arvo.
Korjaus: käytetään selectoria joka palauttaa vain `Opintosuoritus`-rakenteen alta suoraan löytyvät `Nimi`-rakenteet
`\`-selector palauttaa vain annetun noden childit, ei grandchildeja
> Korjaa virta opintojakson nimen päättely;

- src/main/scala/fi/oph/koski/henkilo/HenkiloRepository.scala
- src/main/scala/fi/oph/koski/henkilo/HenkilotiedotSearchFacade.scala
- src/main/scala/fi/oph/koski/henkilo/OpintopolkuHenkiloRepository.scala
Jos linkitetyllä oppijalla on vain yksi opiskeluoikeus joka, on siirretty passivoidulla oppijanumerolla, nimihaku ei löytänyt tälläistä henkilöä,
koska elasticsearchin haku palautti aina oppijan uusimman oidin, ja tällä haettaessa kosken kannasta ei löydy yhtään opiskeluoikeutta.
Ongelma ratkaistiin käyttämällä oppijanumerorekisteristä rajapintaa, mikä palauttaa aina kaikki oppijan oidit
> Korjaa nimihaku linkiteyille oppijoille

- src/main/scala/fi/oph/koski/raportit/LukioOppiaineRahoitusmuodonMukaan.scala
- src/main/scala/fi/oph/koski/raportit/LukioOppiaineenOppimaaranKurssikertymat.scala
- src/main/scala/fi/oph/koski/raportit/LukioOppimaaranKussikertymat.scala
- src/test/scala/fi/oph/koski/raportit/LukioKurssikertymaRaporttiSpec.scala
* Oppimäärä välilehti: Sarakkeen "Kursseja yhteensä" pitäisi olla ennen sarakkeita "Suoritetut kurssit" ja "Tunnustetut kurssit"
* Nykyinen kysely tarkistaa, että opiskeluoikeus, joista kursseja lasketaan on ollut "Läsnä"-tilainen päivänkin sinä tulostusparametreissa määriteltynä päivänä. Se on ihan turha tsekkaus, eli pitäisi etsiä vain osasuorituksia, joiden arviointipäivä osuu sen aikajakson väliin, mikä on tulostusparametreissa määritelty.
* Sama korjaus muidenkin välilehtien kyselyille.
> TOR-1000: Lukion kurssikertymäraportin korjaukset

- src/main/scala/fi/oph/koski/raportit/LukioOppiaineOpiskeluoikeudenUlkopuoliset.scala
- src/main/scala/fi/oph/koski/raportit/LukioOppiaineRahoitusmuodonMukaan.scala
- src/main/scala/fi/oph/koski/raportit/LukioOppiaineenOppimaaranKurssikertymat.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
- src/test/scala/fi/oph/koski/raportit/LukioKurssikertymaRaporttiSpec.scala
- web/app/raportit/Raportit.jsx
* Korjaus: Lasketaan kurssimääriin mukaan myös sellaiset suoritukset, jotka eivät joinaannu opiskeluoikeuden aikajaksoon.
* Korjaus: Opiskeluoikeuden ulkopuolisten suoritusten rajaamisesta puuttui ehto *"suoritettu tai tunnustettuja ja rahoituksen piirissä oleva"*
* Korjaus: Muuta kautta rahoitetut ja Ei rahoitusmuotoa -välilehdet näyttivät merkillisiä tuloksia. Korjattu logiikka vastaamaan Aineopiskelijat-välilehden logiikkaa.
* Lisätty indeksejä performanssia parantamaan. Korjaa timeoutien aiheuttamia error 500 -herjoja.
* Lisätty oppijan oid kolmelle viimeiselle välilehdelle.
> TOR-1000: Kyselyiden korjailua ja performanssiparannus

- src/main/scala/fi/oph/koski/raportit/LukioOppiaineOpiskeluoikeudenUlkopuoliset.scala
- src/main/scala/fi/oph/koski/raportit/LukioOppiaineenOppimaaranKurssikertymat.scala
- src/main/scala/fi/oph/koski/raportit/LukioOppimaaranKussikertymat.scala
- src/main/scala/fi/oph/koski/raportit/PaallekkaisetOpiskeluoikeudet.scala
- src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeudenUlkopuolellaArvioidutOsasuoritukset.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
Kurssikertymien laskenta lennosta todettiin liian hitaaksi.
`lukion_oppiaineen_oppimaaran_kurssikertyma` view:n luonti tämän hetkisellä datamäärällä ~6min
Oppilaitoksella kaikista arviointipäivistä 10% pitää sisällään 70% kaikista kurssiesta. Joten data voidaan pakata suhteellisen tehokkaasti. (Todennettu oppilaitoksella jolla on eniten aineopiskelijoita Helsingissä)
`osasuoritus_arvioitu_opiskeluoikeuden_ulkopuolella ` view:n luonti tämän hetkisellä datamäärällä ~9min
`lukion_oppimaaran_kurssikertyma ` view:n luonti tämän hetkisellä datamäärällä ~30min
> Esilaske kurssikertymat lukion aineopiskelijoille

- src/main/scala/fi/oph/koski/raportit/aikuistenperusopetus/AikuistenPerusopetuksenAineopiskelijoidenKurssikertymät.scala
pieni korjaus aineopintojen queryyn; ei katsota 'valmistunut' tilaa kuin jos suorituksen arviointipäivämäärä on opiskeluoikeuden loppupäivän jälkeen
> Tor-999 - aikuisten perusopetuksen raportti 2 - kurssikertymät - minikorjaus

- src/main/scala/fi/oph/koski/healthcheck/HealthCheckApiServlet.scala
- src/main/scala/fi/oph/koski/healthcheck/HealthCheckHtmlServlet.scala
- src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala
Kosken alkuperäinen healthcheck on riippuvainen taustajärjestelmien tilasta.
AWS:ssä tämä aiheuttaa mm. sen, että taustajärjestelmän ollessa alhaalla dockerissa ajettava Koski terminoitaisiin.
> healthcheck joka tarkistaa vain Kosken yhteyden omaan tietokantaansa

- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/fi/oph/koski/config/KoskiApplication.scala
- src/main/scala/fi/oph/koski/config/RunMode.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
Jos ympäristömuuttuja on GENERATE_RAPORTOINTIKANTA=true, Koski-sovellus käynnistyessään menee erikoistilaan, jossa servlettejä ei mountata, raportointikannan generointi lähtee heti käyntiin ja sovellus sammuu sen päätyttyä.
> TOR-1210: Kosken ajaminen pelkkää raportointikannan generointia varten

- src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogMockData.scala
- src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogService.scala
- src/main/scala/fi/oph/koski/organisaatio/Opetushallitus.scala
- src/test/scala/fi/oph/koski/omaopintopolkuloki/OmaOpintoPolkuLokiServlet.scala
Kosken käyttämä organisaatio-cache ei sisällä Opetushallitusta, koska organisaatiopalvelusta käytettävä rajapinta palauttaa annetulle oidille kaikki hierarkiassa alempana olevat organisaatiot. Opetushallitus on organisaatiohierarkian ylin.
Tämä aiheutti ongelman AuditLogien organisaatioiden nimen näyttämisessä, jos katselija on kuulunut Opetushallitukseen.
> Korjaa auditlog-api jos katselijan organisaatio on OPH;

- src/main/scala/fi/oph/koski/documentation/ExamplesLukio2019.scala
- src/main/scala/fi/oph/koski/schema/Koulutusmoduuli.scala
- src/main/scala/fi/oph/koski/schema/Lukio2019.scala
- src/main/scala/fi/oph/koski/schema/VapaaSivistystyö.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationLukio2019Spec.scala
- validaation_muutoshistoria.md
- web/test/spec/omatTiedotLukioSpec.js
Aiemmin laajuudet ensimmäiselle osasuoritustasolle laskettiin ainoastaan oppinaineille, joissa oli osasuorituksia. Nyt laajuudet
tyhjennetään, jos osasuorituksia ei ole, ja lasketaan myös lukion muissa suorituksissa.
> TOR-1203 Korjaa lops2021 laajuuksien yhteenlaskenta validaatioissa

- src/main/scala/fi/oph/koski/schema/DIA.scala
Tämä on skeeman rikkova muutos, mutta kyseisellä koodiarvolla ei pitäisi olla siirretty suorituksia väärään paikkaan
> DIA lisää sallittu koodiarvo VT

- src/main/scala/fi/oph/koski/elasticsearch/ElasticSearchIndex.scala
- src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotIndexer.scala
- src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala
Vaatii, että indeksit on aiemmin reindeksoitu uusiin indekseihin _doc tyypille.
> Älä käytä mapping typeä ES-kutsuissa

- web/app/uusioppija/UusiEsiopetuksenSuoritus.jsx
- web/app/uusioppija/UusiOpiskeluoikeus.jsx
- web/app/uusioppija/esiopetuksenSuoritus.js
Ongelmia paratiisissa: https://jira.eduuni.fi/browse/TOR-1286
Uusi eperuste-rakenne ei toimi ollenkaan johtuen eperuste-palvelussa olevasta viasta.
Mutta tämä uusi peruste on joka tapauksessa harvinaisempi käyttötapaus kuin tämä vanhempi peruste. Käytetään vanhempaa perustetta defaulttina.
Nyt tässä vaiheessa tehdään ylipäätään mahdolliseksi valita peruste esiopetus-kälissä.
> TOR-1248 - step 1 - Mahdollistetu perusteen valinta esiopetuksen opiskeluoikeutta luotaessa

- src/main/scala/fi/oph/koski/henkilo/MockOppijat.scala
- src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
- src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
- src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
Lisätty ainoastaan puuttunut testi, koska sen perusteella oppijatietojen haku näyttäisi toimivan oikein.
> TOR-1267: Testi kahden oppija-oidin oppijalle

- src/main/scala/fi/oph/koski/fixture/Fixtures.scala
- src/main/scala/fi/oph/koski/valpas/ValpasTestApiServlet.scala
- src/main/scala/fi/oph/koski/valpas/fixture/FixtureUtil.scala
- src/main/scala/fi/oph/koski/valpas/repository/Rajapaivat.scala
- valpas-web/devserver/server.js
- valpas-web/src/api/apiHooks.ts
- valpas-web/src/api/testApi.ts
- valpas-web/src/components/navigation/LocalRaamit.less
- valpas-web/src/components/navigation/LocalRaamit.tsx
- valpas-web/test/integrationtests-env/browser.ts
Huom: Rebasettu tällä hetkellä tor-1268_virheenkäsittely päälle.
Muutos: Fikstuureja ei enää ladata, jos backendissa on jo Valpas-fikstuurit sisällä tai tarkastelupäivä ei ole muuttunut sitten viime testin. Tämä muutos ei ota huomioon sitä, että fikstuurin päälle on tehty muutoksia tilaan, mutta koska sellaisia apeja ei muutenkaan vielä ole, tämän ongelman ratkaisu on työnnetty tulevaisuuteen.
Mahdollisia ratkaisuja: 
* muutoksia tekevät testit itse alustavat fikstuurit takaisin alkutilaan (ongelma: jos unohtuu tehdä, muut testit hajoavat --> voi tulla turhaa selvittelytyötä)
* merkataan fikstuurin tila likaiseksi, kun kutsutaan tilaa muuttavaa apia (ongelma: testi- ja tuotantokoodi sekoittuvat keskenään)
Lisätty myös devserverille PARCEL_CACHE -ympäristömuuttuja, jonka avulla saa …
> TOR-1267: Nopeuta integraatiotestien alustusta

- src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotIndexer.scala
- src/main/scala/fi/oph/koski/perustiedot/PerustiedotSyncRepository.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
- src/main/scala/fi/oph/koski/util/DateOrdering.scala
Jos samalle opiskeluoikeudelle tuli kaksi päivitystä jonoon, uudempi päivitys käsiteltiin ennen vanhempaa ja myöhemmin vanhempi ylikirjoitti uudemman päivityksen.
Jatkossa aina vanhin olemassa oleva päivitys käsitellään ensimmäisenä.
> Korjaa perustiedot-indexin päivitys;

- pom.xml
- src/main/resources/localization/koski-default-texts.json
- src/main/resources/mockdata/virta/opintotiedot/250668-293Y.xml
- src/main/resources/mockdata/virta/opintotiedot/270191-4208.xml
- src/main/scala/fi/oph/koski/omattiedot/OmatTiedotEditorModel.scala
- src/main/scala/fi/oph/koski/schema/Korkeakoulu.scala
- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
- src/test/scala/fi/oph/koski/api/KorkeakouluSpec.scala
- src/test/scala/fi/oph/koski/api/OpiskeluoikeusTestMethodsKorkeakoulu.scala
- src/test/scala/fi/oph/koski/api/SuoritusjakoSpec.scala
- src/test/scala/fi/oph/koski/virta/VirtaXMLConverterSpec.scala
- web/app/suoritus/Koulutusmoduuli.js
- web/app/suoritus/Suoritus.js
VIRTA-lukukausimaksutietoja lisätty kahdelle oppijalle Virta-mockdatoihin.
VIRTA-datasta poimitaan lukukausimaksutiedot, tulevat opiskeluoikeuden lisätietojen alle.
> TOR-1243 - VIRTA-lukukausimaksutiedot Koski-palveluun

- src/main/resources/valpas/localization/valpas-default-texts.json
- src/main/scala/fi/oph/koski/valpas/fixture/ValpasDatabaseFixtureCreator.scala
- src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
- src/main/scala/fi/oph/koski/valpas/hakukooste/MockHakukoosteService.scala
- src/main/scala/fi/oph/koski/valpas/henkilo/ValpasMockOppijat.scala
- src/test/scala/fi/oph/koski/valpas/ValpasOppijaServiceSpec.scala
- valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
- valpas-web/src/views/oppija/OppijaView.tsx
- valpas-web/src/views/oppija/OppijanYhteystiedot.tsx
- valpas-web/test/integrationtests/oppija.test.ts
- valpas-web/test/integrationtests/perusopetus.test.ts
Yhteystietojen näyttäminen olikin korjattu jo aiemmin. Tässä korjaus lähinnä useamman haun näyttämiseen taulukossa ja pientä siistimistä.
Lisäksi tyylikorjaukset jotka menivät jo masteriin:
0479cf15580facd8ca6cbbcee310ae4d5ee63274
52ab41a26abb85e2814ab73b976711bda3c8d7d6
> Valpas UI-korjauksia

- src/main/scala/fi/oph/koski/cloudwatch/CloudWatchMetrics.scala
- src/main/scala/fi/oph/koski/valpas/valpasuser/ValpasSession.scala
- valpas-web/src/components/icons/Spinner.less
- valpas-web/src/components/icons/Spinner.tsx
- valpas-web/src/components/navigation/LocalRaamit.less
- valpas-web/src/state/auth.ts
- valpas-web/src/style/zindex.less
- valpas-web/src/views/VirkailijaApp.tsx
* Robustimpi login-uudelleenohjaus, aiemmassa toteutuksessa saattoi olla blankkoon sivuun johtava tai siihen myötävaikuttava bugi
* On myös mahdollista että virkailija-raamien lataus index.html:ssä aiheuttaa omalta osaltaan tätä ongelmaa. Raamien lataaminen kirjautumatta saattaa aiheuttaa uudelleenohjauksen kirjautumiseen väärällä paluuosoitteella, mutta tästä en ole vielä varma. Aiemmin virkailijan raamit ladattiin vasta kirjautumisen jälkeen - miksikäs tämä muutos olikaan revertoitu?
* Käyttöoikeuksien lataamisessa untuvalla kestää useitakin sekunteja: lisätty spinneri (modaali) myös tähän vaiheeseen, jotta ei sekoiteta tyhjän sivun bugia tyhjältä näyttävään mutta latautuvaan sivuun
> Valpas login fiksausta

- valpas-web/package.json
- valpas-web/src/components/icons/Spinner.less
- valpas-web/src/index.html
- valpas-web/src/state/auth.ts
- valpas-web/src/views/Raamit.tsx
- valpas-web/src/views/VirkailijaApp.tsx
* Vahva hypoteesi: virkailija-raamien lataaminen kirjautumatta johtaa epädeterministiseen käyttäytymiseen: jos raamit ehtii ohjata kirjautumissivulle ennen kuin Valpas ehtii, on kirjautumisen paluuosoite väärä (virkailijan työpöydälle)
* Tehty aiemmin revertoitu uudelleenohjauskäsittely paremmin - nyt pitäisi toimia myös CAS:n kanssa
> Valpas login fix 2

- src/main/resources/valpas/localization/valpas-default-texts.json
- valpas-web/src/views/hakutilanne/HakutilanneView.tsx
- valpas-web/test/integrationtests/hakutilanne.test.ts
Sama näkymä tulee olemaan muillakin kuin peruskoululla ja lisäksi vuosiluvun näyttäminen otsikossa hajoaa syksyllä.
> TOR-1335 Vaihda hakutilannenäkymän otsikko paremmaksi

- src/main/resources/mockdata/koodisto/koodistot/hakutapa.json
- src/main/resources/mockdata/koodisto/koodistot/hakutyyppi.json
- src/main/resources/mockdata/koodisto/koodit/hakutapa.json
- src/main/resources/mockdata/koodisto/koodit/hakutyyppi.json
- src/main/scala/fi/oph/koski/koodisto/Koodistot.scala
- src/main/scala/fi/oph/koski/valpas/hakukooste/Hakukooste.scala
- src/main/scala/fi/oph/koski/valpas/hakukooste/HakukoosteExampleData.scala
- src/main/scala/fi/oph/koski/valpas/repository/ValpasOppija.scala
- valpas-web/src/components/typography/NoDataMessage.less
- valpas-web/src/state/oppijat.ts
- valpas-web/src/views/oppija/OppijanHaut.tsx
- valpas-web/test/integrationtests/oppija.test.ts
* Pisteet kuntoon
* Oppijanäkymän hakutilannekenttä tilaan "ei toteutettu"
* Hakutapa- ja hakutyyppi-koodistot Koskeen
* Harkinnanvaraisuus-kentän tila "dokumentoitu" koodilla
* hakukohdeKoulutuskoodi piiloon väliaikaisesti, ettei tyypin muuttuminen lähiaikoina riko parsintaa
> TOR-1335 Hakukoosteen korjaussarja

- valpas-web/src/components/icons/Icon.tsx
- valpas-web/src/components/tables/Table.less
- valpas-web/test/snapshots/components/containers/Accordion.test.tsx.snap
- valpas-web/test/snapshots/components/tables/DataTable.test.tsx.snap
Chromessa näkyi ikonin sijaan **vierityspalkki**. Korjataan asettamalla molemmat `overflow`:t `hidden`. Olikohan pelkän `overflow-y`:n käyttöön jokin syy tässä?
Laitetaan ikonit semanttisesti oikeampaan `span`-elementtiin `i`-elementin sijaan.
> Valpas taulukon järjestysikonin korjaus Chromessa

- src/main/resources/localization/koski-default-texts.json
- src/main/resources/mockdata/koodisto/koodit/suorituksentyyppi.json
- src/main/scala/fi/oph/koski/documentation/ExamplesLukioonValmistavaKoulutus.scala
- src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
- src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
- src/main/scala/fi/oph/koski/schema/Lukio2019.scala
- src/main/scala/fi/oph/koski/schema/LukioonValmistavaKoulutus.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/main/scala/fi/oph/koski/validation/LukioonValmistavanKoulutuksenValidaatiot.scala
- src/test/resources/backwardcompatibility/lukioonvalmistavakoulutus,Lukion2019-opsilla_2021-04-09.json
- src/test/scala/fi/oph/koski/api/OppijaValidationLukioonValmistavaSpec.scala
Aikaisemmin Luva-opinnoissa (Lukioon Valmistava) on toteutettu tuki lukion oppiaineiden opintojen suorituksille siten, että siellä on ollut kopioituna suoraan sama rakenne kuin lukionkin puolella.
Nyt kopioitu myös 2019 opsin mukainen rakenne Luvalle.
Lukio2019:n rakenteissa sallitaan oppiaineiden suoritustyyppinä myös luva2019-oppiaineopinnot.
Sen lisäksi tehty validaatio; Luva-suorituksella ei voi olla sekä lukion 2015 että lukion 2019 opsien mukaisia suorituksia.
> TOR-1132 LOPS 2012 Luva-opinnoissa

- src/main/resources/reference.conf
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OpiskeluoikeusValidationSpec.scala
Tämä voi olla hyödyllinen, kun tietomallia toteutaan vähitellen osasuoritusten osalta. Päätason suorituksille tällainen esto on jo toteutettu aiemmin.
Tälle vaikutti tulevan käyttöä Pre IB + Lops2021 -yhdistelmän kanssa, mutta ei sitten vielä tarvittukaan.
Haluttaisiinko tämä ominaisuus lisätä kuitenkin jo nyt tulevaisuutta ajatellen, vai jätetäänkö hautumaan?
> TOR-xxxx: Lisää mekanismi osasuoritustyyppien tallennuksen disablointiin

- src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
- valpas-web/src/state/oppijat.ts
- valpas-web/src/views/oppija/OppijanHaut.tsx
- valpas-web/test/integrationtests/login.test.ts
Nyt viimeisenä muokattu haku näytetään aina ylimpänä, aiemmin järjestys oli satunnainen eli riippui hakukoostepalvelun palauttamasta järjestyksestä.
> TOR-1335 Järjestä haut Valppaan detaljinäkymässä käänteiseen muokkausjärjestykseen

- src/main/scala/fi/oph/koski/documentation/ExamplesVapaaSivistystyö.scala
- src/main/scala/fi/oph/koski/schema/VapaaSivistystyö.scala
- src/main/scala/fi/oph/koski/schema/VapaanSivistystyönLukutaitokoulutus.scala
- src/test/resources/backwardcompatibility/vapaasivistystyo-lukutaitokoulutus_2021-04-16.json
- src/test/resources/backwardcompatibility/vapaasivistystyo-maahanmuuttajienkotoutuskoulutus_2021-04-16.json
"Suoritettu"-arviointi ei käynytkään, käytetään samaa "Hyväksytty/Hylätty"-arviontirakennetta kuin muukin VST.
> VST: KOTO- ja Lukutaito -koulutusten arviointiasteikon korjaus

- src/main/scala/fi/oph/koski/schema/NuortenPerusopetus.scala
- src/main/scala/fi/oph/koski/schema/OpiskeluoikeudenLisatiedot.scala
- src/main/scala/fi/oph/koski/schema/PerusopetuksenLisaopetus.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationPerusopetusSpec.scala
Laajuutta ei vaadita jos:
- Opiskeluoikeudella on voimassa kotiopetus jakso vuosiluokan tai päättötodistuksen vahvistuspäivänä
- Vuosiluokan tai päättötodistuksen suoritustapa on `erityinentutkinto`
- Oppiaineen suoritustapa on `erityinentutkinto`
> Perusopetuksen pakollisilta oppiaineilta ei aina vaadita laajuutta

- src/main/resources/valpas/localization/valpas-default-texts.json
- src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
- valpas-web/src/components/forms/Dropdown.tsx
- valpas-web/src/components/tables/DataTable.tsx
- valpas-web/src/components/tables/DataTableFilter.tsx
- valpas-web/src/state/apitypes/haku.ts
- valpas-web/src/state/useSessionStoreState.ts
- valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
- valpas-web/src/views/hakutilanne/HakutilanneView.tsx
- valpas-web/src/views/oppija/OppijaView.tsx
- kun tehdään valinta suodatuksessa, pitäisi näkyä selkeästi ”kaikki”  eikä tyhjä, esim. ryhmästä 9a -> selkeästi valikossa ”kaikki”
- parempi nimi: muut oppijat -> takaisin
- hakemuksiin listanäkymässä lisätietoa: hakemusta on muokattu,  tuodaan päivämäärä koska viimeksi muokattu (hover / tooltip tms.),  tietona missä haussa on hakenut (hover / tooltip tms.)
- jos valitsee vain yhden ysin ryhmän/luokan tarkasteluun, esim. 9A,  niin nopeuttaisi tarkistusta, mikäli yhden ryhmän kokonaislukumäärä  olisi nopeasti nähtävillä. Tällä hetkellä näyttää vain kaikkien ysien  kokonaislukumäärän. Tämä on tärkeää varsinkin, jos ryhmät on jaettu eri  opojen vastuulle.- suodatetut lukumäärä / oppivelvollisten  kokonaislukumäärä
- filttereiden tilat pysyvät tallessa, kun käydään detskunäkymässä
> TOR-1352: Opo-pilotin palautetyöpajasta nousseet havainnot

- src/main/scala/fi/oph/koski/schema/OpiskeluoikeudenLisatiedot.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationPerusopetusSpec.scala
kotiopetus-kenttä on deprekoitu, mutta tätä tulee tukea jatkossakin
kotiopetusjaksot-kenttää ei otettu huomioon validaatiossa, tämä on nyt lisätty
> kotiopetusjaksot huomioon validaatiossa

- src/main/resources/valpas/localization/valpas-default-texts.json
- valpas-web/src/components/buttons/ToggleSwitch.less
- valpas-web/src/components/buttons/ToggleSwitch.tsx
- valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
- valpas-web/test/integrationtests/hakutilanne.test.ts
Huom! Sarakkeelle lisätty tooltip asemoituu väärin (menee ruudun ulkopuolelle), mutta tämä bugi korjautuu pullarissa https://github.com/Opetushallitus/koski/pull/1341 olevan korjauksen myötä.
> TOR-1362: Näytä esimerkinomaiset muu haku -valitsimet taulussa, jos ilmoittaminen-featureflag on päällä

- valpas-web/src/components/tables/DataTable.tsx
- valpas-web/src/components/tables/Table.less
- valpas-web/src/components/tables/Table.tsx
- valpas-web/src/views/hakutilanne/HakutilanneTable.tsx
- valpas-web/test/snapshots/components/tables/DataTable.test.tsx.snap
* Kolmella pisteellä lyhennys toimii taas
* Jos ikkuna on alle 1600 pikseliä, ei yritetä ahtaa taulukkoa enää laatikon sisään, vaan se saa olla niin leveä kuin tarve on ja laatikko sen ympärillä muuttuu vaakatasossa skrollattavaksi﻿
* Otsikkorivit on siivottu ja nyt järjestysindikaattori on aina tekstin vieressä (meni ennen joskus uudelle riville)
* Tooltip-nappi on nyt aina solun oikeassa reunassa
> TOR-1228: Taulukon parempi responsiivisuus

- src/main/scala/fi/oph/koski/config/SecretsManager.scala
- src/main/scala/fi/oph/koski/db/DatabaseConfig.scala
- src/main/scala/fi/oph/koski/valpas/hakukooste/SureHakukoosteService.scala
Käytetään kannan nimeä konffitiedostosta eikä aws:n salaisuudesta
> Tor-1229 valpas kantakonffin korjaus

- src/main/scala/fi/oph/koski/oppija/OppijaServlet.scala
- src/main/scala/fi/oph/koski/oppija/OppijaServletV2.scala
- src/main/scala/fi/oph/koski/oppivelvollisuustieto/Oppivelvollisuustiedot.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
Kyselyyn noin 20-40x nopeutus riippuen välimuistien tilasta, ja noin 10x pienempi IO-kuorma (buffer hitteinä mitattuna).
Ilman näitä indeksejä pg12 on noin 2x nopeampi (2x pienemmällä IO-kuormalla) kuin pg10, mutta indeksien kanssa eroa ei käytännössä ole, joten suurta painetta postgres-version päivitykseen ei tästä vielä tule. Tosin käytännön suorituskyky perffitestikuormalla on vielä testattava (merkittävästi pienempi IO-kuorma kyllä enteilee hyvää myös siltä osin).
> Tor-1229 indeksejä valpas-kyselyjä varten

- src/main/scala/fi/oph/koski/db/DatabaseUtilQueries.scala
- src/main/scala/fi/oph/koski/elasticsearch/ElasticSearchIndex.scala
- src/main/scala/fi/oph/koski/healthcheck/HealthCheckApiServlet.scala
- src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala
- src/main/scala/fi/oph/koski/http/Http.scala
- src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotIndexer.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
Aiempi toteutus oli riippuvainen ulkoisesta oppijanumerorekisteristä.
> Sisäinen healthcheck tarkistaa vain kantayhteydet

- src/main/scala/fi/oph/koski/config/KoskiApplication.scala
- src/main/scala/fi/oph/koski/editor/EditorServlet.scala
- src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusServlet.scala
- src/main/scala/fi/oph/koski/preferences/PreferencesService.scala
- src/main/scala/fi/oph/koski/schema/KoskiSchema.scala
- src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoServlet.scala
- src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoServletV2.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/main/scala/fi/oph/koski/validation/ValidatingAndResolvingExtractor.scala
- src/main/scala/fi/oph/koski/valpas/ValpasKuntailmoitusApiServlet.scala
- src/main/scala/fi/oph/koski/valpas/ValpasOppijaService.scala
- src/main/scala/fi/oph/koski/valpas/hakukooste/SureHakukoosteService.scala
- src/main/scala/fi/oph/koski/valpas/valpasrepository/ValpasKuntailmoitusRepository.scala
- src/test/scala/fi/oph/koski/api/HistoryTestMethods.scala
- src/test/scala/fi/oph/koski/api/KäyttöoikeusryhmätSpec.scala
- src/test/scala/fi/oph/koski/api/OpiskeluoikeusTestMethods.scala
- src/test/scala/fi/oph/koski/api/PermissionCheckSpec.scala
- src/test/scala/fi/oph/koski/api/PutOpiskeluOikeusTestMethods.scala
- src/test/scala/fi/oph/koski/api/QueryTestMethods.scala
- src/test/scala/fi/oph/koski/api/SuoritusjakoV2Spec.scala
- src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala
- src/test/scala/fi/oph/koski/schema/ArviointiSpec.scala
- src/test/scala/fi/oph/koski/schema/KoskiOppijaExamplesValidationSpec.scala
- src/test/scala/fi/oph/koski/schema/SerializationSpec.scala
- src/test/scala/fi/oph/koski/sure/SureSpec.scala
- src/test/scala/fi/oph/koski/tools/AddIgnoreKoskiValidatorFlag.scala
- src/test/scala/fi/oph/koski/valpas/SureHakukoosteServiceSpec.scala
- src/test/scala/fi/oph/koski/versioning/BackwardCompatibilitySpec.scala
- src/test/scala/fi/oph/koski/ytr/YtrKoesuoritusApiSpec.scala
Muutokset Sure-API:n vastauksen validointiin aiheuttivat sen, ettei APIn palauttamia tyhjiä merkkijonoja ja "ylimääräisiä" (Valppaan tietomalliin kuulumattomia) kenttiä enää hyväksytty parsinnassa.
Varsinainen korjaus ongelmaan on viimeisimmässä commitissa ja regressiotesti sitä edellisessä. Korjauksen siisti toteutus vaati lisäksi isompaa refaktorointia parsintaan.
> Valpas Sure-API parsintakorjaus

- src/main/scala/fi/oph/koski/schema/VapaaSivistystyö.scala
- src/test/resources/backwardcompatibility/vapaasivistystyo-maahanmuuttajienkotoutuskoulutus_2021-06-10.json
- web/app/suoritus/SuoritustaulukkoCommon.jsx
- web/app/suoritus/suoritusEditorMapping.jsx
- web/app/vapaasivistystyo/UusiVapaanSivistystyonOsasuoritus.jsx
- web/app/vapaasivistystyo/VapaanSivistystyonSuoritustaulukko.jsx
- web/test/spec/vapaaSivistystyoSpec.js
Käytetään VST:n käliä myös maahanmuuttajien kotoutumiskoulutusta varten, valtaosa koodista on samaa.
Lisätty testi tarkistamaan, että uusi funktionaalisuus on oikein (kieliopiskelujen taitotasojen näyttäminen).
Fiksattu myös Koton kieliopintosuorituksen arvioinnin koodistotyyppi samaksi kuin muilla saman tason osasuorituksilla.
> vst-koto - käytetään vst-käyttöliittymäkoodia myös kotoutuskoulutukselle

- src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusIdentifier.scala
- src/main/scala/fi/oph/koski/opiskeluoikeus/PostgresOpiskeluoikeusRepository.scala
- web/test/spec/useampiSamanOppilaitoksenVoimassaOlevaOpintoOikeusSpec.js
Tiketti: https://jira.eduuni.fi/browse/TOR-797
Aikasemmin korjattu siten, että lisätty koulutusmoduulin tunniste identifioimaan opiskeluoikeus. Tämä ei kuitenkaan riitä, jos samaa tutkintoa on opiskeltu sekä osatutkinotavoitteisena että tutkintotavoitteisena.
Lisätty päätason suorituksen tyyppi opiskeluoikeuden erottavaksi tekijäksi.
> TOR-797 - Käytetään päätason suorituksen suoritustyyppiä identifioimaan opiskeluoikeus

- src/main/scala/fi/oph/koski/schema/DIA.scala
Koodiarvo oli sallittu kahteen eri oppiaineeseen jolloin schema ei osaa päätellä kummasta oppiaineesta on oikeasti kyse.
Koodiarvolla ei oltu siirretty yhtään suoritusta, joten voidaan poistaa koodiarvo väärästä paikasta.
> Korjaa DIA-oppiaine VT koodiarvolla;

- valpas-web/src/components/containers/BottomDrawer.tsx
- valpas-web/src/components/containers/cards.less
- valpas-web/src/components/containers/cards.tsx
- valpas-web/src/components/tables/Table.less
- valpas-web/src/state/useBoundingClientRect.tsx
- valpas-web/src/utils/plaincomponent.tsx
- valpas-web/src/views/hakutilanne/HakutilanneDrawer.tsx
- valpas-web/src/views/hakutilanne/HakutilanneView.tsx
- valpas-web/src/views/suorittaminen/oppivelvolliset/SuorittaminenOppivelvollisetView.tsx
Tämä korjaus estää taulukon kasvamisen pystysuunnassa mahdottomasti. Eli vaakavieritys palkki pysyy saatavilla nyt käyttäjille, jotka sitä tarvitsevat (esim. ei käytössä tai osata käyttää trackpad-vieritystä). Algoritmi yrittää löytää sopivan korkeuden taulukolle haarukoimalla muutamasta erilaisesta vaihtoehdosta.
Testattu Windows 10 Chromella ja Edgellä ja tuntuisi pelittävän.
> TOR-1402: Estä tilanne, jossa taulukon vaakavierityspalkki hukkuu liian pitkän taulukon takia

- src/main/resources/valpas/localization/valpas-default-texts.json
- src/main/scala/fi/oph/koski/valpas/ValpasErrorCategory.scala
- valpas-web/src/components/typography/error.tsx
- valpas-web/src/views/hakutilanne/HakutilanneView.tsx
- valpas-web/src/views/hakutilanne/useOppijatData.ts
- valpas-web/src/views/oppija/OppivelvollisuudenKeskeytysModal.tsx
- valpas-web/src/views/suorittaminen/oppivelvolliset/SuorittaminenOppivelvollisetView.tsx
Käännetty loputkin APIn palauttamat virheet suomeksi, jotta niitä voidaan käyttää suoraan käyttöliittymässä kuten muitakin virheilmoituksia. Kaikista virheistä toki puuttuu yhä lokalisaatiot ruotsiksi ja englanniksi...
> Valpas virheenkäsittely

- src/main/resources/mockdata/koodisto/koodit/koskikoulutustendiaarinumerot.json
- src/main/scala/fi/oph/koski/documentation/ExamplesLukio.scala
- src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
- src/main/scala/fi/oph/koski/schema/LukioonValmistavaKoulutus.scala
- src/main/scala/fi/oph/koski/validation/LukioonValmistavanKoulutuksenValidaatiot.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationLukioonValmistavaSpec.scala
Laajuudet arvoina tietyissä tapauksissa '2' ja '4' hyväksytty. Yksi uusi validaatio; uusimmassa opsissa vain '2' sallitaan.
https://jira.eduuni.fi/browse/TOR-1495
> TOR-1495 - Luva - uusia laajuuden arvoja

- src/main/scala/fi/oph/koski/schema/Laajuus.scala
Epähuomiossa oli Virta-datan parsinnan yhteydessä lisätty `LaajuusOpintoviikkoissa` laitettu perimään `LaajuusOpintopisteissäTaiKursseissa` kun pitäisi periä vain suoraan `Laajuus`.
Pyritty tarkistamaan tuotannon raportointitietokannasta mahdollisimman hyvin, että  siellä ei ole suorituksia, joissa on käytössä `LaajuusOpintopisteissäTaiKursseissa´ ja joille olisi nyt laajuus laitettu viikkoina.
> LaajuusOpintopisteissäTaiKursseissa nimensä mukaiseksi; ei viikkoja mukaan

- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/main/scala/fi/oph/koski/validation/VapaaSivistystyöValidation.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöSpec.scala
Siirretty vst:n validaatiot tapahtumaan aikaisemmassa vaiheessa, jotta myös ei-vahvistetut suoritukset validoidaan.
Aikasemmin validoitu vain vahvistettuja VST:n päätason suorituksia.
> TOR-1455 - VST-Terminaalitilat

- .gitignore
- valpas-web/autoclear.js
- valpas-web/package.json
- valpas-web/test/integrationtests-env/setup.js
Parantaa devausergonomiaa tyhjentämällä automaattisesti käännösvälimuistin aina kun branch tai käännöskohde (dev, prod, integration test jne.) vaihtuu.
Pitäisi korjata ongelma, jossa devaaja saa selaimen konsolin täyteen virheilmoituksia puuttuvista moduuleista.
> Valppaan käännösvälimuistien automaattinen tyhjentäminen

- valpas-web/src/components/navigation/ExternalLink.tsx
- web/app/dokumentaatio/Dokumentaatio.jsx
- web/app/editor/StringEditor.jsx
- web/app/i18n/LocalizedExternalLink.jsx
- web/app/omadata/luvanhallinta/LuvanHallintaDisclaimer.jsx
- web/app/omattiedot/suoritusjako/SuoritusjakoLink.jsx
- web/app/suoritus/OmatTiedotSuoritustaulukko.jsx
- web/app/suoritus/PerusteEditor.jsx
- web/app/virkailija/VirkailijaOppijaView.jsx
- web/static/json-schema-viewer/index.html
Löydökset: https://github.com/artoj-nixu/koski/security/code-scanning
Osa löydöksistä testeistä ja Korhopankista, joita ei mielestäni kannata korjata (esimerkiksi ei järkeä ottaa stringien sanitointikirjastoa käyttöön selector-lauseen rakentamiseen testin sisällä). Jos joskus isketään ci-putkeen skanneri, niin tuollaiset mielestäni ignoreen.
> TOR-1592: CodeQL-löydösten korjaus

- src/main/scala/fi/oph/koski/servlet/BaseServlet.scala
Tarkoituksena saada kiinni vahingossa renderöidyt stack tracet.
Testit menee läpi joten arvioisin tämän olevan turvallinen muutos 🤔
> TOR-1566 Palauta virhe jos render pipelineen annetaan mitään muuta kuin HttpStatus tai Elem

- src/main/scala/fi/oph/koski/documentation/DocumentationApiServlet.scala
- src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOppija.scala
Ks. commit-viestit.
Tämän jälkeen schemaa pääsee tutkimaan visuaalisesti poluissa
https://virkailija.testiopintopolku.fi/koski/json-schema-viewer/?schema=valpas-internal-laaja-schema.json ja
https://virkailija.testiopintopolku.fi/koski/json-schema-viewer/?schema=valpas-internal-suppea-schema.json .
> TOR-xxxx: Lisää automaattisesti generoituva dokumentaatio Valpas-schemalle

- src/main/resources/mockdata/eperusteet/rakenne-liiketalouden-perustutkinto-paattymistesti.json
- src/main/scala/fi/oph/koski/eperusteet/EPerusteRakenne.scala
- src/main/scala/fi/oph/koski/eperusteet/MockEPerusteetRepository.scala
- src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
- src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
Tiketin kommentista:
"Tutkitaan että perusteen päättymisaikavalidaatio toimii oikein.
Päättymiaika päätellään ensisijaisesti siirtymäajan päättymispäivä-kentästä. 
Jos ko. kenttä tyhjä niin vasta sitten päättymispäivä-kenttää katsotaan."
> tor-1602 - suositaan siirtymäajan päättymispäivää validaatiossa; käytetään voimassaolon päättymispäivää jos siirtymäaikaa ei ole määritelty

- pom.xml
Nopeampi testata koko paketti kerralla devillä, kun ovat kaikki samalla kertaa:
- fix: upgrade com.amazonaws:aws-java-sdk-dynamodb from 1.12.140 to 1.12.147
- fix: upgrade software.amazon.awssdk:appconfig from 2.17.111 to 2.17.118
- fix: upgrade software.amazon.awssdk:cloudwatch from 2.17.111 to 2.17.119
- fix: upgrade software.amazon.awssdk:sts from 2.17.111 to 2.17.120
> AWS-kirjastojen yhdistetty päivitys

- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
- src/test/scala/fi/oph/koski/virta/VirtaXMLConverterSpec.scala
Korjaa nimen päättelyn suorituksen oppilaitokselle/toimipaikalle,
kaikille päättyneille opiskeluoikeuden tiloille.
> TOR-1287 korjaa oppilaitoksen nimen päättely Virta-datasta kaikille päättyneille opiskeluoikeuksille

- src/main/scala/fi/oph/koski/http/VirkailijaHttpClient.scala
- src/main/scala/fi/oph/koski/migri/MigriService.scala
- src/main/scala/fi/oph/koski/migri/MigriServlet.scala
- src/test/scala/fi/oph/koski/migri/MigriServiceSpec.scala
- src/test/scala/fi/oph/koski/migri/MigriSpec.scala
Koski toimii tässä lähinnä proxyna valinta-tulos-servicelle.
Jätetty tyhjä testifilu, jota käytetty manuaaliseen testaamiseen. Mielestäni se voi jatkossa olla hyvää dokumentaatiota ja kätevä testaamiseen.
Testataan routetuksen läpi pääseminen Mock-serviceä vasten.
> TOR-1334 - rajapinta migrille valintatietojen hakuun

- src/main/scala/fi/oph/koski/suostumus/SuostumuksenPeruutusServlet.scala
Estä None.get jos yritetään listata peruutetut
suostumukset ilman sessiota.
> Korjaa poikkeus listatessa peruutetut suostumukset

- src/main/resources/localization/koski-default-texts.json
- src/main/scala/fi/oph/koski/schema/TutkintokoulutukseenValmentavaKoulutus.scala
Korjaa schema viewerissä näkyviä tekstimuotoja.
> TOR-1703 korjaa TUVA json-skeeman kuvaavia tekstejä

- src/main/scala/fi/oph/koski/documentation/ExamplesVapaaSivistystyö.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationDIASpec.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöVapaatavoitteinenSpec.scala
- validaation_muutoshistoria.md
Mitätöinti halutaan sallia joka tapauksessa, vaikka
opiskeluoikeus ei läpäisisi validointisääntöjä.
> TOR-1670 älä validoi mitätöityjä opiskeluoikeuksia

- src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala
- src/main/scala/fi/oph/koski/henkilo/OppijanumeroRekisteriClient.scala
- src/main/scala/fi/oph/koski/http/VirkailijaHttpClient.scala
- src/main/scala/fi/oph/koski/huoltaja/HuollettavatRepository.scala
- src/main/scala/fi/oph/koski/koodisto/KoodistoMuokkausPalvelu.scala
- src/main/scala/fi/oph/koski/localization/LocalizationRepository.scala
- src/main/scala/fi/oph/koski/migri/MigriService.scala
- src/main/scala/fi/oph/koski/organisaatio/OrganisaatioRepository.scala
- src/main/scala/fi/oph/koski/userdirectory/KayttooikeusServiceClient.scala
- src/main/scala/fi/oph/koski/valpas/hakukooste/SureHakukoosteService.scala
aina ei haluta hakea virkailija-credentsejä SecretsManagerista, joten tarvitaan tapa ohittaa se haku. Toisaalta, on myös vaikea muuttaa koodia rakenteellisesti merkittävästi, koska testaaminen on hankalaa ympäristöeroavaisuuksien takia
> VirkailijaHTTPClientin siistimistä;

- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationEsiopetusSpec.scala
- validaation_muutoshistoria.md
Jos pidennetty oppivelvollisuus alkaa ennen opiskeluoikeuden alkamista,
käytetään pidennetyn oppivelvollisuuden aikajakson validoinnissa
opiskeluoikeuden alkamispäivää.
> TOR-1196 lisää poikkeus pidennetyn oppivelvollisuuden validointiin

- src/main/scala/fi/oph/koski/config/RunMode.scala
Ennen tarkastettiin vain kyseisen ympäristömuuttujan olemassaolo, eikä sisältö sinänsä vaikuttanut mitään. Käytännössä sen arvo oli aina 'true' tai se puuttui.
Nyt sallitut arvot ovat ainoastaan 'update' ja 'full', jotka yksiselitteisesti kertovat, halutaanko raportointikanta generoida kokonaan uusiksi, vai tehdäänkö inkrementaalinen päivitys.
> TOR-1633: Poista deprekoitu GENERATE_RAPORTOINTIKANTA-arvo

- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/fi/oph/koski/config/RunMode.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
- src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
Päätason suoritukset ja osasuoritukset duplikoituivat inkrementaalisen raportointikannan generoinnin yhteydessä, koska insertOrUpdate ei osannut päivittää niitä rivien primary keyn ollessa arbitraarinen tunniste.
> TOR-1633: Korjaa raportointikannan duplikoituvat suoritukset

- src/main/scala/fi/oph/koski/valpas/log/ValpasAuditLog.scala
- src/test/scala/fi/oph/koski/valpas/ValpasHeturouhintaSpec.scala
- src/test/scala/fi/oph/koski/valpas/ValpasKuntarouhintaSpec.scala
Lasketaan audit-viestiin mahtuvien oidien ja hetujen määrä
dynaamisesti, jotta vältetään jatkossa logitettavan viestin
maksimipituuden muutoksista johtuvat rikot audit-logien
pilkkomisessa pienempiin osiin.
> TOR-1723: Korjaus liian pitkien audit-logien aiheuttamiin 500-virheisiin rouhinnassa

- src/main/scala/fi/oph/koski/documentation/ExamplesLukio.scala
- src/main/scala/fi/oph/koski/raportit/lukio/LukioOppiaineenOppimaaranKurssikertymat.scala
- src/test/scala/fi/oph/koski/raportit/LukioKurssikertymaRaporttiSpec.scala
huom: vanhan opsin aineopiskelijoille ei erikseen ladata tietoa siitä, onko kyseessä nuorten vai aikuisten oppimäärä. yritetään päätellä tämä perusteen diaarinumerosta, mutta jos se epäonnistuu, käsitellään oletuksena suoritus nuorten opsina.
kaikille tiedyn ajan jälkeen päivitetyille vanhan lukion opsin suorituksille pitäisi olla peruste, mutta joillekin hyvin vanhoille se voi mielestäni puuttua.
> TOR-1340 - erotetaan aikuisaineopiskelijat omalle välilehdelle myös lukion vanhoilla opseilla. 

- .github/workflows/run_koski_tests_on_branches.yml
- .github/workflows/test_build_deploy_master.yml
- Makefile
- src/main/scala/fi/oph/koski/oppija/OppijaServlet.scala
- src/main/scala/fi/oph/koski/schema/KoskiSchema.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/main/scala/fi/oph/koski/validation/ValidatingAndResolvingExtractor.scala
- src/test/resources/rikkinäinen_opiskeluoikeus.json
- src/test/scala/fi/oph/koski/LocalJettyHttpSpec.scala
- src/test/scala/fi/oph/koski/SharedJetty.scala
- src/test/scala/fi/oph/koski/api/OppijaGetByOidSpec.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationNonMockEnvSpec.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationSpec.scala
- src/test/scala/fi/oph/koski/meta/GithubActionsSpec.scala
- src/test/scala/fi/oph/koski/mocha/KoskiMochaSpec.scala
- src/test/scala/fi/oph/koski/mocha/KoskiParallelMochaSpec.scala
- src/test/scala/fi/oph/koski/nonmockloginsecurity/OppijaValidationSpec.scala
- src/test/scala/fi/oph/koski/valpas/jest/ValpasFrontSpec.scala
Kommitit suunnilleen loogisessa järjestyksessä. Pientä aikasemman koodin refaktorointia viimeisesssä kommitissa muun asian lisäksi.
Eli kaksi laajempaa asiaa nyt tehty:
Ensinnäkin mahdollistetaan validaatioden skippaaminen ja poistetaan muutama deserialisoimaton kenttä datasta, kun ignoreKoskiValidator ja cleanForTesting -flagit asetettu jsonissa. Esimerkiksi rikkinäinen_opiskeluoikeus.json -tiedostossa käytetään nyt näitä. Tämä on mahdollista vain mock-ympäristössä.
Toisena asiana splitattu backend-testit kolmeen erikseen ajettavaan osaan. Tämä on sikäli tarpeen, että testit käyttävät jaettua Koskea ja jotta voidaan testata ylempää asiaa myös ei-mock-ympäristössä, tarvii käynnistää sille testille oma Koski. Sen lisäksi samalla haettiin pientä nopeutusta testien ajamiseen Githubissa. Noin …
> Tuotantodataan testaamisen helpottamista

- src/main/scala/fi/oph/koski/documentation/ExamplesLukio.scala
- src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala
- src/main/scala/fi/oph/koski/schema/Lukio2015.scala
- src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
This reverts commit 90252324f5cf498d8f821f5ec52bff69a5987b7f.
* kurssikertymärapsaa varten korjattu lukion oppimäärän koodiarvon tulkkaaminen, jotta saadaan aikuisten opsin mukaiset opiskelijat omalle välilehdelle raporttiin
* poistettu vanhan lukion oppiaineen päätason suorituken oppimäärän huomiointi raportointikantaa generoitaessa
> TOR-1340: Lukion kurssikertymäraportti/aineopiskelijat hännät

- src/main/scala/ScalatraBootstrap.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
- src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
Lue ympäristömuuttujasta parametri, pakotetaanko raportointikannan
generointi käyntiin jos edellinen generointi on vielä kesken.
> TOR-1745 parametrisoi raportointikannan generoinnin pakotus

- src/main/scala/fi/oph/koski/suostumus/SuostumuksenPeruutusService.scala
- src/main/scala/fi/oph/koski/suostumus/SuostumuksenPeruutusServlet.scala
- src/test/scala/fi/oph/koski/api/SuostumuksenPeruutusSpec.scala
Ks. commit-viestit.
Sähköpostinotifikaatio toteutetaan infran puolella.
> TOR-1676 Sähköposti Koski-tiimille, kun kansalainen peruu suostumuksen

- src/main/resources/db/migration/V83__create_paivitettu_opiskeluoikeus_table.sql
- src/main/resources/db/migration/V84__create_paivitetty_opiskeluoikeus_trigger.sql
- src/main/scala/fi/oph/koski/config/Environment.scala
- src/main/scala/fi/oph/koski/config/KoskiApplication.scala
- src/main/scala/fi/oph/koski/db/Database.scala
- src/main/scala/fi/oph/koski/db/KoskiTables.scala
- src/main/scala/fi/oph/koski/db/Migration.scala
- src/main/scala/fi/oph/koski/fixture/Fixtures.scala
- src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusQueryService.scala
- src/main/scala/fi/oph/koski/opiskeluoikeus/PäivitetytOpiskeluoikeudetJonoService.scala
- src/main/scala/fi/oph/koski/raportit/RaportitService.scala
- src/main/scala/fi/oph/koski/raportit/RaportitServlet.scala
- src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala
- src/main/scala/fi/oph/koski/raportointikanta/PäivitettyOpiskeluoikeusLoader.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabase.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
- src/main/scala/fi/oph/koski/raportointikanta/RaportointikantaService.scala
- src/main/scala/fi/oph/koski/util/TimeConversions.scala
- src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
- src/test/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoaderPerfTester.scala
- src/test/scala/fi/oph/koski/raportointikanta/RaportointikantaSpec.scala
**HUOM! Ympäristöihin vieminen vaatii jokaiseen raportointitietokantaan seuraavan migraation ajamisen manuaalisesti:**
```sql
alter table raportointikanta_status add column due_time timestamp without time zone;
```
Ympäristöön viemisen jälkeen voi olla hyvä idea vetää joko full reload tai populoida työjonoon tarvittavat työt operatiiviseen kantaan pyynnöllä:
```sql
insert into paivitetty_opiskeluoikeus
(opiskeluoikeus_oid, aikaleima)
select
oid as opiskeluoikeus_oid,
now() as aikaleima
from opiskeluoikeus
where aikaleima >= '2022-06-05'; -- tähän tietenkin sopiva aikaraja
```
-----------
Muutettu raportointikannan generoinnin logiikka niin: Sen sijaan että logiikka perustuu tietokannoissa oleviin opiskeluoikeuksien aikaleimoihin, lisätään opiskeluoikeuksien muutoksista rivi työjonoon, …
> TOR-1745: Raportointikannan generoinnin kuorman tasaaminen

- src/main/scala/fi/oph/koski/documentation/ExamplesEsiopetus.scala
- src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
- src/main/scala/fi/oph/koski/koskiuser/Kayttooikeus.scala
- src/main/scala/fi/oph/koski/koskiuser/KayttooikeusRepository.scala
- src/main/scala/fi/oph/koski/koskiuser/Session.scala
- src/main/scala/fi/oph/koski/opiskeluoikeus/OpiskeluoikeusQueryFilter.scala
- src/main/scala/fi/oph/koski/organisaatio/OrganisaatioRepository.scala
- src/main/scala/fi/oph/koski/perustiedot/OpiskeluoikeudenPerustiedotRepository.scala
- src/main/scala/fi/oph/koski/raportit/RaportitService.scala
- src/main/scala/fi/oph/koski/raportit/RaportitServlet.scala
- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/test/scala/fi/oph/koski/api/VarhaiskasvatusPerustiedotSpec.scala
- src/test/scala/fi/oph/koski/api/VarhaiskasvatusSpec.scala
- src/test/scala/fi/oph/koski/organisaatio/OrganisaatioRepositorySpec.scala
- src/test/scala/fi/oph/koski/organisaatio/RemoteOrganisaatioRepositorySpec.scala
- src/test/scala/fi/oph/koski/raportit/EsiopetusRaporttiSpec.scala
- src/test/scala/fi/oph/koski/raportit/RaportitServletSpec.scala
- validaation_muutoshistoria.md
- web/app/virkailija/Oppijataulukko.jsx
- web/app/virkailija/OrganisaatioPicker.jsx
- web/test/spec/RaportitSpec.js
- web/test/spec/esiopetusSpec.js
- web/test/spec/huoltajaSpec.js
- web/test/spec/oppijataulukkoSpec.js
Sallitaan peruskoulut esiopetuksen opiskeluoikeuden oppilaitoksina,
kun järjestämismuotona on ostopalvelu tai palveluseteli.
Varhaiskasvatuksen koulutustoimijoiden käyttäjät näkevät käyttöliittymällä kaikki peruskoulut,
kun lisätään esiopetuksen opiskeluoikeutta joka ostetaan oman organisaation ulkopuolelta, ja
pystyvät lisäämään oman organisaation ulkopuolisen peruskoulun opiskeluoikeuden oppilaitokseksi.
> TOR-1710 salli peruskoulut esiopetuksen ostopalvelun oppilaitoksina

- src/main/scala/fi/oph/koski/kela/KelaAikuistenPerusopetuksenSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaAmmatillinenSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaDIASchema.scala
- src/main/scala/fi/oph/koski/kela/KelaInternationalSchoolSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaLukionSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaLuvaSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaOpiskeluoikeusRepository.scala
- src/main/scala/fi/oph/koski/kela/KelaOppijaConverter.scala
- src/main/scala/fi/oph/koski/kela/KelaPerusopetuksenLisäopetuksenSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaPerusopetuksenSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaTutkintokoulutukseenValmentavanKoulutuksenSchema.scala
- src/main/scala/fi/oph/koski/kela/KelaVapaanSivistystyönSchema.scala
- src/main/scala/fi/oph/koski/schema/KoskiSchema.scala
Älä validoi aikajaksojen oikeellisuutta kun deserialisoidaan
opiskeluoikeus Kela skeemaan.
Lisätty omia luokkia aikajaksoille Kela skeemaan, jotta deserialisoinnin ignoreNonValidatingListItems-valinta ei vaikuta niihin ja jätä aikajaksoja palauttamatta.
> TOR-1677 höllennä validointia Kela skeemaan deserialisoitaessa

- src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
- src/main/scala/fi/oph/koski/documentation/ExamplesAmmatillinen.scala
- src/main/scala/fi/oph/koski/documentation/ExamplesValma.scala
- src/test/resources/backwardcompatibility/ammatillinen-erikoisammattitutkinto_2022-07-05.json
- src/test/resources/backwardcompatibility/ammatillinen-full_2022-07-05.json
- src/test/resources/backwardcompatibility/ammatillinen-perustutkinto_2022-07-05.json
- src/test/resources/backwardcompatibility/ammatillinen-reforminmukainenperustutkinto2022_2022-07-05.json
- src/test/resources/backwardcompatibility/ammatillinen-reforminmukainenperustutkinto_2022-07-05.json
- src/test/resources/backwardcompatibility/ammatillinen-reformiuseitatutkinnonosia_2022-07-05.json
- src/test/resources/backwardcompatibility/ammatillinen-tutkinnonosa_2022-07-05.json
- src/test/resources/backwardcompatibility/ammatillinen-tutkinnonosaapienempikokonaisuus_2022-07-05.json
- src/test/resources/backwardcompatibility/ammatilliseenperuskoulutukseenvalmentavakoulutus_2022-07-05.json
- src/test/resources/backwardcompatibility/lukio-paattotodistus_2022-07-05.json
- src/test/resources/backwardcompatibility/tiedonsiirto-epaonnistunut3_2022-07-05.json
- src/test/resources/backwardcompatibility/tyohonjaitsenaiseenelamaanvalmentavakoulutus_2022-07-05.json
Vältetään jatkossa ammatillisten suoritusten esimerkeistä
mallia otettaessa ongelmasta, jossa koodiviite on sidottu
väärään koodistoversioon. Lisäksi samalla korjautuu
dokumentaation esimerkki "ammatillinen - reformin mukainen
perustutkinto 2022"
> TOR-1767: Poistetaan tutkinnonosat-koodiston pakotus versioon 1 kaikista ammatillisen esimerkeistä

- valpas-web/src/components/forms/DateRangePicker.tsx
- valpas-web/src/utils/date.ts
- valpas-web/src/views/oppija/oppivelvollisuudenkeskeytys/OppivelvollisuudenKeskeytysForm.tsx
Tämä PR korjaa bugin, jolla Valpaksen käyttämä päivämäärädialogi kaatui väärällä syötteellä. Esimerkiksi syöte `01-01-22222` aiheuttaa poikkeuksen `react-date-picker` -kirjaston sisällä, koska syötettä ei oltu validoitu millään tavalla. Korjaus on testattu manuaalisesti.
> TOR-1777 Korjaa päivämäärädialogin kaatuminen väärällä syötteellä

- src/main/scala/fi/oph/koski/documentation/AmmatillinenExampleData.scala
- src/main/scala/fi/oph/koski/eperusteet/EPerusteRakenne.scala
- src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
- src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
- validaation_muutoshistoria.md
Koodi voidaan siirtää vain jos suorituksen perusteen
voimaantulon päivä on 1.8.2022 tai sen jälkeen.
> TOR-1769 korjaa validaatio ammatillisen uudelle koodille VVAI22

- valpas-web/src/style/spacing.less
- valpas-web/src/views/hakutilanne/HakutilanneView.less
- valpas-web/src/views/hakutilanne/NivelvaiheenHakutilanneView.tsx
Samalla kaikille sivuille tuli nyt alareunaan marginaalia,
jotta sama vahinko ei tapahtuisi jakossa niin helposti ja
sivuja on muutenkin mukavampi skrollata.
> TOR-1800: Valpas: nivelvaiheen taulukon alareunasta katoaa tietoa

- src/main/resources/mockdata/koodisto/koodistot/koulutus_11.json
- src/main/resources/mockdata/koodisto/koodit/koulutus_11.json
- src/main/scala/fi/oph/koski/documentation/DocumentationApiServlet.scala
- src/main/scala/fi/oph/koski/koodisto/Koodisto.scala
- src/main/scala/fi/oph/koski/koodisto/KoodistoMockDataSorter.scala
- src/main/scala/fi/oph/koski/koodisto/KoodistoMockDataUpdater.scala
- src/main/scala/fi/oph/koski/koodisto/KoodistoViitePalvelu.scala
- src/main/scala/fi/oph/koski/koodisto/Koodistot.scala
- src/main/scala/fi/oph/koski/koodisto/MockKoodistoPalvelu.scala
- src/test/scala/fi/oph/koski/koodisto/KoodistotTest.scala
- src/test/scala/fi/oph/koski/localization/KoodistotLocalizationTest.scala
- src/test/scala/fi/oph/koski/tools/CsvToKoodisto.scala
- src/test/scala/fi/oph/koski/tools/TxtToKoodisto.scala
- web/app/uusisuoritus/UusiAmmatillisenTutkinnonSuoritus.jsx
- web/test/page/opinnotPage.js
- web/test/spec/ammatillinenSpec.js
- web/test/spec/muuAmmatillinenSpec.js
Vanhemmat versiot koodistoista lisätään mock-dataan siten, että versio erotetaan alaviivalla json-tiedostojen nimiin ja versio lisätään myös listaukseen Koodistot.scalaan.
Koodistot ilman eksplisiittistä versiota tulkitaan "uusimmaksi".
> TOR-1775 mahdollista mock-koodistojen versiointi

- .github/workflows/run_koski_tests_continuously_on_master.yml
- .github/workflows/run_koski_tests_on_branches.yml
- .github/workflows/test_build_deploy_master.yml
- Makefile
- src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala
- src/test/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoServiceSpec.scala
- web/test/page/tiedonsiirrotPage.js
- web/test/spec/tiedonsiirrotSpec.js
Korjaa duplikaatti id:t dokumenteille, joille ei ole henkilötietoja tai niitä ei voida parsia syötteestä.
> Varmista uniikki id kaikille tiedonsiirtolokin dokumenteille

- .github/workflows/run_koski_tests_continuously_on_master.yml
- .github/workflows/run_koski_tests_on_branches.yml
- .github/workflows/test_build_deploy_master.yml
- Makefile
- src/main/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoService.scala
- src/test/scala/fi/oph/koski/tiedonsiirto/TiedonsiirtoServiceSpec.scala
- web/test/page/tiedonsiirrotPage.js
- web/test/spec/tiedonsiirrotSpec.js
Korjaa duplikaatti id:t dokumenteille, joille ei ole henkilötietoja tai niitä ei voida parsia syötteestä.
Ei tee muutoksia olemassaolevien dokumenttien id:n päättelyyn, jotta ne voidaan edelleen poistaa käyttöliittymältä.
> Varmista uniikki id kaikille tiedonsiirtolokin uusille dokumenteille

- src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
- validaation_muutoshistoria.md
Sallitaan keskiarvo kun _opiskeluoikeuden_ tila on "katsotaan eronneeksi". Aiemmin yritettiin katsoa suorituksen tilaa.
> Korjaus ammatillisen suorituksen keskiarvon validaatioon

- src/main/scala/fi/oph/koski/validation/AmmatillinenValidation.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationAmmatillinenSpec.scala
- validaation_muutoshistoria.md
Lisää tarkennuksia speksiin: keskiarvo vaaditaan vain perustutkinnolta, joka on päättynyt 15.1.2018 tai myöhemmin ja suoritustapana on reformi/ops
> TOR-1197 Ammatillisen keskiarvo vaaditaan vain perustutkinnolta

- web/app/style/tiedonsiirrot.less
> TOR-XXXX: Korjaa tiedonsiirtovirheiden näkymässä pre-elementin tekstin ylivuoto

- src/main/scala/fi/oph/koski/eperusteetvalidation/TutkintoRakenneValidator.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationTutkintokoulutukseenValmentavaKoulutusSpec.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöKOPSSpec.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöKOTOSpec.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationVapaaSivistystyöLukutaitoSpec.scala
- validaation_muutoshistoria.md
estetään näin opiskeluoikeuksien siirtäminen perusteella jossa on väärä koulutustyyppi.
> TOR-1840 lisää puuttuvat koulutukset perusteen rakennevalidaatioon

- src/main/scala/fi/oph/koski/kela/KelaAmmatillinenSchema.scala
- src/test/scala/fi/oph/koski/kela/KelaSpec.scala
Lisätty Kelan tietomalliin tiedot oppisopimuksen purkamisesta. Tiketissä mainittu dokumentaation päivitys puuttuu tästä pullarista - tehdään erikseen.
> TOR-1822 Lisää Kelan malliin tieto oppisopimuksen purkamisesta

- src/main/scala/fi/oph/koski/validation/KoskiValidator.scala
- src/main/scala/fi/oph/koski/validation/PerusopetuksenOpiskeluoikeudenValidation.scala
- src/test/scala/fi/oph/koski/api/OppijaValidationPerusopetuksenVuosiluokkaSpec.scala
- validaation_muutoshistoria.md
Nuorten perusopetuksen vuosiluokan päätason suoritus sallitaan vahvistaa ilman osasuorituksia, kun oppija on vuosiluokkiin sitomattomassa opetuksessa.
> TOR-1754 salli vahvistaa vuosiluokan suoritus ilman osasuorituksia vuosiluokkiin sitomattomassa opetuksessa

- src/main/scala/fi/oph/koski/koodisto/RemoteKoodistoPalvelu.scala
Haetaan koodistot lisätietoineen yhdellä kyselyllä sen sijaan että haettaisiin lisätiedot kullekin koodistolle erikseen.
Odottaa uuden apin julkaisua qa- ja prod-ympäristöihin.
> Koesta uutta koodistorajapintaa

- .github/workflows/deploy.yml
- .github/workflows/test_build_deploy_master.yml
Kts. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> TOR-1894: Vaihda GitHub actionsin set-output -komennon syntaksi uuteen

- src/main/scala/fi/oph/koski/config/KoskiApplication.scala
- src/main/scala/fi/oph/koski/opiskeluoikeus/CompositeOpiskeluoikeusRepository.scala
Käytetään olemassa olevaa Hetu-instanssia validoimiseen, jotta acceptSyntheticHetus -lippua ei tarvitse kovakoodata vaan se luetaan konfigista.
> Salli synteettiset hetut sen mukaan mitä appconfig sanoo

- src/main/resources/localization/koski-default-texts.json
- src/main/scala/fi/oph/koski/documentation/ExamplesTaiteenPerusopetus.scala
- src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoader.scala
- src/main/scala/fi/oph/koski/schema/OsaamisenTunnustaminen.scala
- src/main/scala/fi/oph/koski/schema/TaiteenPerusopetus.scala
- src/test/resources/backwardcompatibility/taiteenperusopetus-hyvaksytystisuoritettu_2023-01-26.json
- src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
- tiedonsiirtoprotokollan_muutoshistoria.md
Tunnustettu-rakenne on kevyempi kuin muissa opiskeluoikeuden tyypeissä ja sisältää ainoastaan selite-kentän.
> TOR-1691 lisää tunnustettu-rakenne taiteen perusopetukseen

- web/app/opiskeluoikeus/opintojenRahoitus.js
- web/test/page/addOppijaPage.js
- web/test/spec/tuvaSpec.js
Korjaus: rahoitusmuoto valittavaksi kälissä loma-tilaiselle TUVA-opiskeluoikeudelle
> TOR-1888 TUVA: rahoitusmuoto toimii käyttöliittymässä myös loma-tilaiselle

- web/app/components-v2/containers/EditorContainer.tsx
- web/app/taiteenperusopetus/TaiteenPerusopetusEditor.tsx
- web/test/e2e/taiteenperusopetus.spec.ts
Taiteen perusopetuksen opiskeluoikeudella pitää olla kaksi vahvistettua
päätason suoritusta ennen kuin opiskeluoikeus voidaan
merkitä hyväksytysti suoritetuksi.
> TOR-1692: Korjaus opiskeluoikeuden tilan asettamiseen

- src/main/scala/fi/oph/koski/ytr/download/YtrDownloadService.scala
Muuta osa warn-logeista error-logeiksi. Ks. myös https://github.com/Opetushallitus/koski-aws-infra/pull/162
> TOR-1639 Käytä error-logia hälyjen mahdollistamiseksi 

- docker-build/Dockerfile
- docker-compose.yaml
- opensearch/Dockerfile
Pinnataan Koskessa käytössä olevat Dockerfile-versiot hashiin.
SHA256-hashin etuja:
- Jos imagen ylläpitäjä julkaisee päivityksen ja se rikkoo asioita, niin menee myös Koski
- Ilman SHA256 hashia ei saada aikaan täysin deterministisiä buildeja Koskesta
Pinnaamalla Dockerfilet SHA256-hasheihin parannetaan myös turvallisuutta estämällä uusien image-muutosten tuominen automaattisesti ilman auditointia.
> Pinnaa Kosken Dockerfilen image-versiot SHA256-hashiin

- src/main/resources/reference.conf
- src/main/scala/fi/oph/koski/ytr/YoTodistusService.scala
- src/main/scala/fi/oph/koski/ytr/YtrS3.scala
Yo-todistusta varten luotu s3-salaisuus on nykyisen toteutuksen myötä muuttunut turhaksi,
koska se on muilta osin sama kuin vanha ytr-s3-salaisuus paitsi bucketin, joka asetetaan
kutsujen yhteydessä joka tapauksessa dynaamisesti.
> TOR-1933: Poista ytr-s3-certificates-credentials käytöstä

- src/main/scala/fi/oph/koski/raportointikanta/RaportointiDatabaseSchema.scala
- src/test/scala/fi/oph/koski/migration/MigrationSpec.scala
Mätsää osasuorituksen rivi eri tavalla oppiaineen ja kurssin kanssa paremman lopputuloksen saavuttamiseksi. Aiemmin kurssi ei mätsännyt osasuorituksen riviin lainkaan, jos kurssin koulutusmoduulissa oli kieli määriteltynä.
> TOR-1893 korjaa kurssien näkyminen raportin kurssien välilehdellä

- src/main/resources/mockdata/ytr/laaja_080380-2432_140380-336X_220680-7850_240680-087S_060807A7787.json
- src/main/scala/fi/oph/koski/raportointikanta/OpiskeluoikeusLoaderRowBuilder.scala
raportointikantaan varsinaisen kokeen tutkintokokonaisuuteen. Jätetään rivi lisäämättä toistaiseksi.
> Älä lisää YTR-kokeen virheellistä sisällytettyä suoritusta;

- web/app/suoritus/OmatTiedotSuoritustaulukko.jsx
- web/app/util/koskiApi.ts
- web/test/spec/omatTiedotSpec.js
- Näytä yo-todistuksen lataus vain omat tiedot -sivulla
- Ei uudelleenlatausta, jos yo-todistus-api palauttaa 401;
> TOR-1933: Älä näytä yo-todistuksen-latausta linkkijaossa

- src/main/scala/fi/oph/koski/migri/ConvertMigriSchema.scala
- src/main/scala/fi/oph/koski/migri/MigriSchema.scala
- src/test/scala/fi/oph/koski/migri/MigriSpec.scala
Korjaus: tunnustettu-kenttä aina mukaan, lisätiedot-kenttä vain jos mukautettu löytyy
> TOR-2002 korjaus Migrin tietomalliin

- src/main/scala/fi/oph/koski/documentation/ExamplesAmmatillinen.scala
- src/main/scala/fi/oph/koski/migri/ConvertMigriSchema.scala
- src/test/scala/fi/oph/koski/migri/MigriSpec.scala
Mätsää aliosasuoritusten lisätiedot oikeaan traittiin väärän sijaan.
> TOR-2002 korjaa migrin rajapinnan amiksen aliosasuoritusten konversio

- src/main/scala/fi/oph/koski/suoritusjako/SuoritusjakoService.scala
- src/test/scala/fi/oph/koski/api/SuoritusjakoAPISpec.scala
> TOR-1984: Korjaa: eri tyyppisten linkkijakojen secretejä voi käyttää ristiin

- src/main/scala/fi/oph/koski/log/LogUtils.scala
- src/test/scala/fi/oph/koski/log/LogMaskingPatternConverterSpec.scala
\b ei laske alaviivan ja numeron väliä "word boundaryksi"
> TOR-2009: Estä hetujen päätyminen logille OpenSearch-id:n kautta

- src/main/resources/mockdata/virta/henkilotiedot/130505A831H.xml
- src/main/resources/mockdata/virta/opintotiedot/080795-884U.xml
- src/main/resources/mockdata/virta/opintotiedot/130505A831H.xml
- src/main/scala/fi/oph/koski/henkilo/KoskiSpecificMockOppijat.scala
- src/main/scala/fi/oph/koski/virta/VirtaXMLConverter.scala
Korjaa tilanteen jossa Virta-datassa tulee eri opiskelija-noodien alla
opiskeluoikeus-noodit, joilla oli samat avaimet. Nyt suoritukset
yhdistetään oikeisiin opiskeluoikeuksiin, eikä opiskeluoikeuksia
poisteta listasta holtittomasti.
> TOR-2056: Puuttuvat Virta-suoritukset

- src/main/scala/fi/oph/koski/schema/EuropeanSchoolOfHelsinki.scala
- src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotESHSchema.scala
- src/main/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotService.scala
- src/main/scala/fi/oph/koski/validation/MaksuttomuusValidation.scala
- src/test/scala/fi/oph/koski/api/misc/MaksuttomuusSpec.scala
- src/test/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotServiceSpec.scala
- tiedonsiirtoprotokollan_muutoshistoria.md
- validaation_muutoshistoria.md
- web/app/types/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotEuropeanSchoolOfHelsinkiPaatasonSuoritus.ts
Päivitetään maksuttomuusvalidaatiota niin että S5 kelpaa
> TOR-2033 Salli maksuttomuustiedon siirtäminen ESH S5-vuosiluokalle

- src/main/scala/fi/oph/koski/valpas/opiskeluoikeusrepository/ValpasOpiskeluoikeusDatabaseService.scala
- valpas-web/test/integrationtests/hakutilanne.shared.ts
- valpas-web/test/integrationtests/hakutilanne.test.ts
- Älä näytä S5+ -oppijoita hakeutumisenvalvonnassa
- Siisti suorituksenvalvontalogiikkaa
- Näytä ESH:n perusopetuksen päättymispäivä oikein
> TOR-2051: ESH S4-muutoksen korjauksia

- src/main/scala/fi/oph/koski/eperusteetvalidation/EPerusteetLops2019Validator.scala
- Salli elämänkatsomustiedon moduulit uskonnon oppiaineeseen
- Salli uskonnon moduulit elämänkatsomustiedon alle
- Siirrä diplomimoduulit oikeiden oppiaineiden alle
> TOR-1119: LOPS2019-ePeruste-validaation korjauksia 2

- src/main/scala/fi/oph/koski/eperusteetvalidation/EPerusteetLops2019Validator.scala
- Ei validoida lukiodiplomeja rakenteen perusteella
- Salli uskonnon ja et:n moduulien ristipölytys vain valinnaisille moduuleille
> TOR-1119: lops2019-ePeruste-validaatiokorjauksia III

- owasp-dependency-check-suppressions.xml
Test dependency for aws s3, waits for aws sdk patch
> Suppress owasp warning for netty 4.1.94

- owasp-dependency-check-suppressions.xml
… since netty is just a test dependency for aws s3
> Suppress cve-2023-4586 for a while

- web/app/components-v2/containers/EditorContainer.tsx
- web/app/components-v2/forms/FormModel.ts
- web/app/components-v2/messages/GlobalErrors.tsx
- web/app/components-v2/messages/Snackbar.tsx
- web/app/vst/VSTEditor.tsx
- web/app/vst/VSTOsasuoritusProperties.tsx
- web/test/e2e/pages/oppija/KoskiOppijaPageV2.ts
- web/test/e2e/pages/oppija/KoskiVSTOppijaPage.ts
- web/test/e2e/pages/oppija/uiV2builder/Select.ts
- web/test/e2e/vst.spec.ts
- Käytä desimaalierottimena pilkkua
- Poista vanhat virheet näkyvistä ennen tallennusta
- Lisää tallennuksen yritys jokaisen muokkaustestin perään
- Poista unohtunut console.log
- Importien siivous
- fixup! Lisää tallennuksen yritys jokaisen muokkaustestin perään
> TOR-1959: Fronttivalidaatioiden fiksauksia

- web/app/components-v2/containers/EditorContainer.tsx
- web/app/components-v2/opiskeluoikeus/SuorituksenVahvistus.tsx
- web/app/vst/kops/AddKOPSOsasuoritus.tsx
- web/app/vst/vapaatavoitteinen/VSTVapaatavoitteinenEditor.tsx
- web/test/e2e/vst.spec.ts
- Poista lisätiedot vapaatavoitteisilta
- Korjaa ensimmäisen kops-osasuorituksen lisäys
- Mahdollista vapaatavoitteisen vahvistuksen poisto terminaalitilalla
> TOR-2086: VST-korjauksia

- src/main/scala/fi/oph/koski/ytr/YtrClient.scala
> TOR-2001: Käytä retry-clientia myös YO-todistuksen generoinnissa

- src/main/scala/fi/oph/koski/documentation/ExamplesVapaaSivistystyöJotpa.scala
- src/main/scala/fi/oph/koski/fixture/KoskiSpecificDatabaseFixtureCreator.scala
- web/app/components-v2/access/RequiresWriteAccess.tsx
- web/app/components-v2/opiskeluoikeus/OpiskeluoikeusEditToolbar.tsx
- web/test/e2e/pages/oppija/KoskiVSTOppijaPage.ts
- web/test/e2e/pages/oppija/uiV2builder/OpiskeluoikeusHeader.ts
- web/test/e2e/vst.spec.ts
- Lisää lähdejärjestelmällinen vst-oppija
- Piilota muokkaa-nappi lähdejärjestelmälliseltä vst-oppijalta
> TOR-2111: VST: Muokkaustoiminnallisuus tiedonsiirroilla siirretyissä opiskeluoikeuksissa ja KOSKI-pääkäyttäjän pystyttävä mitätöimään opiskeluoikeus

- src/main/scala/fi/oph/koski/http/KoskiErrorCategory.scala
- src/main/scala/fi/oph/koski/koskiuser/Kayttooikeus.scala
- src/main/scala/fi/oph/koski/koskiuser/KoskiSpecificAuthenticationSupport.scala
- src/main/scala/fi/oph/koski/koskiuser/MockUsers.scala
- src/main/scala/fi/oph/koski/koskiuser/RequiresMigri.scala
- src/main/scala/fi/oph/koski/koskiuser/RequiresPalveluvayla.scala
- src/main/scala/fi/oph/koski/koskiuser/Session.scala
- src/main/scala/fi/oph/koski/luovutuspalvelu/PalveluvaylaServlet.scala
- src/main/scala/fi/oph/koski/migri/MigriServlet.scala
- src/main/scala/fi/oph/koski/mydata/ApiProxyServlet.scala
- src/main/scala/fi/oph/koski/organisaatio/MockOrganisaatioRepository.scala
- src/main/scala/fi/oph/koski/schema/FilterNonAnnotationableSensitiveData.scala
- src/main/scala/fi/oph/koski/schema/Korkeakoulu.scala
- src/main/scala/fi/oph/koski/userdirectory/DirectoryClient.scala
- src/test/scala/fi/oph/koski/api/misc/KäyttöoikeusryhmätSpec.scala
- src/test/scala/fi/oph/koski/json/SensitiveAndRedundantDataFilterSpec.scala
- src/test/scala/fi/oph/koski/koskiuser/KoskiSpecificSessionSpec.scala
- src/test/scala/fi/oph/koski/luovutuspalvelu/PalveluvaylaSpec.scala
- src/test/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusSpec.scala
- src/test/scala/fi/oph/koski/migri/MigriServletSpec.scala
- src/test/scala/fi/oph/koski/migri/MigriSpec.scala
- src/test/scala/fi/oph/koski/mydata/MyDataAPIProxyServletTest.scala
- src/test/scala/fi/oph/koski/valvira/ValviraSpec.scala
- src/test/scala/fi/oph/koski/ytl/YtlSpec.scala
- Lisää uusi rooli Migrille ja käsittele luovutuspalvelukäyttäjänä. 
- Lisää myös roolit HSL ja SUOMIFI ja erota palveluväyläkäyttäjät muista luovutuspalvelun käyttäjistä.
- Poista rooli TIEDONSIIRTO_LUOVUTUSPALVELU
> TOR-2037 Uusi käyttöoikeus Migrille

- src/main/resources/localization/koski-default-texts.json
- web/app/appstate/useSearchParam.tsx
- web/app/components-v2/opiskeluoikeus/OpiskeluoikeusEditToolbar.tsx
- web/app/components-v2/opiskeluoikeus/OpiskeluoikeusTitle.less
- web/app/components-v2/opiskeluoikeus/OpiskeluoikeusTitle.tsx
- web/app/components-v2/opiskeluoikeus/TodistuksellaNäkyvätLisätiedotField.tsx
- web/app/util/url.ts
- Indikoi paremmin että ollaan katsomassa oo:n versiota
- Piilota muokkaus- ja mitätöintinapit versiota katseltaessa
- Lisää nappi jolla poistutaan versioiden katselusta
- Korjaa todistuksen lisätietojen validointi
> TOR-2049: VST-/TPO-näkymien kälikorjauksia

- src/main/scala/fi/oph/koski/validation/DuplikaattiValidation.scala
- src/test/scala/fi/oph/koski/api/oppijavalidation/OppijaValidationPerusopetusSpec.scala
Virheellisen validaatiovirheen aiheutti seuraavat tilanteet:
- oppija siirtyi toiselle rinnakkaisluokalle
- oppija vaihtoi kesken lukukauden koulua ja vuosiluokan suoritus jäi edellisessä koulussa keskentilaiseksi
> TOR-2173: Korjauksia nuorten perusopetuksen vuosiluokan suoritusten validaatioon

- web/app/components-v2/containers/Modal.less
- web/app/components-v2/controls/KieliSelect.tsx
- web/app/components-v2/controls/Select.less
- web/app/components-v2/controls/Select.tsx
- web/app/uusiopiskeluoikeus/UusiOpiskeluoikeusForm.less
- web/app/uusiopiskeluoikeus/UusiOpiskeluoikeusForm.tsx
- web/app/uusiopiskeluoikeus/components/DialogKoodistoSelect.tsx
- web/app/uusiopiskeluoikeus/components/DialogPaatasonSuoritusSelect.tsx
- web/app/uusiopiskeluoikeus/components/DialogPerusteSelect.tsx
- web/app/uusiopiskeluoikeus/components/DialogSelect.tsx
- web/app/uusiopiskeluoikeus/components/OppilaitosSearch.tsx
- web/app/uusiopiskeluoikeus/components/OppilaitosSelect.tsx
- web/app/uusiopiskeluoikeus/suoritus/AmmatillinenKoulutusFields.tsx
- web/app/uusiopiskeluoikeus/suoritus/TaiteenPerusopetusFields.tsx
- **Mahdollista organisaatiovalitsimen käyttö pääkäyttäjänä**
- **Tiukenna riviväliä matalemmilla resoilla**
- **Estä dialogin muuttuminen käyttökelvottomaksi ahtaalla ruudulla**
- **Korjaa hajonnut automaattinen kielivalinta**
> TOR-2189: Dialogin kälikorjauksia

- .github/actions/setup_backend/action.yml
- .github/workflows/all_tests.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy.yml
- .github/workflows/run_performance_tests.yml
- .github/workflows/run_security_checks.yml
- .github/workflows/run_smoketests.yml
- .github/workflows/test_build_deploy_master.yml
- .github/workflows/update_localizations.yml
- .github/workflows/valpas_performance_tests.yml
- Makefile
- README.md
- sandbox/pull_rebuild_restart.sh
`docker-compose` -komento on korvattu `docker compose` -komennolla (huomaa puuttuva väliviiva).
Päivitetty samalla dokumentaatio ja korjattu workflowta testatessa havaitut GH `actions/checkout@v3` deprekaatiot.
> Korvaa docker-compose komento docker compose :lla

- src/main/resources/localization/koski-default-texts.json
- web/app/components-v2/controls/Select.tsx
- web/app/style/uusi-oppija.less
- web/app/uusiopiskeluoikeus/components/DialogKoodistoSelect.tsx
- web/test/spec/esiopetusSpec.js
- **Älä nappaa kentälle fokusta klikkaamalla sen oikealle puolelle**
- **Filtteröi ryhmiteltyjen vaihtoehtojen lapsien filtteröinti**
- **Nopeuta pudotusvalikkoa rajoittamalla renderöityjä vaihtoehtoja**
> TOR-2189: Opiskeluoikeuden luontidialogin bugikorjauksia

- src/main/resources/reference.conf
- src/main/scala/fi/oph/koski/jettylauncher/JettyLauncher.scala
Jetty asettaa idle timeoutin oletuksena 30 sekunniksi. Tämä on ongelma, koska ympäristöjen kuormantasaaja asettaa idle timeoutin 900 sekuntiin (15min), jolloin load balancer ei välttämättä havaitse "danglaamaan" jääviä TCP-yhteyksiä.
Tehdään mahdolliseksi asettaa Jetty HTTP timeout. Ympäristöissä timeoutin sopiva arvo on 905s
> Aseta idle timeout konfiguroitavaksi Jetty-serverille

- src/main/resources/reference.conf
- src/main/scala/fi/oph/koski/mydata/MyDataConfig.scala
- src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogMockData.scala
- src/main/scala/fi/oph/koski/omaopintopolkuloki/AuditLogService.scala
- src/test/scala/fi/oph/koski/omaopintopolkuloki/OmaOpintoPolkuLokiServletSpec.scala
Ks. commit-viestit ja myös https://github.com/Opetushallitus/oma-opintopolku-loki/pull/400
> TOR-2210 OmaData OAuth2: Näytä kansalaiskälissä myös OAuth2-rajapinnan kautta katselut

- src/main/scala/fi/oph/koski/massaluovutus/MassaluovutusDocumentation.scala
- src/main/scala/fi/oph/koski/massaluovutus/luokallejaaneet/MassaluovutusQueryLuokalleJaaneet.scala
- src/main/scala/fi/oph/koski/massaluovutus/luokallejaaneet/MassaluovutusQueryLuokalleJaaneetCsv.scala
- src/main/scala/fi/oph/koski/massaluovutus/luokallejaaneet/MassaluovutusQueryLuokalleJaaneetExamples.scala
- src/main/scala/fi/oph/koski/massaluovutus/luokallejaaneet/MassaluovutusQueryLuokalleJaaneetJson.scala
- src/test/scala/fi/oph/koski/massaluovutus/MassaluovutusSpec.scala
- **Lisää mahdollisuus ladata luokalle jääneet csv-tiedostona**
- **Lisää virherivit opiskeluoikeuksien kohdalle, joissa havaittiin rikkinäinen historia**
> TOR-2182: Luokalle jääneiden massaluovutuskyselyyn tuki csv:lle

- src/main/resources/documentation/omadata_oauth2.md
- src/main/scala/fi/oph/koski/suoritusjako/common/OpiskeluoikeusFacade.scala
- src/main/scala/fi/oph/koski/suoritusjako/common/OpiskeluoikeusRepository.scala
- src/test/scala/fi/oph/koski/hakemuspalvelu/HakemuspalveluServiceSpec.scala
- src/test/scala/fi/oph/koski/omadataoauth2/unit/OmaDataOAuth2BackendSpec.scala
- src/test/scala/fi/oph/koski/suoritusjako/aktiivisetjapaattyneetopinnot/AktiivisetJaPaattyneetOpinnotServiceSpec.scala
- src/test/scala/fi/oph/koski/suoritusjako/suoritetuttutkinnot/SuoritetutTutkinnotServiceSpec.scala
- src/test/scala/fi/oph/koski/vkt/VktServiceSpec.scala
> TOR-2210: OmaData OAuth2: Palauta tiedonhyödyntäjälle 404 aina, jos oppijalla ei ole mitään opiskeluoikeuksia kannassa

- docker-build/Dockerfile
Syy: [CHANGE] Changed release model to use GitHub Release page for jars. collector jar no longer published to Maven Central.
> Päivät jmx exporter uusi url

- web/app/ib/dialogs/UusiIBTutkintoOsasuoritusDialog.tsx
Ei aseteta laajuutta tilakoneelle, vaan pakotetaan se päättelemään se itse päivämäärän perusteella
> TOR-2263: Korjaa väärä laajuuden yksikkö käytettäessä vanhaa tallennettua paikallista kurssia

- .github/skip_tiedonsiirtoprotokollan_muutoshistoria.md
- src/main/resources/localization/koski-default-texts.json
- src/main/resources/mockdata/koodisto/koodit/vktkielitaito.json
- src/main/scala/fi/oph/koski/documentation/ExamplesKielitutkinto.scala
- src/main/scala/fi/oph/koski/koskiuser/Kayttooikeus.scala
- src/main/scala/fi/oph/koski/koskiuser/Session.scala
- src/main/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusServlet.scala
- src/main/scala/fi/oph/koski/schema/Kielitutkinto.scala
- src/main/scala/fi/oph/koski/schema/Opiskeluoikeus.scala
- src/main/scala/fi/oph/koski/sso/LocalLoginServlet.scala
- src/test/scala/fi/oph/koski/api/misc/OppijaExamplesTest.scala
- src/test/scala/fi/oph/koski/kielitutkinto/KielitutkintorekisteriSpec.scala
- src/test/scala/fi/oph/koski/koskiuser/KaikilleOpiskeluoikeudenTyypeilleOnKayttooikeusSpec.scala
- src/test/scala/fi/oph/koski/koskiuser/KoskiSpecificSessionSpec.scala
- src/test/scala/fi/oph/koski/luovutuspalvelu/TilastokeskusSpec.scala
- tiedonsiirtoprotokollan_muutoshistoria.md
- valpas-web/package-lock.json
- valpas-web/package.json
- valpas-web/test/integrationtests-env/browser/reset.ts
- web/app/components-v2/containers/EditorContainer.tsx
- web/app/components-v2/opiskeluoikeus/OpiskeluoikeusTitle.tsx
- web/app/components-v2/opiskeluoikeus/SuorituksenVahvistus.tsx
- web/app/kielitutkinto/KielitutkintoEditor.tsx
- web/app/kielitutkinto/ValtiohallinnonKielitutkintoEditor.tsx
- web/app/kielitutkinto/YleinenKielitutkintoEditor.tsx
- web/app/types/fi/oph/koski/schema/ValtionhallinnonKielitutkinnonSuoritus.ts
- **Opiskeluoikeuden otsikkopalkkiin kielitutkinnon tyyppi, kieli ja tutkintopäivä**
- **Piilota opiskeluoikeuden voimassaoloaika**
- **Lisää päätason suoritukselle testipaikka; nimeä tutkintopäivä -> testipäivä**
- **Poista toisteista tietoa vahvistuspalkista**
- **Kielitaidolle siirretään hylätty-arvosana, jos osakoe on hylätty**
- **Tarkenna vkt-päätason suorituksen näytettävät kentät**
- **Näytä useasti suoritetun vkt-osakokeen arvosanat haitarissa**
> TOR-2329: Kielitutkintojen muutoksia

- src/main/scala/fi/oph/koski/massaluovutus/MassaluovutusService.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureAikuistenPerusopetuksenOpiskeluoikeus.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureAmmatillinenTutkinto.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureDiaOpiskeluoikeus.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureEBOpiskeluoikeus.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureIBOpiskeluoikeus.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureInternationalSchoolOpiskeluoikeus.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureOpiskeluoikeus.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SurePerusopetuksenOpiskeluoikeus.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureTutkintokoulutukseenValmentavanOpiskeluoikeus.scala
- src/main/scala/fi/oph/koski/massaluovutus/suoritusrekisteri/opiskeluoikeus/SureVapaaSivistystyo.scala
- src/test/scala/fi/oph/koski/massaluovutus/MassaluovutusSpec.scala
Palauta rajapinnasta perusopetuksen oppimäärän osasuoritukset.
Käytä Kosken määriteltyä execution contextia MassaluovutusServicessä.
> TOR-2354 Lisää osasuoritukset sure-tietomallin perusopetuksen oppimäärään

- src/main/scala/fi/oph/koski/healthcheck/HealthChecker.scala
Lisättiin vain siksi, että saatiin kontit konsistentimmin kaatumaan, jos/kun ThreadPool on täynnä.
Tämän voi mergetä, kunhan on todettu, että ThreadPool-korjaukset toimii.
> TOR-xxxx: ONR taas pois internal healthcheckistä

- .github/skip_tiedonsiirtoprotokollan_muutoshistoria.md
- src/main/scala/fi/oph/koski/schema/Kielitutkinto.scala
- validaation_muutoshistoria.md
Kielitutkintojen näkökulmasta suoritukset ovat aina valmiita, kunhan ne on arvioitu, vaikka lopputulos olisikin hylätty.
> OPHKOTO-17: VKT-validaation muutos

- src/main/scala/fi/oph/koski/schema/Kielitutkinto.scala
- src/main/scala/fi/oph/koski/schema/Opiskeluoikeus.scala
- src/main/scala/fi/oph/koski/validation/DateValidation.scala
- tiedonsiirtoprotokollan_muutoshistoria.md
- validaation_muutoshistoria.md
Tyypillinen tapaus vkt-kielitutkinnoille on, että tutkinto ja arviointi ovat samana päivänä.
> OPHKOTO-17: Salli kielitutkinnoille sama alku- ja päättymispäivä

- src/main/resources/localization/koski-default-texts.json
- src/main/scala/fi/oph/koski/raportit/PaallekkaisetOpiskeluoikeudet.scala
ammatillisen tutkinnon osien suoritukselle useasta tutkinnosta
> TOR-2387 korjaa suorituksen nimi päällekkäisten opiskeluoikeuksien raporttiin

- src/main/scala/fi/oph/koski/massaluovutus/suorituspalvelu/opiskeluoikeus/SupaAmmatillinenOsittainen.scala
- src/main/scala/fi/oph/koski/massaluovutus/suorituspalvelu/opiskeluoikeus/SupaAmmatillinenTutkinto.scala
- src/main/scala/fi/oph/koski/massaluovutus/suorituspalvelu/opiskeluoikeus/SupaTelmaKoulutus.scala
- src/test/scala/fi/oph/koski/massaluovutus/MassaluovutusSpec.scala
Lisätään SUPA-rajapinnan ammatillisen opiskeluoikeuden tietomalliin myös tyyppiä 'ammatillinentutkintoosittainen' oleva päätason suoritus
> TOR-2386 SUPA-rajapinnan tietomalliin ammatillinentutkintoosittainen
